//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolumeControl.Hotkeys {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    public sealed partial class HotkeyManagerSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static HotkeyManagerSettings defaultInstance = ((HotkeyManagerSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HotkeyManagerSettings())));
        
        public static HotkeyManagerSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Hotkeys {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Hotkeys"]));
            }
            set {
                this["Hotkeys"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>Volume Up::VolumeUp::Volume Up</string>
  <string>Volume Down::VolumeDown::Volume Down</string>
  <string>Toggle Mute::VolumeMute::Toggle Mute</string>
  <string>Next Session::Ctrl+Shift+Alt+E::Select Next Session</string>
  <string>Previous Session::Ctrl+Shift+Alt+Q::Select Previous Session</string>
  <string>Lock Session::Ctrl+Shift+Alt+S::Toggle Session Lock</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Hotkeys_Default {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Hotkeys_Default"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReloadOnHotkey {
            get {
                return ((bool)(this["ReloadOnHotkey"]));
            }
            set {
                this["ReloadOnHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReloadOnInterval {
            get {
                return ((bool)(this["ReloadOnInterval"]));
            }
            set {
                this["ReloadOnInterval"] = value;
            }
        }
    }
}
