//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolumeControl.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+VolumeUp")]
        public string hks_VolumeUp {
            get {
                return ((string)(this["hks_VolumeUp"]));
            }
            set {
                this["hks_VolumeUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+VolumeDown")]
        public string hks_VolumeDown {
            get {
                return ((string)(this["hks_VolumeDown"]));
            }
            set {
                this["hks_VolumeDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+VolumeMute")]
        public string hks_VolumeToggle {
            get {
                return ((string)(this["hks_VolumeToggle"]));
            }
            set {
                this["hks_VolumeToggle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string hks_MediaNext {
            get {
                return ((string)(this["hks_MediaNext"]));
            }
            set {
                this["hks_MediaNext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string hks_MediaPrev {
            get {
                return ((string)(this["hks_MediaPrev"]));
            }
            set {
                this["hks_MediaPrev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string hks_MediaToggle {
            get {
                return ((string)(this["hks_MediaToggle"]));
            }
            set {
                this["hks_MediaToggle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CtrlShift+E")]
        public string hks_TargetNext {
            get {
                return ((string)(this["hks_TargetNext"]));
            }
            set {
                this["hks_TargetNext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CtrlShift+Q")]
        public string hks_TargetPrev {
            get {
                return ((string)(this["hks_TargetPrev"]));
            }
            set {
                this["hks_TargetPrev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CtrlShift+S")]
        public string hks_TargetToggle {
            get {
                return ((string)(this["hks_TargetToggle"]));
            }
            set {
                this["hks_TargetToggle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("volumecontrol.log")]
        public string log_file {
            get {
                return ((string)(this["log_file"]));
            }
            set {
                this["log_file"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hks_VolumeUpEnabled {
            get {
                return ((bool)(this["hks_VolumeUpEnabled"]));
            }
            set {
                this["hks_VolumeUpEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hks_VolumeDownEnabled {
            get {
                return ((bool)(this["hks_VolumeDownEnabled"]));
            }
            set {
                this["hks_VolumeDownEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hks_VolumeToggleEnabled {
            get {
                return ((bool)(this["hks_VolumeToggleEnabled"]));
            }
            set {
                this["hks_VolumeToggleEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hks_MediaNextEnabled {
            get {
                return ((bool)(this["hks_MediaNextEnabled"]));
            }
            set {
                this["hks_MediaNextEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hks_MediaPrevEnabled {
            get {
                return ((bool)(this["hks_MediaPrevEnabled"]));
            }
            set {
                this["hks_MediaPrevEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hks_MediaToggleEnabled {
            get {
                return ((bool)(this["hks_MediaToggleEnabled"]));
            }
            set {
                this["hks_MediaToggleEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hks_TargetNextEnabled {
            get {
                return ((bool)(this["hks_TargetNextEnabled"]));
            }
            set {
                this["hks_TargetNextEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hks_TargetPrevEnabled {
            get {
                return ((bool)(this["hks_TargetPrevEnabled"]));
            }
            set {
                this["hks_TargetPrevEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hks_TargetToggleEnabled {
            get {
                return ((bool)(this["hks_TargetToggleEnabled"]));
            }
            set {
                this["hks_TargetToggleEnabled"] = value;
            }
        }
    }
}
