var searchData=
[
  ['baseaddon_31',['BaseAddon',['../class_volume_control_1_1_core_1_1_base_addon.html',1,'VolumeControl.Core.BaseAddon'],['../class_volume_control_1_1_core_1_1_base_addon.html#a85b7c33c43ccb419d5a356cab2f12263',1,'VolumeControl.Core.BaseAddon.BaseAddon()']]],
  ['baseaddonattribute_32',['BaseAddonAttribute',['../class_volume_control_1_1_core_1_1_base_addon_attribute.html',1,'VolumeControl.Core.BaseAddonAttribute'],['../class_volume_control_1_1_core_1_1_base_addon_attribute.html#a2eec4e0cc3d53e8dbcfc30450d301e3a',1,'VolumeControl.Core.BaseAddonAttribute.BaseAddonAttribute(string addonName, CompatibleVersions compatibleVersions)'],['../class_volume_control_1_1_core_1_1_base_addon_attribute.html#a2b07109e02afb99f2509f19409bfcc11',1,'VolumeControl.Core.BaseAddonAttribute.BaseAddonAttribute(string addonName)']]],
  ['bindableeventtype_33',['BindableEventType',['../class_volume_control_1_1_w_p_f_1_1_collections_1_1_bindable_event_type.html',1,'VolumeControl.WPF.Collections.BindableEventType'],['../class_volume_control_1_1_w_p_f_1_1_collections_1_1_bindable_event_type.html#a3314c7aea60da61ebeead00db159e978',1,'VolumeControl.WPF.Collections.BindableEventType.BindableEventType()'],['../class_volume_control_1_1_w_p_f_1_1_collections_1_1_bindable_event_type.html#adf3aca44b99226c8ff32fcfea923f313',1,'VolumeControl.WPF.Collections.BindableEventType.BindableEventType(EventType ev)']]],
  ['bindableeventtypeflag_34',['BindableEventTypeFlag',['../class_volume_control_1_1_w_p_f_1_1_collections_1_1_bindable_event_type_1_1_bindable_event_type_flag.html',1,'VolumeControl.WPF.Collections.BindableEventType.BindableEventTypeFlag'],['../class_volume_control_1_1_w_p_f_1_1_collections_1_1_bindable_event_type_1_1_bindable_event_type_flag.html#a6ebd91f6bf99462f76c3872fbd4a3f60',1,'VolumeControl.WPF.Collections.BindableEventType.BindableEventTypeFlag.BindableEventTypeFlag()']]],
  ['bindablewindowshotkey_35',['BindableWindowsHotkey',['../class_volume_control_1_1_hotkeys_1_1_bindable_windows_hotkey.html',1,'VolumeControl.Hotkeys.BindableWindowsHotkey'],['../class_volume_control_1_1_hotkeys_1_1_bindable_windows_hotkey.html#a905e493f46f1128a45009bf88752ab3d',1,'VolumeControl.Hotkeys.BindableWindowsHotkey.BindableWindowsHotkey()']]],
  ['bindings_36',['Bindings',['../interface_volume_control_1_1_hotkeys_1_1_interfaces_1_1_i_hotkey_action_manager.html#a03c5f4b40ed4b81f4ec77122e2c7a973',1,'VolumeControl::Hotkeys::Interfaces::IHotkeyActionManager']]],
  ['blacklist_37',['Blacklist',['../class_hotkey_lib_1_1_keys_blacklist.html#abe578c90e955bf1c948348dcabd08767',1,'HotkeyLib::KeysBlacklist']]],
  ['blank_38',['Blank',['../class_volume_control_1_1_log_1_1_timestamp.html#a17674d5dc5d93b90ec85e381859c2152',1,'VolumeControl::Log::Timestamp']]],
  ['booleaninverter_39',['BooleanInverter',['../class_volume_control_1_1_w_p_f_1_1_converters_1_1_boolean_inverter.html',1,'VolumeControl::WPF::Converters']]],
  ['booltocheckvisibleconverter_40',['BoolToCheckVisibleConverter',['../class_volume_control_1_1_w_p_f_1_1_converters_1_1_bool_to_check_visible_converter.html',1,'VolumeControl::WPF::Converters']]],
  ['booltothicknessconverter_41',['BoolToThicknessConverter',['../class_volume_control_1_1_w_p_f_1_1_converters_1_1_bool_to_thickness_converter.html',1,'VolumeControl::WPF::Converters']]],
  ['booltovalueconverter_42',['BoolToValueConverter',['../class_volume_control_1_1_w_p_f_1_1_converters_1_1_bool_to_value_converter.html',1,'VolumeControl.WPF.Converters.BoolToValueConverter&lt; T &gt;'],['../class_volume_control_1_1_w_p_f_1_1_converters_1_1_bool_to_value_converter.html#a0a4f1cc2c94c1e9a6b9889cad155a406',1,'VolumeControl.WPF.Converters.BoolToValueConverter.BoolToValueConverter()']]],
  ['bottom_43',['bottom',['../struct_volume_control_1_1_w_p_f_1_1_r_e_c_t.html#aa775b423ffba15abc7fadd680ccd5967',1,'VolumeControl::WPF::RECT']]],
  ['building_20from_20source_44',['Building From Source',['../md_docs__building_from_source.html',1,'']]]
];
