var searchData=
[
  ['iactionbinding_751',['IActionBinding',['../interface_volume_control_1_1_core_1_1_keyboard_1_1_actions_1_1_i_action_binding.html',1,'VolumeControl::Core::Keyboard::Actions']]],
  ['ibaseaddon_752',['IBaseAddon',['../interface_volume_control_1_1_core_1_1_i_base_addon.html',1,'VolumeControl::Core']]],
  ['ibaseaddonattribute_753',['IBaseAddonAttribute',['../interface_volume_control_1_1_core_1_1_i_base_addon_attribute.html',1,'VolumeControl::Core']]],
  ['ibindablehotkey_754',['IBindableHotkey',['../interface_volume_control_1_1_core_1_1_keyboard_1_1_i_bindable_hotkey.html',1,'VolumeControl::Core::Keyboard']]],
  ['icongetter_755',['IconGetter',['../class_volume_control_1_1_w_p_f_1_1_icon_getter.html',1,'VolumeControl::WPF']]],
  ['iconpair_756',['IconPair',['../class_volume_control_1_1_w_p_f_1_1_icon_pair.html',1,'VolumeControl::WPF']]],
  ['idevice_757',['IDevice',['../interface_volume_control_1_1_audio_1_1_interfaces_1_1_i_device.html',1,'VolumeControl::Audio::Interfaces']]],
  ['iendpoint_758',['IEndpoint',['../interface_volume_control_1_1_log_1_1_endpoints_1_1_i_endpoint.html',1,'VolumeControl::Log::Endpoints']]],
  ['ihotkey_759',['IHotkey',['../interface_volume_control_1_1_core_1_1_keyboard_1_1_i_hotkey.html',1,'VolumeControl::Core::Keyboard']]],
  ['ihotkeyactionmanager_760',['IHotkeyActionManager',['../interface_volume_control_1_1_hotkeys_1_1_interfaces_1_1_i_hotkey_action_manager.html',1,'VolumeControl::Hotkeys::Interfaces']]],
  ['ilogwriter_761',['ILogWriter',['../interface_volume_control_1_1_log_1_1_interfaces_1_1_i_log_writer.html',1,'VolumeControl::Log::Interfaces']]],
  ['initializer_762',['Initializer',['../class_volume_control_1_1_s_d_k_1_1_internal_1_1_initializer.html',1,'VolumeControl::SDK::Internal']]],
  ['int32extensions_763',['Int32Extensions',['../class_volume_control_1_1_type_extensions_1_1_int32_extensions.html',1,'VolumeControl::TypeExtensions']]],
  ['iprocess_764',['IProcess',['../interface_volume_control_1_1_audio_1_1_interfaces_1_1_i_process.html',1,'VolumeControl::Audio::Interfaces']]],
  ['isession_765',['ISession',['../interface_volume_control_1_1_audio_1_1_interfaces_1_1_i_session.html',1,'VolumeControl::Audio::Interfaces']]],
  ['isessionextensions_766',['ISessionExtensions',['../class_volume_control_1_1_audio_1_1_interfaces_1_1_i_session_extensions.html',1,'VolumeControl::Audio::Interfaces']]],
  ['itargetable_767',['ITargetable',['../interface_volume_control_1_1_audio_1_1_interfaces_1_1_i_targetable.html',1,'VolumeControl::Audio::Interfaces']]],
  ['itimestamp_768',['ITimestamp',['../interface_volume_control_1_1_log_1_1_interfaces_1_1_i_timestamp.html',1,'VolumeControl::Log::Interfaces']]]
];
