Volume Control: VolumeControl.Core.Input.HotkeyActionPressedEventArgs Class Reference
VolumeControl.Core.Input.HotkeyActionPressedEventArgs Class Reference
Event arguments for hotkey action events.
Public Member Functions
HotkeyActionPressedEventArgs ()
Creates a new HotkeyActionPressedEventArgs instance without any action settings.
HotkeyActionPressedEventArgs (bool defaultHandledValue)
Creates a new HotkeyActionPressedEventArgs instance without any action settings.
HotkeyActionPressedEventArgs (IActionSettingInstance[] actionSettings)
Creates a new HotkeyActionPressedEventArgs instance with the specified actionSettings .
HotkeyActionPressedEventArgs (IActionSettingInstance[] actionSettings, bool defaultHandledValue)
Creates a new HotkeyActionPressedEventArgs instance with the specified actionSettings .
IActionSettingInstance? GetSetting (string name, StringComparison stringComparison=StringComparison.Ordinal)
Gets the first IActionSettingInstance instance with the specified name .
IActionSettingInstance< TValue > GetSetting< TValue > (string name, StringComparison stringComparison=StringComparison.Ordinal)
Gets the IActionSettingInstance instance with the specified name and value type.
bool TryGetSetting< TValue > (string name, StringComparison stringComparison, out IActionSettingInstance< TValue > actionSetting)
Attempts to get the IActionSettingInstance instance with the specified name and value type.
object? GetValue (string name, StringComparison stringComparison=StringComparison.Ordinal)
Gets the value of the first action setting with the specified name .
TValue? GetValue< TValue > (string name, StringComparison stringComparison=StringComparison.Ordinal)
Gets the value of the IActionSettingInstance instance with the specified name and value type.
TValue GetValueOrDefault< TValue > (string name, StringComparison stringComparison, TValue defaultValue=default!)
Gets the value of the IActionSettingInstance instance with the specified name and value type, or the defaultValue if one wasn't found.
TValue GetValueOrDefault< TValue > (string name, TValue defaultValue=default!)
Properties
IActionSettingInstance[] Settings [get]
Gets the array of ActionSettings configured for the hotkey that triggered the event.
Detailed Description
Event arguments for hotkey action events.
Constructor & Destructor Documentation
HotkeyActionPressedEventArgs() [1/4]
VolumeControl.Core.Input.HotkeyActionPressedEventArgs.HotkeyActionPressedEventArgs ()
Creates a new HotkeyActionPressedEventArgs instance without any action settings.
References VolumeControl.Core.Input.HotkeyActionPressedEventArgs.Settings.
HotkeyActionPressedEventArgs() [2/4]
VolumeControl.Core.Input.HotkeyActionPressedEventArgs.HotkeyActionPressedEventArgs (bool defaultHandledValue)
Creates a new HotkeyActionPressedEventArgs instance without any action settings.
Parameters
defaultHandledValue The default value for the HandledEventArgs.Handled property.
References VolumeControl.Core.Input.HotkeyActionPressedEventArgs.Settings.
HotkeyActionPressedEventArgs() [3/4]
VolumeControl.Core.Input.HotkeyActionPressedEventArgs.HotkeyActionPressedEventArgs (IActionSettingInstance[] actionSettings)
Creates a new HotkeyActionPressedEventArgs instance with the specified actionSettings .
Parameters
actionSettings The array of settings to send to the action method.
References VolumeControl.Core.Input.HotkeyActionPressedEventArgs.Settings.
HotkeyActionPressedEventArgs() [4/4]
VolumeControl.Core.Input.HotkeyActionPressedEventArgs.HotkeyActionPressedEventArgs (IActionSettingInstance[] actionSettings, bool defaultHandledValue)
Creates a new HotkeyActionPressedEventArgs instance with the specified actionSettings .
Parameters
actionSettings The array of settings to send to the action method.
defaultHandledValue The default value for the HandledEventArgs.Handled property.
References VolumeControl.Core.Input.HotkeyActionPressedEventArgs.Settings.
Member Function Documentation
GetSetting()
IActionSettingInstance? VolumeControl.Core.Input.HotkeyActionPressedEventArgs.GetSetting (string name, StringComparison stringComparison = StringComparison.Ordinal)
Gets the first IActionSettingInstance instance with the specified name .
Parameters
name The name of the action setting to get.
stringComparison The type of StringComparison to use when comparing strings.
Returns
The first IActionSettingInstance instance with the specified name when one was found; otherwise null.
References VolumeControl.Core.Input.HotkeyActionPressedEventArgs.Settings.
GetSetting< TValue >()
IActionSettingInstance<TValue> VolumeControl.Core.Input.HotkeyActionPressedEventArgs.GetSetting< TValue > (string name, StringComparison stringComparison = StringComparison.Ordinal)
Gets the IActionSettingInstance instance with the specified name and value type.
Template Parameters
TValue The value type of the action setting to get.
Parameters
name The name of the action setting to get.
stringComparison The type of StringComparison to use when comparing strings.
Returns
The IActionSettingInstance instance with the specified name and the same ValueType as TValue .
Exceptions
ActionSettingNotFoundException There is no action setting with the specified name and value type.
References VolumeControl.Core.Input.HotkeyActionPressedEventArgs.Settings.
Referenced by VolumeControl.Core.Input.HotkeyActionPressedEventArgs.TryGetSetting< TValue >().
GetValue()
object? VolumeControl.Core.Input.HotkeyActionPressedEventArgs.GetValue (string name, StringComparison stringComparison = StringComparison.Ordinal)
Gets the value of the first action setting with the specified name .
Parameters
name The name of the action setting to get the value of.
stringComparison The type of StringComparison to use when comparing strings.
Returns
The value of the first action setting with the specified name when found; otherwise null.
GetValue< TValue >()
TValue? VolumeControl.Core.Input.HotkeyActionPressedEventArgs.GetValue< TValue > (string name, StringComparison stringComparison = StringComparison.Ordinal)
Gets the value of the IActionSettingInstance instance with the specified name and value type.
Template Parameters
TValue The value type of the action setting to get.
Parameters
name The name of the action setting to get the value of.
stringComparison The type of StringComparison to use when comparing strings.
Returns
The value of the action setting with the specified name and the same ValueType as TValue .
Exceptions
ActionSettingNotFoundException There is no action setting with the specified name and value type.
GetValueOrDefault< TValue >()
TValue VolumeControl.Core.Input.HotkeyActionPressedEventArgs.GetValueOrDefault< TValue > (string name, StringComparison stringComparison, TValue defaultValue = default!)
Gets the value of the IActionSettingInstance instance with the specified name and value type, or the defaultValue if one wasn't found.
Template Parameters
TValue The value type of the action setting to get.
Parameters
name The name of the action setting to get the value of.
stringComparison The type of StringComparison to use when comparing strings.
defaultValue A default TValue instance to return if no settings with the specified name were found.
Returns
The value of the action setting with the specified name and the same ValueType as TValue when found; otherwise defaultValue .
References VolumeControl.Core.Input.HotkeyActionPressedEventArgs.TryGetSetting< TValue >().
TryGetSetting< TValue >()
bool VolumeControl.Core.Input.HotkeyActionPressedEventArgs.TryGetSetting< TValue > (string name, StringComparison stringComparison, out IActionSettingInstance< TValue > actionSetting)
Attempts to get the IActionSettingInstance instance with the specified name and value type.
Template Parameters
TValue The value type of the action setting to get.
Parameters
name The name of the action setting to get.
stringComparison The type of StringComparison to use when comparing strings.
actionSetting The IActionSettingInstance instance with the specified name and the same ValueType as TValue .
Returns
true when no errors occurred and actionSetting is not null; otherwise false.
References VolumeControl.Core.Input.HotkeyActionPressedEventArgs.GetSetting< TValue >().
Referenced by VolumeControl.Core.Input.HotkeyActionPressedEventArgs.GetValueOrDefault< TValue >().
Property Documentation
Settings
IActionSettingInstance [] VolumeControl.Core.Input.HotkeyActionPressedEventArgs.Settings get
Gets the array of ActionSettings configured for the hotkey that triggered the event.
Referenced by VolumeControl.Core.Input.HotkeyActionPressedEventArgs.GetSetting(), VolumeControl.Core.Input.HotkeyActionPressedEventArgs.GetSetting< TValue >(), and VolumeControl.Core.Input.HotkeyActionPressedEventArgs.HotkeyActionPressedEventArgs().
The documentation for this class was generated from the following file:
/home/runner/work/volume-control/volume-control/VolumeControl.Core/Input/HotkeyActionPressedEventArgs.cs