Volume Control: VolumeControl.Hotkeys.HotkeyManager Class Reference
VolumeControl.Hotkeys.HotkeyManager Class Reference
This object is responsible for managing hotkeys at runtime.
Public Member Functions
HotkeyManager (IHotkeyActionManager actionManager, HWndHook hook, bool loadNow=false)
void AddHotkey (BindableWindowsHotkey hk)
Create a new hotkey and add it to Hotkeys.
void AddHotkey (string name, IKeyCombo keys, string action, bool registerNow=false)
Create a new hotkey and add it to Hotkeys.
void AddHotkey ()
Create a new blank hotkey and add it to Hotkeys.
void DelHotkey (BindableWindowsHotkey? hk)
Remove the specified hotkey from Hotkeys.
void DelHotkey (int id)
Remove the specified hotkey from Hotkeys.
void DelAllHotkeys ()
Deletes all hotkeys in the list by first disposing them, then removing them from the list.
BindableWindowsHotkey? GetHotkey (int id)
Gets a single BindableWindowsHotkey from the list by checking for matching id numbers.
void LoadHotkeys ()
Loads hotkeys from the settings file and binds them to the associated actions.
void SaveHotkeys ()
Saves all hotkeys to the settings file.
void ResetHotkeys ()
Resets the current hotkey list by replacing it with HotkeyManagerSettings.Hotkeys_Default.
void Dispose ()
Public Attributes
readonly IntPtr OwnerHandle
This is the handle used to register hotkeys with the Win32 API.
IHotkeyActionManager Actions => _hotkeyActions
Action manager object
Protected Member Functions
virtual void NotifyPropertyChanged ([CallerMemberName] string propertyName="")
Triggers the PropertyChanged event.
virtual IntPtr HwndHook (IntPtr hWnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
Handles window messages, and triggers WindowsHotkey.Pressed events.
Properties
NotifyCollectionChangedEventHandler? CollectionChanged
Forwards all collection changed events from Hotkeys.
ObservableList< BindableWindowsHotkey > Hotkeys = new() [get]
List of hotkeys.
bool? AllSelected [get, set]
This is used as the binding source for the (un)register all checkbox in the column header.
Events
PropertyChangedEventHandler? PropertyChanged
Triggered after the value changes when a property's setter is called.
Detailed Description
This object is responsible for managing hotkeys at runtime.
Constructor & Destructor Documentation
HotkeyManager()
VolumeControl.Hotkeys.HotkeyManager.HotkeyManager (IHotkeyActionManager actionManager, HWndHook hook, bool loadNow = false)
Parameters
actionManager The action manager to use.
hook The HWndHook instance to use.
loadNow When true, the LoadHotkeys method is called from the constructor. Set this to false if you want to do it yourself.
Member Function Documentation
AddHotkey() [1/3]
void VolumeControl.Hotkeys.HotkeyManager.AddHotkey ()
Create a new blank hotkey and add it to Hotkeys.
BindableWindowsHotkey.Name = string.Empty
AddHotkey() [2/3]
void VolumeControl.Hotkeys.HotkeyManager.AddHotkey (BindableWindowsHotkey hk)
Create a new hotkey and add it to Hotkeys.
AddHotkey() [3/3]
void VolumeControl.Hotkeys.HotkeyManager.AddHotkey (string name, IKeyCombo keys, string action, bool registerNow = false)
Create a new hotkey and add it to Hotkeys.
Parameters
name The name of the new hotkey.
keys The key combination of the new hotkey.
action The associated action of the new hotkey.
registerNow When true, the new hotkey is registered immediately after construction.
References VolumeControl.Hotkeys.HotkeyManager.Hotkeys, and VolumeControl.Log.LogWriter.Info().
DelAllHotkeys()
void VolumeControl.Hotkeys.HotkeyManager.DelAllHotkeys ()
Deletes all hotkeys in the list by first disposing them, then removing them from the list.
References VolumeControl.Hotkeys.HotkeyManager.Hotkeys.
Referenced by VolumeControl.Hotkeys.HotkeyManager.ResetHotkeys().
DelHotkey() [1/2]
void VolumeControl.Hotkeys.HotkeyManager.DelHotkey (BindableWindowsHotkey? hk)
Remove the specified hotkey from Hotkeys.
Parameters
hk The BindableWindowsHotkey object to remove.
If this is null, nothing happens.
References VolumeControl.Hotkeys.HotkeyManager.Hotkeys, and VolumeControl.Log.LogWriter.Info().
DelHotkey() [2/2]
void VolumeControl.Hotkeys.HotkeyManager.DelHotkey (int id)
Remove the specified hotkey from Hotkeys.
Parameters
id The ID number of the hotkey to delete.
References VolumeControl.Hotkeys.HotkeyManager.Hotkeys.
GetHotkey()
BindableWindowsHotkey? VolumeControl.Hotkeys.HotkeyManager.GetHotkey (int id)
Gets a single BindableWindowsHotkey from the list by checking for matching id numbers.
Parameters
id The ID number of the target hotkey.
(This is compared to the BindableWindowsHotkey.ID property.)
Returns
The target BindableWindowsHotkey instance if successful; otherwise null.
HwndHook()
virtual IntPtr VolumeControl.Hotkeys.HotkeyManager.HwndHook (IntPtr hWnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled) protected virtual
Handles window messages, and triggers WindowsHotkey.Pressed events.
LoadHotkeys()
void VolumeControl.Hotkeys.HotkeyManager.LoadHotkeys ()
Loads hotkeys from the settings file and binds them to the associated actions.
Make sure that the Actions property is set and initialized before calling this!
Referenced by VolumeControl.Hotkeys.HotkeyManager.ResetHotkeys().
NotifyPropertyChanged()
virtual void VolumeControl.Hotkeys.HotkeyManager.NotifyPropertyChanged ([CallerMemberName] string propertyName = "") protected virtual
Triggers the PropertyChanged event.
Parameters
propertyName This is automatically retrieved using reflection; it is the name of the property that was changed.
ResetHotkeys()
void VolumeControl.Hotkeys.HotkeyManager.ResetHotkeys ()
Resets the current hotkey list by replacing it with HotkeyManagerSettings.Hotkeys_Default.
References VolumeControl.Hotkeys.HotkeyManager.DelAllHotkeys(), and VolumeControl.Hotkeys.HotkeyManager.LoadHotkeys().
SaveHotkeys()
void VolumeControl.Hotkeys.HotkeyManager.SaveHotkeys ()
Saves all hotkeys to the settings file.
References VolumeControl.Log.LogWriter.Debug(), VolumeControl.Hotkeys.BindableWindowsHotkey.GetFullIdentifier(), VolumeControl.Hotkeys.HotkeyManager.Hotkeys, and VolumeControl.Hotkeys.BindableWindowsHotkey.Serialize().
Member Data Documentation
Actions
IHotkeyActionManager VolumeControl.Hotkeys.HotkeyManager.Actions => _hotkeyActions
Action manager object
OwnerHandle
readonly IntPtr VolumeControl.Hotkeys.HotkeyManager.OwnerHandle
This is the handle used to register hotkeys with the Win32 API.
Referenced by VolumeControl.Hotkeys.BindableWindowsHotkey.BindableWindowsHotkey().
Property Documentation
AllSelected
bool? VolumeControl.Hotkeys.HotkeyManager.AllSelected get set
This is used as the binding source for the (un)register all checkbox in the column header.
CollectionChanged
NotifyCollectionChangedEventHandler? VolumeControl.Hotkeys.HotkeyManager.CollectionChanged add remove
Forwards all collection changed events from Hotkeys.
Hotkeys
ObservableList<BindableWindowsHotkey> VolumeControl.Hotkeys.HotkeyManager.Hotkeys = new() get
List of hotkeys.
Referenced by VolumeControl.Hotkeys.HotkeyManager.AddHotkey(), VolumeControl.Hotkeys.HotkeyManager.DelAllHotkeys(), VolumeControl.Hotkeys.HotkeyManager.DelHotkey(), and VolumeControl.Hotkeys.HotkeyManager.SaveHotkeys().
Event Documentation
PropertyChanged
PropertyChangedEventHandler? VolumeControl.Hotkeys.HotkeyManager.PropertyChanged
Triggered after the value changes when a property's setter is called.
The documentation for this class was generated from the following file:
/home/runner/work/volume-control/volume-control/VolumeControl.Hotkeys/HotkeyManager.cs