Volume Control: VolumeControl.Core.Input.Hotkey Class Reference
VolumeControl.Core.Input.Hotkey Class Reference
A hotkey that executes an action when pressed.
Public Member Functions
Hotkey (string name, EFriendlyKey key, EModifierKey modifiers, bool isRegistered, HotkeyActionInstance actionInstance)
Creates a new Hotkey instance with the specified parameters.
Hotkey (string name, EFriendlyKey key, EModifierKey modifiers, bool isRegistered)
Hotkey (EFriendlyKey key, EModifierKey modifiers, bool isRegistered, HotkeyActionInstance actionInstance)
Hotkey (EFriendlyKey key, EModifierKey modifiers, bool isRegistered)
void GetNewID ()
Gets a new ID from the WindowsHotkeyAPI.
void Dispose ()
Protected Member Functions
void NotifyPropertyChanged ([CallerMemberName] string propertyName="")
Triggers the PropertyChanged event.
virtual bool Register ()
Registers the hotkey with the Win32 API.
virtual bool Unregister ()
Unregisters the hotkey with the Win32 API.
virtual bool Reregister ()
Re-registers the hotkey with the Win32 API.
virtual void Dispose (bool disposing)
Properties
int ID [get]
string Name [get, set]
EFriendlyKey Key [get, set]
EModifierKey Modifiers [get, set]
bool Alt [get, set]
bool Shift [get, set]
bool Ctrl [get, set]
bool Win [get, set]
bool NoRepeat [get, set]
HwndSourceHook MessageHook [get]
virtual bool IsRegistered [get, set]
HotkeyActionInstance? Action [get, set]
Properties inherited from VolumeControl.Core.Input.IHotkey
string Name [get, set]
Gets or sets the friendly name of this hotkey.
int ID [get]
Gets the ID number of this hotkey.
EFriendlyKey Key [get, set]
Gets or sets the main key for this hotkey.
EModifierKey Modifiers [get, set]
Gets or sets the modifier keys for this hotkey.
bool Alt [get, set]
Gets or sets whether the Alt modifier key is enabled.
bool Shift [get, set]
Gets or sets whether the Shift modifier key is enabled.
bool Ctrl [get, set]
Gets or sets whether the Ctrl modifier key is enabled.
bool Win [get, set]
Gets or sets whether the Win modifier key is enabled.
bool NoRepeat [get, set]
Gets or sets whether NoRepeat is enabled.
HwndSourceHook MessageHook [get]
Gets the windows message hook for this hotkey.
bool IsRegistered [get, set]
Gets or sets whether this hotkey is registered with the Win32 API.
HotkeyActionInstance? Action [get, set]
Gets or sets the action that this hotkey triggers when pressed.
Events
HotkeyActionPressedEventHandler? Pressed
Occurs when the hotkey was pressed, after the Action has been triggered.
PropertyChangedEventHandler? PropertyChanged
Events inherited from VolumeControl.Core.Input.IHotkey
HotkeyActionPressedEventHandler? Pressed
Occurs when the hotkey combination was pressed.
Detailed Description
A hotkey that executes an action when pressed.
Constructor & Destructor Documentation
Hotkey()
VolumeControl.Core.Input.Hotkey.Hotkey (string name, EFriendlyKey key, EModifierKey modifiers, bool isRegistered, HotkeyActionInstance actionInstance)
Creates a new Hotkey instance with the specified parameters.
Parameters
name The name of the hotkey.
key The primary key of the hotkey combination.
modifiers The modifier keys of the hotkey combination.
isRegistered The registration state of the hotkey.
actionInstance The action to trigger when the hotkey is pressed.
References VolumeControl.Core.Input.Hotkey.Action, VolumeControl.Core.Input.Hotkey.ID, VolumeControl.Core.Input.Hotkey.IsRegistered, VolumeControl.Core.Input.Hotkey.Key, VolumeControl.Core.Input.Hotkey.Modifiers, and VolumeControl.Core.Input.Hotkey.Name.
Member Function Documentation
GetNewID()
void VolumeControl.Core.Input.Hotkey.GetNewID ()
Gets a new ID from the WindowsHotkeyAPI.
This method automatically unregisters & reregisters the hotkey when called.
References VolumeControl.Core.Input.Hotkey.ID, VolumeControl.Core.Input.Hotkey.IsRegistered, VolumeControl.Core.Input.Hotkey.Register(), and VolumeControl.Core.Input.Hotkey.Unregister().
NotifyPropertyChanged()
void VolumeControl.Core.Input.Hotkey.NotifyPropertyChanged ([CallerMemberName] string propertyName = "") protected
Triggers the PropertyChanged event.
Parameters
propertyName The name of the property that was changed.
Referenced by VolumeControl.Core.Input.Hotkey.Reregister().
Register()
virtual bool VolumeControl.Core.Input.Hotkey.Register () protected virtual
Registers the hotkey with the Win32 API.
Returns
true when successful; otherwise false.
Reimplemented in VolumeControl.Core.Input.HotkeyWithError.
References VolumeControl.Core.Input.Hotkey.IsRegistered, and VolumeControl.Core.Input.WindowsHotkeyAPI.TryRegister().
Referenced by VolumeControl.Core.Input.Hotkey.GetNewID(), and VolumeControl.Core.Input.Hotkey.Reregister().
Reregister()
virtual bool VolumeControl.Core.Input.Hotkey.Reregister () protected virtual
Re-registers the hotkey with the Win32 API.
Returns
true when successful; otherwise false.
References VolumeControl.Core.Input.Hotkey.IsRegistered, VolumeControl.Core.Input.Hotkey.NotifyPropertyChanged(), VolumeControl.Core.Input.Hotkey.Register(), and VolumeControl.Core.Input.Hotkey.Unregister().
Unregister()
virtual bool VolumeControl.Core.Input.Hotkey.Unregister () protected virtual
Unregisters the hotkey with the Win32 API.
Returns
true when successful; otherwise false.
Reimplemented in VolumeControl.Core.Input.HotkeyWithError.
References VolumeControl.Core.Input.Hotkey.IsRegistered, and VolumeControl.Core.Input.WindowsHotkeyAPI.TryUnregister().
Referenced by VolumeControl.Core.Input.Hotkey.Dispose(), VolumeControl.Core.Input.Hotkey.GetNewID(), and VolumeControl.Core.Input.Hotkey.Reregister().
Event Documentation
Pressed
HotkeyActionPressedEventHandler? VolumeControl.Core.Input.Hotkey.Pressed
Occurs when the hotkey was pressed, after the Action has been triggered.
The documentation for this class was generated from the following file:
/home/runner/work/volume-control/volume-control/VolumeControl.Core/Input/Hotkey.cs