Volume Control: VolumeControl.Core.HotkeyManager Class Reference
VolumeControl.Core.HotkeyManager Class Reference
This object is responsible for managing hotkeys at runtime.
Public Member Functions
HotkeyManager (IHotkeyActionManager actionManager)
void AddHotkey (IBindableHotkey hk)
Create a new hotkey and add it to Hotkeys.
void AddHotkey ()
Create a new blank hotkey and add it to Hotkeys.
void DelHotkey (IBindableHotkey? hk)
Remove the specified hotkey from Hotkeys.
void DelHotkey (int id)
Remove the specified hotkey from Hotkeys.
void DelAllHotkeys ()
Deletes all hotkeys in the list by first disposing them, then removing them from the list.
IBindableHotkey? GetHotkey (int id)
Gets a single Hotkey from the list by checking for matching id numbers.
void LoadHotkeys ()
Loads hotkeys from the settings file and binds them to the associated actions.
void SaveHotkeys ()
Saves all hotkeys to the settings file.
void ResetHotkeys ()
Resets the current hotkey list by replacing it with Config.Hotkeys_Default.
void Dispose ()
bool IsUniqueID (int id)
Checks if the given id does not match any existing hotkeys.
int GetNextUniqueID ()
Gets the next unique hotkey ID by repeatedly calling WindowsHotkeyAPI.NextID until a unique ID is found.
Properties
NotifyCollectionChangedEventHandler? CollectionChanged
Forwards all collection changed events from Hotkeys.
IHotkeyActionManager Actions [get]
Action manager object
ObservableList< IBindableHotkey > Hotkeys = new() [get]
List of hotkeys.
bool? AllSelected [get, set]
This is used as the binding source for the (un)register all checkbox in the column header.
Events
PropertyChangedEventHandler? PropertyChanged
Triggered after the value changes when a property's setter is called.
Detailed Description
This object is responsible for managing hotkeys at runtime.
Constructor & Destructor Documentation
HotkeyManager()
VolumeControl.Core.HotkeyManager.HotkeyManager (IHotkeyActionManager actionManager)
Parameters
actionManager The action manager to use.
References VolumeControl.Core.HotkeyManager.Actions, and VolumeControl.Core.HotkeyManager.CollectionChanged.
Member Function Documentation
AddHotkey() [1/2]
void VolumeControl.Core.HotkeyManager.AddHotkey ()
Create a new blank hotkey and add it to Hotkeys.
BindableHotkey.Name = string.Empty
AddHotkey() [2/2]
void VolumeControl.Core.HotkeyManager.AddHotkey (IBindableHotkey hk)
Create a new hotkey and add it to Hotkeys.
References VolumeControl.Core.HotkeyManager.Hotkeys, and VolumeControl.Log.LogWriter.Info().
DelAllHotkeys()
void VolumeControl.Core.HotkeyManager.DelAllHotkeys ()
Deletes all hotkeys in the list by first disposing them, then removing them from the list.
References VolumeControl.Core.HotkeyManager.Hotkeys.
Referenced by VolumeControl.Core.HotkeyManager.ResetHotkeys().
DelHotkey() [1/2]
void VolumeControl.Core.HotkeyManager.DelHotkey (IBindableHotkey? hk)
Remove the specified hotkey from Hotkeys.
Parameters
hk The Hotkey object to remove.
If this is null, nothing happens.
References VolumeControl.Core.HotkeyManager.Hotkeys, and VolumeControl.Log.LogWriter.Info().
DelHotkey() [2/2]
void VolumeControl.Core.HotkeyManager.DelHotkey (int id)
Remove the specified hotkey from Hotkeys.
Parameters
id The Windows API ID number of the hotkey to delete.
References VolumeControl.Core.HotkeyManager.Hotkeys.
GetHotkey()
IBindableHotkey? VolumeControl.Core.HotkeyManager.GetHotkey (int id)
Gets a single Hotkey from the list by checking for matching id numbers.
Parameters
id The ID number of the target hotkey.
(This is compared to the Hotkey.ID property.)
Returns
The target Hotkey instance if successful; otherwise null.
GetNextUniqueID()
int VolumeControl.Core.HotkeyManager.GetNextUniqueID ()
Gets the next unique hotkey ID by repeatedly calling WindowsHotkeyAPI.NextID until a unique ID is found.
Returns
References VolumeControl.Core.HotkeyManager.IsUniqueID().
IsUniqueID()
bool VolumeControl.Core.HotkeyManager.IsUniqueID (int id)
Checks if the given id does not match any existing hotkeys.
Parameters
id The hotkey ID to check.
Returns
true when id is unique; otherwise false if an existing hotkey is already using it.
Referenced by VolumeControl.Core.HotkeyManager.GetNextUniqueID().
LoadHotkeys()
void VolumeControl.Core.HotkeyManager.LoadHotkeys ()
Loads hotkeys from the settings file and binds them to the associated actions.
Make sure that the Actions property is set and initialized before calling this!
References VolumeControl.Core.Config.Hotkeys, VolumeControl.Core.HotkeyManager.Hotkeys, and VolumeControl.Core.Config.Hotkeys_Default.
Referenced by VolumeControl.Core.HotkeyManager.ResetHotkeys().
ResetHotkeys()
void VolumeControl.Core.HotkeyManager.ResetHotkeys ()
Resets the current hotkey list by replacing it with Config.Hotkeys_Default.
References VolumeControl.Core.HotkeyManager.DelAllHotkeys(), VolumeControl.Core.Config.Hotkeys, and VolumeControl.Core.HotkeyManager.LoadHotkeys().
SaveHotkeys()
void VolumeControl.Core.HotkeyManager.SaveHotkeys ()
Saves all hotkeys to the settings file.
References VolumeControl.Core.Config.Hotkeys, and VolumeControl.Core.HotkeyManager.Hotkeys.
Property Documentation
Actions
IHotkeyActionManager VolumeControl.Core.HotkeyManager.Actions get
Action manager object
Referenced by VolumeControl.Core.HotkeyManager.HotkeyManager().
AllSelected
bool? VolumeControl.Core.HotkeyManager.AllSelected get set
This is used as the binding source for the (un)register all checkbox in the column header.
CollectionChanged
NotifyCollectionChangedEventHandler? VolumeControl.Core.HotkeyManager.CollectionChanged add remove
Forwards all collection changed events from Hotkeys.
Referenced by VolumeControl.Core.HotkeyManager.HotkeyManager().
Hotkeys
ObservableList<IBindableHotkey> VolumeControl.Core.HotkeyManager.Hotkeys = new() get
List of hotkeys.
Referenced by VolumeControl.Core.HotkeyManager.AddHotkey(), VolumeControl.Core.HotkeyManager.DelAllHotkeys(), VolumeControl.Core.HotkeyManager.DelHotkey(), VolumeControl.Core.HotkeyManager.LoadHotkeys(), and VolumeControl.Core.HotkeyManager.SaveHotkeys().
Event Documentation
PropertyChanged
PropertyChangedEventHandler? VolumeControl.Core.HotkeyManager.PropertyChanged
Triggered after the value changes when a property's setter is called.
The documentation for this class was generated from the following file:
/home/runner/work/volume-control/volume-control/VolumeControl.Core/HotkeyManager.cs