Volume Control: VolumeControl.Audio.AudioSession Class Reference
VolumeControl.Audio.AudioSession Class Reference
Represents an audio session playing on the system.
Public Member Functions
AudioSession (AudioSessionControl controller)
Process? GetProcess ()
Gets the process associated with this audio session instance.
void Dispose ()
Public Attributes
SimpleAudioVolume VolumeController => _controller.SimpleAudioVolume
Gets the SimpleAudioVolume object from the underlying AudioSessionControl type.
AudioSessionState State => _controller.State
Gets the current state of the audio session.
See AudioSessionState.
string IconPath => _controller.IconPath
This is the location of this sessions icon on the system and may or may not actually be set.
Do not rely on this being available, many third-party programs do not provide it!
ImageSource? SmallIcon => (_icons # this.GetIcons())?.Item1
The small icon located at the IconPath, or null if no icon was found.
ImageSource? LargeIcon => (_icons # this.GetIcons())?.Item2
The large icon located at the IconPath, or null if no icon was found.
ImageSource? Icon => SmallIcon ?? LargeIcon
Gets the large or small icon, depending on whether they are null or not.
string ProcessIdentifier => PID != -1L ? $"{PID}:{ProcessName}" : string.Empty
Static Public Attributes
static int
Parses the given process identifier string into a PID and ProcessName.
Properties
int Volume [get, set]
float NativeVolume [get, set]
bool Muted [get, set]
string ProcessName [get]
long PID [get]
bool IsRunning [get]
Checks if the process that owns this session is still running.
Properties inherited from VolumeControl.Audio.Interfaces.ISession
int Volume [get, set]
Gets or sets the volume of this process using the int type in the range (0 - 100)
float NativeVolume [get, set]
Gets or sets the volume of this process using the native float type, in the range (0.0 (0%) - 1.0 (100%))
bool Muted [get, set]
Gets or sets whether the session is muted or not.
Properties inherited from VolumeControl.Audio.Interfaces.IProcess
string ProcessName [get]
Gets the process name of this process.
long PID [get]
Gets the process ID number of this process.
string ProcessIdentifier [get]
Gets the process identifier of this process.
Events
PropertyChangedEventHandler? PropertyChanged
Triggered after one of this instance's properties have been set.
PropertyChangingEventHandler? PropertyChanging
Triggered before one of this instance's properties is being set.
Detailed Description
Represents an audio session playing on the system.
Some properties in this object require the NAudio library.
If you're writing an addon, install the 'NAudio' nuget package if you need to be able to use them.
Constructor & Destructor Documentation
AudioSession()
VolumeControl.Audio.AudioSession.AudioSession (AudioSessionControl controller)
Parameters
controller The underlying session controller instance to create this audio session object for.
This object is from NAudio.
If you're writing an addon, install the 'NAudio' nuget package to be able to use this.
References VolumeControl.Audio.AudioSession.Dispose(), VolumeControl.Log.LogWriter.Error(), VolumeControl.Audio.AudioSession.GetProcess(), VolumeControl.Log.FLog.Log, VolumeControl.Audio.AudioSession.PID, and VolumeControl.Audio.AudioSession.ProcessName.
Member Function Documentation
GetProcess()
Process? VolumeControl.Audio.AudioSession.GetProcess ()
Gets the process associated with this audio session instance.
Returns
The Process instance that owns the audio session represented by this instance.
Referenced by VolumeControl.Audio.AudioSession.AudioSession().
Member Data Documentation
Icon
ImageSource? VolumeControl.Audio.AudioSession.Icon => SmallIcon ?? LargeIcon
Gets the large or small icon, depending on whether they are null or not.
Checks and returns LargeIcon first, if that is null then it checks and returns SmallIcon.
If both are null, returns null.
IconPath
string VolumeControl.Audio.AudioSession.IconPath => _controller.IconPath
This is the location of this sessions icon on the system and may or may not actually be set.
Do not rely on this being available, many third-party programs do not provide it!
This can point to nothing, one icon in a DLL package, an executable, or all sorts of other formats.
Do not use this for retrieving icon images directly, instead use SmallIcon/LargeIcon.
You can also use Icon directly if you don't care about the icon size.
int
VolumeControl.Audio.AudioSession.int static
Parses the given process identifier string into a PID and ProcessName.
Parameters
identifier A process identifier, PID, or ProcessName to split.
Returns
Returns a tuple where the first item is the PID and the second is the ProcessName.
Exceptions
FormatException Thrown when there is a colon in the string, but the characters before it are invalid as an integral.
LargeIcon
ImageSource? VolumeControl.Audio.AudioSession.LargeIcon => (_icons # this.GetIcons())?.Item2
The large icon located at the IconPath, or null if no icon was found.
Note that the icon properties all use internal caching; you don't need to worry about using these properties repeatedly for fear of performance loss, as the only time the icons are actually retrieved is the first time any of the icon properties are called.
SmallIcon
ImageSource? VolumeControl.Audio.AudioSession.SmallIcon => (_icons # this.GetIcons())?.Item1
The small icon located at the IconPath, or null if no icon was found.
Note that the icon properties all use internal caching; you don't need to worry about using these properties repeatedly for fear of performance loss, as the only time the icons are actually retrieved is the first time any of the icon properties are called.
State
AudioSessionState VolumeControl.Audio.AudioSession.State => _controller.State
Gets the current state of the audio session.
See AudioSessionState.
This object is from NAudio.
If you're writing an addon, install the 'NAudio' nuget package to be able to use this.
VolumeController
SimpleAudioVolume VolumeControl.Audio.AudioSession.VolumeController => _controller.SimpleAudioVolume
Gets the SimpleAudioVolume object from the underlying AudioSessionControl type.
This object is from NAudio.
If you're writing an addon, install the 'NAudio' nuget package to be able to use this.
Property Documentation
IsRunning
bool VolumeControl.Audio.AudioSession.IsRunning get
Checks if the process that owns this session is still running.
Returns
True when the process is still running, otherwise false.
Event Documentation
PropertyChanged
PropertyChangedEventHandler? VolumeControl.Audio.AudioSession.PropertyChanged
Triggered after one of this instance's properties have been set.
PropertyChanging
PropertyChangingEventHandler? VolumeControl.Audio.AudioSession.PropertyChanging
Triggered before one of this instance's properties is being set.
The documentation for this class was generated from the following file:
/home/runner/work/volume-control/volume-control/VolumeControl.Audio/AudioSession.cs