Volume Control: VolumeControl.Core.Input.Actions.HotkeyActionInstance Class Reference
VolumeControl.Core.Input.Actions.HotkeyActionInstance Class Reference
An instance of a hotkey action.
Public Member Functions
void Invoke (object? sender, HotkeyPressedEventArgs e)
Invokes the method specified by the HotkeyActionDefinition
void Invoke (object? sender)
Invokes the method specified by the HotkeyActionDefinition with a new HotkeyPressedEventArgs instance.
Properties
HotkeyActionDefinition HotkeyActionDefinition [get]
Gets the HotkeyActionDefinition that defines this hotkey action.
string Name [get]
string? Description [get]
string? GroupName [get]
Brush? GroupBrush [get]
string Identifier [get]
IActionSettingInstance[] ActionSettings [get]
Gets the action setting instances for this hotkey action.
Detailed Description
An instance of a hotkey action.
Member Function Documentation
Invoke() [1/2]
void VolumeControl.Core.Input.Actions.HotkeyActionInstance.Invoke (object? sender)
Invokes the method specified by the HotkeyActionDefinition with a new HotkeyPressedEventArgs instance.
Parameters
sender The object instance to use as the sender of the event.
Invoke() [2/2]
void VolumeControl.Core.Input.Actions.HotkeyActionInstance.Invoke (object? sender, HotkeyPressedEventArgs e)
Invokes the method specified by the HotkeyActionDefinition
Parameters
sender The object instance to use as the sender of the event.
e The event arguments to use for the event.
References VolumeControl.Log.AsyncLogWriter.Error(), VolumeControl.Log.AsyncLogWriter.FilterEventType(), VolumeControl.Core.Input.Actions.HotkeyActionDefinition.Invoke_Unsafe(), VolumeControl.Log.FLog.Log, and VolumeControl.Log.AsyncLogWriter.Trace().
Property Documentation
ActionSettings
IActionSettingInstance [] VolumeControl.Core.Input.Actions.HotkeyActionInstance.ActionSettings get
Gets the action setting instances for this hotkey action.
Referenced by VolumeControl.Core.Input.Json.JsonHotkey.JsonHotkey().
HotkeyActionDefinition
HotkeyActionDefinition VolumeControl.Core.Input.Actions.HotkeyActionInstance.HotkeyActionDefinition get
Gets the HotkeyActionDefinition that defines this hotkey action.
The documentation for this class was generated from the following file:
/home/runner/work/volume-control/volume-control/VolumeControl.Core/Input/Actions/HotkeyActionInstance.cs