Volume Control: VolumeControl.Log.LogWriter Class Reference
VolumeControl.Log.LogWriter Class Reference
Basic log writer object.
Classes
struct ConditionalMessage
Wrapper object for the Conditional(ConditionalMessage[]) method.
Public Member Functions
LogWriter (IEndpoint endpoint, EventType eventTypeFilter)
bool FilterEventType (EventType eventType)
Determines whether the given EventType should be written to the Endpoint or not.
ITimestamp MakeTimestamp (EventType eventType)
Gets a timestamp in the correct format for this log writer instance.
void Write (object text)
Writes some text to the log file.
void WriteLine (object? line=null)
Writes a line to the log file.
void WriteWithTimestamp (string ts, params object?[] lines)
Writes a log message with a given timestamp.
void WriteWithTimestamp (ITimestamp ts, params object?[] lines)
void Conditional (params ConditionalMessage[] messages)
Conditional log message, allows you to write different messages depending on the current log filter level.
void WriteEvent (EventType eventType, IEnumerable lines)
Writes a log message with a timestamp and log level header.
void WriteEvent ((EventType, IEnumerable) pair)
Writes a log message with a timestamp and log level header.
void WriteEvent (EventType eventType, object?[] lines)
Writes a log message with a timestamp and log level header.
void Debug (params object?[] lines)
Write a formatted EventType.DEBUG message to the log endpoint.
void Info (params object?[] lines)
Write a formatted EventType.INFO message to the log endpoint.
void Warning (params object?[] lines)
Write a formatted EventType.WARN message to the log endpoint.
void Error (params object?[] lines)
Write a formatted EventType.ERROR message to the log endpoint.
void Fatal (params object?[] lines)
Write a formatted EventType.FATAL message to the log endpoint.
void WriteException (EventType ev, Exception exception, object? message=null)
void DebugException (Exception exception, object? message=null)
Write a formatted EventType.DEBUG exception message to the log endpoint.
void InfoException (Exception exception, object? message=null)
Write a formatted EventType.INFO exception message to the log endpoint.
void WarningException (Exception exception, object? message=null)
Write a formatted EventType.WARN exception message to the log endpoint.
void ErrorException (Exception exception, object? message=null)
Write a formatted EventType.ERROR exception message to the log endpoint.
void FatalException (Exception exception, object? message=null)
Write a formatted EventType.FATAL exception message to the log endpoint.
void Append (params object?[] lines)
Appends the given lines to the log with a blank timestamp.
void Followup (params object?[] lines)
Write a formatted followup message without a timestamp or event type to the log endpoint.
void FollowupIf (EventType eventType, params object?[] lines)
Write a formatted followup message without a timestamp or event type to the log endpoint.
void FollowupIf (Predicate< EventType > predicate, params object?[] lines)
Write a formatted followup message without a timestamp or event type to the log endpoint.
void Dispose ()
Static Public Member Functions
static string MakeBlankTimestamp ()
Gets a blank timestamp to use as indentation.
static string FormatExceptionMessage (Exception ex, string? linePrefix=null, string lineSuffix="\n", string tabString=" ")
Creates a formatted string representation of the Exception ex .
static string GetTrace ([CallerMemberName] string callerMemberName="", [CallerFilePath] string callerFilePath="", [CallerLineNumber] int callerLineNumber=-1)
Creates a trace message for the calling method using the CallerMemberNameAttribute, CallerFilePathAttribute, & CallerLineNumberAttribute attributes.
Protected Member Functions
virtual void Dispose (bool disposing)
Properties
IEndpoint Endpoint [get, set]
Gets or sets the log endpoint object used for output.
EventType EventTypeFilter [get, set]
Gets or sets the bitfield filter for event types.
EventType LastEventType [get]
Gets the last type of event to be printed to the log.
Properties inherited from VolumeControl.Log.Interfaces.ILogWriter
IEndpoint Endpoint [get, set]
Gets or sets the endpoint for data written to the log.
Detailed Description
Basic log writer object.
This does all of the heavy-lifting (string manipulation) for the Log namespace.
Constructor & Destructor Documentation
LogWriter()
VolumeControl.Log.LogWriter.LogWriter (IEndpoint endpoint, EventType eventTypeFilter)
Parameters
endpoint An endpoint to use.
eventTypeFilter An event type filter to use. This may be a combination of bitfield flags.
Member Function Documentation
Append()
void VolumeControl.Log.LogWriter.Append (params object?[] lines)
Appends the given lines to the log with a blank timestamp.
This is intended for writing quick follow-up messages that appear as if they were part of a previously written message.
This function is unpredictable in multi-threaded environments.
Parameters
lines Any number of writable objects. Each element appears on a separate line.
References VolumeControl.Log.Endpoints.IEndpoint.Enabled, VolumeControl.Log.LogWriter.Endpoint, VolumeControl.Log.LogWriter.MakeBlankTimestamp(), and VolumeControl.Log.LogWriter.WriteWithTimestamp().
Referenced by VolumeControl.Log.LogWriter.FollowupIf().
Conditional()
void VolumeControl.Log.LogWriter.Conditional (params ConditionalMessage[] messages)
Conditional log message, allows you to write different messages depending on the current log filter level.
Parameters
messages EventType-IEnumerable pairs. Only the message assoicated with the first pair whose event type is considered valid by FilterEventType(EventType) is printed.
If none of the given event types are allowed, nothing happens.
References VolumeControl.Log.LogWriter.FilterEventType(), and VolumeControl.Log.LogWriter.WriteEvent().
Debug()
void VolumeControl.Log.LogWriter.Debug (params object?[] lines)
Write a formatted EventType.DEBUG message to the log endpoint.
Parameters
lines Any number of objects, each written on a new line.
Referenced by VolumeControl.Hotkeys.HotkeyManager.AddHook(), VolumeControl.Core.Helpers.VCSettingsContainer.NotifyPropertyChanged(), VolumeControl.Hotkeys.HotkeyManager.RemoveHook(), and VolumeControl.Hotkeys.HotkeyManager.SaveHotkeys().
DebugException()
void VolumeControl.Log.LogWriter.DebugException (Exception exception, object? message = null)
Write a formatted EventType.DEBUG exception message to the log endpoint.
Parameters
exception The exception that was thrown.
message An optional header message to use instead of the exception's message. (The exception message is still shown.)
Error()
void VolumeControl.Log.LogWriter.Error (params object?[] lines)
Write a formatted EventType.ERROR message to the log endpoint.
Parameters
lines Any number of objects, each written on a new line.
Referenced by VolumeControl.Audio.AudioSession.AudioSession(), and VolumeControl.Audio.AudioSession.GetProcess().
ErrorException()
void VolumeControl.Log.LogWriter.ErrorException (Exception exception, object? message = null)
Write a formatted EventType.ERROR exception message to the log endpoint.
Parameters
exception The exception that was thrown.
message An optional header message to use instead of the exception's message. (The exception message is still shown.)
Fatal()
void VolumeControl.Log.LogWriter.Fatal (params object?[] lines)
Write a formatted EventType.FATAL message to the log endpoint.
Parameters
lines Any number of objects, each written on a new line.
FatalException()
void VolumeControl.Log.LogWriter.FatalException (Exception exception, object? message = null)
Write a formatted EventType.FATAL exception message to the log endpoint.
Parameters
exception The exception that was thrown.
message An optional header message to use instead of the exception's message. (The exception message is still shown.)
Followup()
void VolumeControl.Log.LogWriter.Followup (params object?[] lines)
Write a formatted followup message without a timestamp or event type to the log endpoint.
This is intended for writing quick follow-up messages that appear as if they were part of a previously written message.
This function is unpredictable in multi-threaded environments.
Parameters
lines Any number of writable objects. Each element appears on a separate line.
FollowupIf() [1/2]
void VolumeControl.Log.LogWriter.FollowupIf (EventType eventType, params object?[] lines)
Write a formatted followup message without a timestamp or event type to the log endpoint.
This is intended for writing quick follow-up messages that appear as if they were part of a previously written message.
This function is unpredictable in multi-threaded environments.
Parameters
eventType Message is only printed if this was the last event type to be printed.
lines Any number of writable objects. Each element appears on a separate line.
References VolumeControl.Log.LogWriter.Append(), and VolumeControl.Log.LogWriter.LastEventType.
FollowupIf() [2/2]
void VolumeControl.Log.LogWriter.FollowupIf (Predicate< EventType > predicate, params object?[] lines)
Write a formatted followup message without a timestamp or event type to the log endpoint.
This is intended for writing quick follow-up messages that appear as if they were part of a previously written message.
This function is unpredictable in multi-threaded environments.
Parameters
predicate A predicate that accepts the LastEventType to use as the condition.
lines Any number of writable objects. Each element appears on a separate line.
References VolumeControl.Log.LogWriter.Append(), and VolumeControl.Log.LogWriter.LastEventType.
FormatExceptionMessage()
static string VolumeControl.Log.LogWriter.FormatExceptionMessage (Exception ex, string? linePrefix = null, string lineSuffix = "\n", string tabString = " ") static
Creates a formatted string representation of the Exception ex .
Parameters
ex An exception object.
linePrefix An optional string to prepend to each line.
lineSuffix An optional string to append to each line.
tabString The string to use as a single tab. This is used when indenting subsequent lines.
Returns
A string representation of ex .
GetTrace()
static string VolumeControl.Log.LogWriter.GetTrace ([CallerMemberName] string callerMemberName = "", [CallerFilePath] string callerFilePath = "", [CallerLineNumber] int callerLineNumber = -1) static
Creates a trace message for the calling method using the CallerMemberNameAttribute, CallerFilePathAttribute, & CallerLineNumberAttribute attributes.
Don't provide parameters or the attributes won't work.
Returns
A string containing the caller's name, filepath, and line number.
Info()
void VolumeControl.Log.LogWriter.Info (params object?[] lines)
Write a formatted EventType.INFO message to the log endpoint.
Parameters
lines Any number of objects, each written on a new line.
Referenced by VolumeControl.Hotkeys.HotkeyManager.AddHotkey(), and VolumeControl.Hotkeys.HotkeyManager.DelHotkey().
InfoException()
void VolumeControl.Log.LogWriter.InfoException (Exception exception, object? message = null)
Write a formatted EventType.INFO exception message to the log endpoint.
Parameters
exception The exception that was thrown.
message An optional header message to use instead of the exception's message. (The exception message is still shown.)
MakeBlankTimestamp()
static string VolumeControl.Log.LogWriter.MakeBlankTimestamp () static
Gets a blank timestamp to use as indentation.
Returns
A string of the same length as a timestamp, filled entirely with space characters.
Referenced by VolumeControl.Log.LogWriter.Append(), and VolumeControl.Log.LogWriter.WriteWithTimestamp().
Warning()
void VolumeControl.Log.LogWriter.Warning (params object?[] lines)
Write a formatted EventType.WARN message to the log endpoint.
Parameters
lines Any number of objects, each written on a new line.
WarningException()
void VolumeControl.Log.LogWriter.WarningException (Exception exception, object? message = null)
Write a formatted EventType.WARN exception message to the log endpoint.
Parameters
exception The exception that was thrown.
message An optional header message to use instead of the exception's message. (The exception message is still shown.)
Write()
void VolumeControl.Log.LogWriter.Write (object text)
Writes some text to the log file.
Using this method is very inefficient as it re-creates a StreamWriter each time; see the obsoletion warning.
Parameters
text Object to write.
WriteEvent() [1/3]
void VolumeControl.Log.LogWriter.WriteEvent ((EventType, IEnumerable) pair)
Writes a log message with a timestamp and log level header.
Parameters
pair An event type, and any enumerable type.
WriteEvent() [2/3]
void VolumeControl.Log.LogWriter.WriteEvent (EventType eventType, IEnumerable lines)
Writes a log message with a timestamp and log level header.
Parameters
eventType An event type. Do not provide combinations of event type flags!
lines Any enumerable type.
Referenced by VolumeControl.Log.LogWriter.Conditional().
WriteEvent() [3/3]
void VolumeControl.Log.LogWriter.WriteEvent (EventType eventType, object?[] lines)
Writes a log message with a timestamp and log level header.
Parameters
eventType An event type. Do not provide combinations of event type flags!
lines Any enumerable type.
References VolumeControl.Log.Endpoints.IEndpoint.Enabled, VolumeControl.Log.LogWriter.Endpoint, VolumeControl.Log.LogWriter.FilterEventType(), VolumeControl.Log.LogWriter.LastEventType, VolumeControl.Log.LogWriter.MakeTimestamp(), and VolumeControl.Log.LogWriter.WriteWithTimestamp().
WriteLine()
void VolumeControl.Log.LogWriter.WriteLine (object? line = null)
Writes a line to the log file.
Using this method is very inefficient as it re-creates a StreamWriter each time; see the obsoletion warning.
Parameters
line Object to write.
WriteWithTimestamp() [1/2]
void VolumeControl.Log.LogWriter.WriteWithTimestamp (ITimestamp ts, params object?[] lines)
Parameters
ts The timestamp object.
lines Any number of lines of any object type.
WriteWithTimestamp() [2/2]
void VolumeControl.Log.LogWriter.WriteWithTimestamp (string ts, params object?[] lines)
Writes a log message with a given timestamp.
Parameters
ts The full timestamp as a string.
lines Any number of lines of any object type.
References VolumeControl.Log.Endpoints.IEndpoint.Enabled, VolumeControl.Log.LogWriter.Endpoint, VolumeControl.Log.Endpoints.IEndpoint.GetWriter(), and VolumeControl.Log.LogWriter.MakeBlankTimestamp().
Referenced by VolumeControl.Log.LogWriter.Append(), and VolumeControl.Log.LogWriter.WriteEvent().
Property Documentation
Endpoint
IEndpoint VolumeControl.Log.LogWriter.Endpoint get set
Gets or sets the log endpoint object used for output.
Referenced by VolumeControl.Log.LogWriter.Append(), VolumeControl.Log.LogWriter.Dispose(), VolumeControl.Log.LogWriter.WriteEvent(), and VolumeControl.Log.LogWriter.WriteWithTimestamp().
EventTypeFilter
EventType VolumeControl.Log.LogWriter.EventTypeFilter get set
Gets or sets the bitfield filter for event types.
LastEventType
EventType VolumeControl.Log.LogWriter.LastEventType get
Gets the last type of event to be printed to the log.
Referenced by VolumeControl.Log.LogWriter.FollowupIf(), and VolumeControl.Log.LogWriter.WriteEvent().
The documentation for this class was generated from the following file:
/home/runner/work/volume-control/volume-control/VolumeControl.Log/LogWriter.cs