Volume Control: VolumeControl.Audio.Collections.AudioDeviceCollection Class Reference
VolumeControl.Audio.Collections.AudioDeviceCollection Class Reference
Management container object for the AudioDevice class.
Public Member Functions
AudioDeviceCollection (DataFlow flow)
Creates a new AudioDeviceCollection instance with the given NAudio.CoreAudioApi.DataFlow.
AudioDevice? FindDeviceWithMMDevice (MMDevice mmDevice)
Gets the AudioDevice associated with the given mmDevice .
AudioDevice? FindDeviceWithDeviceID (string deviceID, StringComparison sCompareType=StringComparison.Ordinal)
Gets the AudioDevice associated with the given deviceID .
void ReloadDevices (MMDeviceEnumerator deviceEnumerator)
Reloads all AudioDevices using deviceEnumerator .
void ReloadDevices ()
Reloads all AudioDevices using the default MMDeviceEnumerator.
void Dispose ()
IEnumerator< AudioDevice > GetEnumerator ()
void Add (AudioDevice item)
void Clear ()
bool Contains (AudioDevice item)
void CopyTo (AudioDevice[] array, int arrayIndex)
bool Remove (AudioDevice item)
IImmutableList< AudioDevice > AddRange (IEnumerable< AudioDevice > items)
int IndexOf (AudioDevice item, int index, int count, IEqualityComparer< AudioDevice >? equalityComparer)
IImmutableList< AudioDevice > Insert (int index, AudioDevice element)
IImmutableList< AudioDevice > InsertRange (int index, IEnumerable< AudioDevice > items)
int LastIndexOf (AudioDevice item, int index, int count, IEqualityComparer< AudioDevice >? equalityComparer)
IImmutableList< AudioDevice > Remove (AudioDevice value, IEqualityComparer< AudioDevice >? equalityComparer)
IImmutableList< AudioDevice > RemoveAll (Predicate< AudioDevice > match)
IImmutableList< AudioDevice > RemoveAt (int index)
IImmutableList< AudioDevice > RemoveRange (IEnumerable< AudioDevice > items, IEqualityComparer< AudioDevice >? equalityComparer)
IImmutableList< AudioDevice > RemoveRange (int index, int count)
IImmutableList< AudioDevice > Replace (AudioDevice oldValue, AudioDevice newValue, IEqualityComparer< AudioDevice >? equalityComparer)
IImmutableList< AudioDevice > SetItem (int index, AudioDevice value)
int IndexOf (AudioDevice item)
void CopyTo (Array array, int index)
int Add (object? value)
bool Contains (object? value)
int IndexOf (object? value)
void Insert (int index, object? value)
void Remove (object? value)
Properties
ObservableImmutableList< AudioDevice > Devices [get]
Gets the list of AudioDevice instances that are currently being tracked.
AudioDevice? DefaultDevice [get, set]
Gets the default DataFlow.Render Role.Multimedia AudioDevice.
DataFlow DataFlow [get]
Specifies the (I/O) type of AudioDevice objects that this instance manages.
int Count [get]
bool IsReadOnly [get]
bool IsSynchronized [get]
object SyncRoot [get]
bool IsFixedSize [get]
AudioDevice this[int index] [get]
NotifyCollectionChangedEventHandler? CollectionChanged
EventHandler<(MMDevice, Role)>? DefaultDeviceChanged
EventHandler< MMDevice >? DeviceAdded
EventHandler< string >? DeviceRemoved
EventHandler< MMDevice >? DeviceStateChanged
EventHandler<(string, PropertyKey)>? PropertyValueChanged
bool? AllDevicesEnabled [get, set]
Enables or disables all devices.
Events
EventHandler< bool >? DeviceEnabledChanged
Triggered when a managed device's Enabled property was changed.
EventHandler< AudioSession >? DeviceSessionCreated
Triggered when a managed device has a session added to it.
EventHandler< long >? DeviceSessionRemoved
Triggered when a managed device has a session removed from it.
PropertyChangedEventHandler? PropertyChanged
VolumeChangedEventHandler? DeviceVolumeChanged
Triggered when the volume or mute state of a device was changed.
Events inherited from VolumeControl.Audio.Interfaces.IDeviceNotificationClient
EventHandler<(MMDevice, Role)>? DefaultDeviceChanged
Triggered when a default audio device was changed.
EventHandler< MMDevice >? DeviceAdded
Triggered when a new audio device was detected.
EventHandler< string >? DeviceRemoved
Triggered when an audio device was removed.
EventHandler< MMDevice >? DeviceStateChanged
Triggered when an audio device changed states.
EventHandler<(string, PropertyKey)>? PropertyValueChanged
Triggered when an audio device's properties were changed.
Detailed Description
Management container object for the AudioDevice class.
Constructor & Destructor Documentation
AudioDeviceCollection()
VolumeControl.Audio.Collections.AudioDeviceCollection.AudioDeviceCollection (DataFlow flow)
Creates a new AudioDeviceCollection instance with the given NAudio.CoreAudioApi.DataFlow.
Parameters
flow Specifies the (I/O) type of AudioDevice objects that this instance manages.
References VolumeControl.Audio.Collections.AudioDeviceCollection.DataFlow, VolumeControl.Audio.Collections.AudioDeviceCollection.Devices, and VolumeControl.Audio.Collections.AudioDeviceCollection.ReloadDevices().
Member Function Documentation
FindDeviceWithDeviceID()
AudioDevice? VolumeControl.Audio.Collections.AudioDeviceCollection.FindDeviceWithDeviceID (string deviceID, StringComparison sCompareType = StringComparison.Ordinal)
Gets the AudioDevice associated with the given deviceID .
Parameters
deviceID The AudioDevice.DeviceID to search for.
sCompareType The StringComparison type to use.
Returns
The AudioDevice associated with deviceID if it was found in Devices; otherwise null.
FindDeviceWithMMDevice()
AudioDevice? VolumeControl.Audio.Collections.AudioDeviceCollection.FindDeviceWithMMDevice (MMDevice mmDevice)
Gets the AudioDevice associated with the given mmDevice .
Parameters
mmDevice An NAudio MMDevice instance.
Returns
The AudioDevice associated with mmDevice if it was found in Devices; otherwise null.
Referenced by VolumeControl.Audio.Collections.AudioDeviceCollection.ReloadDevices().
ReloadDevices() [1/2]
void VolumeControl.Audio.Collections.AudioDeviceCollection.ReloadDevices ()
Reloads all AudioDevices using the default MMDeviceEnumerator.
Referenced by VolumeControl.Audio.Collections.AudioDeviceCollection.AudioDeviceCollection().
ReloadDevices() [2/2]
void VolumeControl.Audio.Collections.AudioDeviceCollection.ReloadDevices (MMDeviceEnumerator deviceEnumerator)
Reloads all AudioDevices using deviceEnumerator .
Parameters
deviceEnumerator An MMDeviceEnumerator instance to use.
References VolumeControl.Audio.Collections.AudioDeviceCollection.DefaultDevice, VolumeControl.Audio.Collections.AudioDeviceCollection.Devices, and VolumeControl.Audio.Collections.AudioDeviceCollection.FindDeviceWithMMDevice().
Referenced by VolumeControl.Audio.AudioAPI.ForceReloadAudioDevices().
Property Documentation
AllDevicesEnabled
bool? VolumeControl.Audio.Collections.AudioDeviceCollection.AllDevicesEnabled get set
Enables or disables all devices.
Returns
true when all devices are enabled, false when all devices are disabled; otherwise null.
DataFlow
DataFlow VolumeControl.Audio.Collections.AudioDeviceCollection.DataFlow get
Specifies the (I/O) type of AudioDevice objects that this instance manages.
Referenced by VolumeControl.Audio.Collections.AudioDeviceCollection.AudioDeviceCollection().
DefaultDevice
AudioDevice? VolumeControl.Audio.Collections.AudioDeviceCollection.DefaultDevice get set
Gets the default DataFlow.Render Role.Multimedia AudioDevice.
Referenced by VolumeControl.Audio.Collections.AudioDeviceCollection.ReloadDevices().
Devices
ObservableImmutableList<AudioDevice> VolumeControl.Audio.Collections.AudioDeviceCollection.Devices get
Gets the list of AudioDevice instances that are currently being tracked.
Referenced by VolumeControl.Audio.Collections.AudioDeviceCollection.AudioDeviceCollection(), VolumeControl.Audio.Collections.AudioDeviceCollection.Dispose(), and VolumeControl.Audio.Collections.AudioDeviceCollection.ReloadDevices().
Event Documentation
DeviceEnabledChanged
EventHandler<bool>? VolumeControl.Audio.Collections.AudioDeviceCollection.DeviceEnabledChanged
Triggered when a managed device's Enabled property was changed.
DeviceSessionCreated
EventHandler<AudioSession>? VolumeControl.Audio.Collections.AudioDeviceCollection.DeviceSessionCreated
Triggered when a managed device has a session added to it.
DeviceSessionRemoved
EventHandler<long>? VolumeControl.Audio.Collections.AudioDeviceCollection.DeviceSessionRemoved
Triggered when a managed device has a session removed from it.
DeviceVolumeChanged
VolumeChangedEventHandler? VolumeControl.Audio.Collections.AudioDeviceCollection.DeviceVolumeChanged
Triggered when the volume or mute state of a device was changed.
The documentation for this class was generated from the following file:
/home/runner/work/volume-control/volume-control/VolumeControl.Audio/Collections/AudioDeviceCollection.cs