Volume Control: VolumeControl.Log.AsyncLogWriter Class Reference
VolumeControl.Log.AsyncLogWriter Class Reference
Asynchonously writes messages to the log endpoint.
Public Member Functions
AsyncLogWriter (IEndpointWriter endpoint, EventType eventTypeFilter)
Creates a new AsyncLogWriter instance with the specified endpoint and eventTypeFilter .
bool FilterEventType (EventType eventType)
Checks if messages with the specified eventType are shown in the log.
void ResetEndpoint ()
Resets the endpoint to its default state by calling IEndpointWriter.Reset.
void ResetEndpoint (string firstLine)
Resets the endpoint to its default state by calling IEndpointWriter.Reset, and writes the specified firstLine .
void LogMessage (LogMessage logMessage)
Writes the specified logMessage to the log.
void Trace (params object?[] lines)
Queues writing a EventType.TRACE message with the specified lines .
void Debug (params object?[] lines)
Queues writing a EventType.DEBUG message with the specified lines .
void Info (params object?[] lines)
Queues writing a EventType.INFO message with the specified lines .
void Warning (params object?[] lines)
Queues writing a EventType.WARN message with the specified lines .
void Error (params object?[] lines)
Queues writing a EventType.ERROR message with the specified lines .
void Fatal (params object?[] lines)
Queues writing a EventType.FATAL message with the specified lines .
void Critical (params object?[] lines)
Queues writing a EventType.CRITICAL message with the specified lines .
void Blank (params object?[] lines)
Queues writing a EventType.NONE message with the specified lines .
void DisableAsyncNoFlush ()
Sets the IsAsyncEnabled property to false without flushing the queue.
new void Dispose ()
Public Member Functions inherited from VolumeControl.Log.Helpers.ThreadedActionQueue
void Flush ()
Blocks the caller until the background thread has finished processing the queue.
bool Flush (int timeoutMs)
Blocks the caller until the background thread has finished processing the queue, or until the specified timeout has elapsed.
bool Flush (int timeoutMs, bool exitContext)
Blocks the caller until the background thread has finished processing the queue, or until the specified timeout has elapsed.
void Dispose ()
Terminates the background thread. Does not flush the queue.
Static Public Attributes
const string DateTimeFormatString = "HH:mm:ss:fff"
The string that defines the format of timestamps.
static readonly int TimestampLength
Length of the timestamp segment of the line header.
static readonly int EventTypeLength
Length of the event type segment of the line header.
static readonly string BlankLineHeader
A blank string with the same length as a line header.
const EventType AlwaysVisibleEventTypes = EventType.FATAL | EventType.CRITICAL
Event types that are always visible. EventType.NONE is implicitly included.
Properties
bool EndpointEnabled [get, set]
Gets or sets whether the endpoint is enabled or not.
EventType EventTypeFilter [get, set]
Gets or sets the event type filter that determines which message types are visible for this log writer instance.
bool IsAsyncEnabled [get, set]
Gets or sets whether log messages are added to the queue to be written asynchronously, or written synchronously.
Events
PropertyChangedEventHandler? PropertyChanged
Additional Inherited Members
Protected Member Functions inherited from VolumeControl.Log.Helpers.ThreadedActionQueue
ThreadedActionQueue ()
Instantiates a new ThreadedActionQueue instance.
void Enqueue (Action action)
Adds the specified action to the queue.
Detailed Description
Asynchonously writes messages to the log endpoint.
Constructor & Destructor Documentation
AsyncLogWriter()
VolumeControl.Log.AsyncLogWriter.AsyncLogWriter (IEndpointWriter endpoint, EventType eventTypeFilter)
Creates a new AsyncLogWriter instance with the specified endpoint and eventTypeFilter .
Parameters
endpoint A log endpoint instance.
eventTypeFilter The default event type filter.
Member Function Documentation
Blank()
void VolumeControl.Log.AsyncLogWriter.Blank (params object?[] lines)
Queues writing a EventType.NONE message with the specified lines .
This produces a message with no event type header, but a timestamp is still shown.
Parameters
lines Any number of objects. Each object will be written on a new line. null objects and blank strings are skipped.
Implements VolumeControl.Log.Interfaces.ILogWriter.
Critical()
void VolumeControl.Log.AsyncLogWriter.Critical (params object?[] lines)
Queues writing a EventType.CRITICAL message with the specified lines .
Parameters
lines Any number of objects. Each object will be written on a new line. null objects and blank strings are skipped.
Implements VolumeControl.Log.Interfaces.ILogWriter.
Debug()
void VolumeControl.Log.AsyncLogWriter.Debug (params object?[] lines)
Queues writing a EventType.DEBUG message with the specified lines .
Parameters
lines Any number of objects. Each object will be written on a new line. null objects and blank strings are skipped.
Implements VolumeControl.Log.Interfaces.ILogWriter.
Referenced by VolumeControl.Core.Input.HotkeyActionAddonLoader.LoadActions().
DisableAsyncNoFlush()
void VolumeControl.Log.AsyncLogWriter.DisableAsyncNoFlush ()
Sets the IsAsyncEnabled property to false without flushing the queue.
Queued messages will still be written, but any further messages will be written synchronously.
References VolumeControl.Log.AsyncLogWriter.IsAsyncEnabled.
Error()
void VolumeControl.Log.AsyncLogWriter.Error (params object?[] lines)
Queues writing a EventType.ERROR message with the specified lines .
Parameters
lines Any number of objects. Each object will be written on a new line. null objects and blank strings are skipped.
Implements VolumeControl.Log.Interfaces.ILogWriter.
Referenced by VolumeControl.SDK.Internal.Initializer.Initialize(), and VolumeControl.Core.Input.Actions.HotkeyActionInstance.Invoke().
Fatal()
void VolumeControl.Log.AsyncLogWriter.Fatal (params object?[] lines)
Queues writing a EventType.FATAL message with the specified lines .
Parameters
lines Any number of objects. Each object will be written on a new line. null objects and blank strings are skipped.
Implements VolumeControl.Log.Interfaces.ILogWriter.
FilterEventType()
bool VolumeControl.Log.AsyncLogWriter.FilterEventType (EventType eventType)
Checks if messages with the specified eventType are shown in the log.
Parameters
eventType An EventType to check.
Returns
true when the eventType is shown; otherwise false.
Implements VolumeControl.Log.Interfaces.ILogWriter.
References VolumeControl.Log.AsyncLogWriter.AlwaysVisibleEventTypes, and VolumeControl.Log.AsyncLogWriter.EventTypeFilter.
Referenced by VolumeControl.CoreAudio.AudioDevice.Dispose(), VolumeControl.CoreAudio.AudioSession.Dispose(), VolumeControl.Core.Input.Actions.HotkeyActionInstance.Invoke(), and VolumeControl.Core.Input.HotkeyActionAddonLoader.LoadActions().
Info()
void VolumeControl.Log.AsyncLogWriter.Info (params object?[] lines)
Queues writing a EventType.INFO message with the specified lines .
Parameters
lines Any number of objects. Each object will be written on a new line. null objects and blank strings are skipped.
Implements VolumeControl.Log.Interfaces.ILogWriter.
LogMessage()
void VolumeControl.Log.AsyncLogWriter.LogMessage (LogMessage logMessage)
Writes the specified logMessage to the log.
When IsAsyncEnabled is true, the message is written asynchronously; otherwise, the message is written synchronously and the caller will be blocked until the message has been written.
Parameters
logMessage The message to write to the log.
Implements VolumeControl.Log.Interfaces.ILogWriter.
References VolumeControl.Log.Helpers.ThreadedActionQueue.Enqueue(), and VolumeControl.Log.AsyncLogWriter.IsAsyncEnabled.
ResetEndpoint() [1/2]
void VolumeControl.Log.AsyncLogWriter.ResetEndpoint ()
Resets the endpoint to its default state by calling IEndpointWriter.Reset.
Referenced by VolumeControl.Log.FLog.Initialize().
ResetEndpoint() [2/2]
void VolumeControl.Log.AsyncLogWriter.ResetEndpoint (string firstLine)
Resets the endpoint to its default state by calling IEndpointWriter.Reset, and writes the specified firstLine .
Parameters
firstLine The first line to (synchronously) write to the log.
Trace()
void VolumeControl.Log.AsyncLogWriter.Trace (params object?[] lines)
Queues writing a EventType.TRACE message with the specified lines .
Parameters
lines Any number of objects. Each object will be written on a new line. null objects and blank strings are skipped.
Implements VolumeControl.Log.Interfaces.ILogWriter.
Referenced by VolumeControl.CoreAudio.AudioDevice.Dispose(), VolumeControl.CoreAudio.AudioSession.Dispose(), VolumeControl.Core.Input.Actions.HotkeyActionInstance.Invoke(), and VolumeControl.Core.Input.HotkeyActionAddonLoader.LoadActions().
Warning()
void VolumeControl.Log.AsyncLogWriter.Warning (params object?[] lines)
Queues writing a EventType.WARN message with the specified lines .
Parameters
lines Any number of objects. Each object will be written on a new line. null objects and blank strings are skipped.
Implements VolumeControl.Log.Interfaces.ILogWriter.
Member Data Documentation
AlwaysVisibleEventTypes
const EventType VolumeControl.Log.AsyncLogWriter.AlwaysVisibleEventTypes = EventType.FATAL | EventType.CRITICAL static
Event types that are always visible. EventType.NONE is implicitly included.
Referenced by VolumeControl.Log.AsyncLogWriter.FilterEventType().
BlankLineHeader
readonly string VolumeControl.Log.AsyncLogWriter.BlankLineHeader static
A blank string with the same length as a line header.
DateTimeFormatString
const string VolumeControl.Log.AsyncLogWriter.DateTimeFormatString = "HH:mm:ss:fff" static
The string that defines the format of timestamps.
EventTypeLength
readonly int VolumeControl.Log.AsyncLogWriter.EventTypeLength static
Length of the event type segment of the line header.
The event type segment comes after the timestamp.
TimestampLength
readonly int VolumeControl.Log.AsyncLogWriter.TimestampLength static
Length of the timestamp segment of the line header.
The timestamp segment comes before the event type.
Property Documentation
EndpointEnabled
bool VolumeControl.Log.AsyncLogWriter.EndpointEnabled get set
Gets or sets whether the endpoint is enabled or not.
EventTypeFilter
EventType VolumeControl.Log.AsyncLogWriter.EventTypeFilter get set
Gets or sets the event type filter that determines which message types are visible for this log writer instance.
Referenced by VolumeControl.Log.AsyncLogWriter.FilterEventType().
IsAsyncEnabled
bool VolumeControl.Log.AsyncLogWriter.IsAsyncEnabled get set
Gets or sets whether log messages are added to the queue to be written asynchronously, or written synchronously.
Returns
true when log messages are written asynchronously; otherwise false.
Referenced by VolumeControl.Log.AsyncLogWriter.DisableAsyncNoFlush(), and VolumeControl.Log.AsyncLogWriter.LogMessage().
The documentation for this class was generated from the following file:
/home/runner/work/volume-control/volume-control/VolumeControl.Log/AsyncLogWriter.cs