var class_volume_control_1_1_hotkeys_1_1_volume_step___numeric_up_down___data_template_provider =
[
    [ "ProvideDataTemplate", "class_volume_control_1_1_hotkeys_1_1_volume_step___numeric_up_down___data_template_provider.html#a4185621ce75ed2fa0d20e703de52efee", null ]
];