Volume Control: VolumeControl.Core.Config Class Reference
VolumeControl.Core.Config Class Reference
Contains the application configuration and logic to read from and write to JSON files.
Public Member Functions
Config() void ResumeAutoSave ()
Creates a new Config instance.
void PauseAutoSave ()
Pauses automatic saving of the config to disk whenever a PropertyChanged event is triggered.
Static Public Attributes
static readonly List< Key > KeyBlacklist
List of Keys that shouldn't be included as an option in the key selector.
static readonly Brush NotificationLockedBrush
The brush to use for the background of the list notification when locked.
static readonly Brush NotificationUnlockedBrush
The brush to use for the background of the list notification when unlocked.
static readonly Brush NotificationDefaultBrush = new SolidColorBrush(Color.FromRgb(0x30, 0x30, 0x30))
The default background brush used for the ListNotification
static readonly BindableHotkeyJsonWrapper[] Hotkeys_Default
Default hotkey configuration.
const double PeakMeterMinValue = 0.0
The minimum boundary shown on peak meters.
const double PeakMeterMaxValue = 1.0
The maximum boundary shown on peak meters.
Properties
string LanguageName = "English (US/CA)" [get, set]
Gets or sets the name of the current localization language.
bool CreateDefaultTranslationFiles = true [get, set]
Gets or sets whether the program should create the default translation files if they don't already exist.
ObservableImmutableList< string > CustomLocalizationDirectories = new() [get, set]
Gets or sets a list of additional directories to load localization packages from.
bool AllowMultipleDistinctInstances = false [get, set]
Gets or sets whether multiple distinct instances of Volume Control are allowed to run concurrently.
In this case, distinct means that each instance is using a different config file.
This works by creating a MD5 hash of AppConfig.ConfigurationFile.Location, and appending it to the instance's mutex ID, seperated with a colon (:).
The initialization process of acquiring a mutex lock is still performed, which will always prevent Volume Control from running alongside other instances using the same config as itself, regardless of this setting.
bool RunAtStartup = false [get, set]
Gets or sets whether the application should run when Windows starts.
Creates/deletes a registry value in HKEY_CURRENT_USER => SOFTWARE\Microsoft\Windows\CurrentVersion\Run
bool StartMinimized = false [get, set]
Gets or sets whether the window should be minimized during startup.
The window can be shown again later using the tray icon.
bool ShowInTaskbar = true [get, set]
Gets or sets whether the taskbar icon is visible when the window isn't minimized.
bool AlwaysOnTop = false [get, set]
Gets or sets whether volume control should always appear on top of other windows when the window isn't minimized.
bool DeleteHotkeyConfirmation = true [get, set]
Gets or sets whether confirmation is required to delete a hotkey.
bool ShowIcons = true [get, set]
Gets or sets whether or not device/session icons are shown in the UI.
ObservableImmutableList< string > CustomAddonDirectories = new() [get, set]
List of directories that should be checked for addons in addition to the default one.
bool AllowTransparency = true [get, set]
Gets or sets whether the main window allows transparency effects.
When true, window background transparency is allowed.
When false, window background transparency isn't allowed;
only controls within the window may use transparent background effects.
(See System.Windows.Controls.Control.Background)
bool NotificationsEnabled = true [get, set]
Gets or sets whether notifications are enabled or not.
bool NotificationsOnVolumeChange = true [get, set]
Gets or sets whether or not the list notification window appears for volume change events.
int NotificationTimeoutMs = 3000 [get, set]
The amount of time, in milliseconds, that the notification window stays visible for before disappearing.
bool NotificationTimeoutEnabled = true [get, set]
Gets or sets whether the list notification timeout is enabled, which causes the list notification to disappear after NotificationTimeoutMs milliseconds.
bool NotificationMoveRequiresAlt = true [get, set]
Gets or sets whether the notification can be dragged without holding down the ALT key.
Point? NotificationPosition [get, set]
Gets or sets the location of the notification window
bool NotificationSavePos = true [get, set]
Gets or sets whether NotificationPosition is used or not.
ScreenCorner NotificationPositionOriginCorner = ScreenCorner.BottomLeft [get, set]
Gets or sets whether controls from Interfaces.IListDisplayable.DisplayControls are shown or not.
bool NotificationDoFadeIn = true [get, set]
Gets or sets whether the notification window slowly fades in instead of appearing instantly.
Duration NotificationFadeInDuration = new(TimeSpan.FromMilliseconds(300)) [get, set]
Gets or sets the duration of the notification fade-in animation.
bool NotificationDoFadeOut = true [get, set]
Gets or sets whether the notification window slowly fades out instead of disappearing instantly.
Duration NotificationFadeOutDuration = new(TimeSpan.FromMilliseconds(500)) [get, set]
Gets or sets the duration of the notification fade-in animation.
string NotificationDisplayTarget = "Audio Sessions" [get, set]
Gets or sets the name of the currently-selected list notification display target.
bool CheckForUpdates = true [get, set]
Gets or sets whether the program should check for updates on startup.
bool ShowUpdatePrompt = true [get, set]
Gets or sets whether a message box prompt is shown informing the user of an available update.
BindableHotkeyJsonWrapper[] Hotkeys = null! [get, set]
The current hotkey configuration, or null if the default configuration should be used instead.
TargetInfo Target = new() { ProcessIdentifier = string.Empty, SessionInstanceIdentifier = string.Empty } [get, set]
Gets or sets the last target session.
bool LockTargetSession = false [get, set]
Gets or sets whether the target session is locked.
int VolumeStepSize = 2 [get, set]
Gets or sets the amount of volume added or subtracted from the current volume level when volume change hotkeys are pressed.
ObservableImmutableList< string > EnabledDevices = new() { } [get, set]
List of enabled audio device IDs.
bool EnableDefaultDevice = true [get, set]
Whether the default audio device should be enabled or not, regardless of the device IDs in EnabledDevices.
int PeakMeterUpdateIntervalMs = 100 [get, set]
Gets or sets the interval (in milliseconds) between updating the audio peak meters.
bool ShowPeakMeters = true [get, set]
Gets or sets whether or not peak meters are shown in the mixer.
bool EnableDeviceControl = false [get, set]
Gets or sets whether volume & mute controls are visible in the Audio Devices list.
bool EnableLogging = true [get, set]
Gets or sets whether the log is enabled or not.
See Log.SettingsInterface.EnableLogging
string LogPath = "VolumeControl.log" [get, set]
Gets or sets the location of the log file.
See Log.SettingsInterface.LogPath
VolumeControl.Log.Enum.EventType LogFilter = VolumeControl.Log.Enum.EventType.ALL_EXCEPT_DEBUG [get, set]
Gets or sets the Log.Enum.EventType filter used for messages.
See Log.SettingsInterface.LogFilter
bool LogClearOnInitialize = true [get, set]
Gets or sets whether the log is cleared when the program starts.
See Log.SettingsInterface.LogClearOnInitialize
string LogTimestampFormat = "HH:mm:ss:fff" [get, set]
Gets or sets the format string used for timestamps in the log.
See Log.SettingsInterface.LogTimestampFormat
bool LogEnableStackTrace = true [get, set]
bool LogEnableStackTraceLineCount = true [get, set]
SemVersion __VERSION__ = new(0) [get, set]
Gets or sets the version number identifier of the last Volume Control instance to access this config file.
Detailed Description
Contains the application configuration and logic to read from and write to JSON files.
Member Function Documentation
PauseAutoSave()
void VolumeControl.Core.Config.PauseAutoSave ()
Pauses automatic saving of the config to disk whenever a PropertyChanged event is triggered.
References VolumeControl.Log.LogWriter.Debug().
ResumeAutoSave()
Config () void VolumeControl.Core.Config.ResumeAutoSave ()
Creates a new Config instance.
The first time this is called, the AppConfig.Configuration.Default property is set to that instance; all subsequent calls do not update this property.
Resumes automatic saving of the config to disk whenever a PropertyChanged event is triggered.
Member Data Documentation
Hotkeys_Default
readonly BindableHotkeyJsonWrapper [] VolumeControl.Core.Config.Hotkeys_Default static
Default hotkey configuration.
Referenced by VolumeControl.Core.HotkeyManager.LoadHotkeys().
KeyBlacklist
readonly List<Key> VolumeControl.Core.Config.KeyBlacklist static
List of Keys that shouldn't be included as an option in the key selector.
NotificationDefaultBrush
readonly Brush VolumeControl.Core.Config.NotificationDefaultBrush = new SolidColorBrush(Color.FromRgb(0x30, 0x30, 0x30)) static
The default background brush used for the ListNotification
NotificationLockedBrush
readonly Brush VolumeControl.Core.Config.NotificationLockedBrush static
Initial value:
= new LinearGradientBrush(new GradientStopCollection()
        {
            new GradientStop(Color.FromRgb(0xA3, 0x28, 0x28), 0.2),
            new GradientStop(Color.FromRgb(0xA8, 0x14, 0x14), 0.8)
        }, new Point(0, 0), new Point(1, 1))
The brush to use for the background of the list notification when locked.
NotificationUnlockedBrush
readonly Brush VolumeControl.Core.Config.NotificationUnlockedBrush static
Initial value:
= new LinearGradientBrush(new GradientStopCollection()
        {
            new GradientStop(Color.FromRgb(0x49, 0x6D, 0x49), 0.2),
            new GradientStop(Color.FromRgb(0x40, 0x70, 0x40), 0.8)
        }, new Point(0, 0), new Point(1, 1))
The brush to use for the background of the list notification when unlocked.
PeakMeterMaxValue
const double VolumeControl.Core.Config.PeakMeterMaxValue = 1.0 static
The maximum boundary shown on peak meters.
1.0
PeakMeterMinValue
const double VolumeControl.Core.Config.PeakMeterMinValue = 0.0 static
The minimum boundary shown on peak meters.
0.0
Property Documentation
__VERSION__
SemVersion VolumeControl.Core.Config.__VERSION__ = new(0) get set
Gets or sets the version number identifier of the last Volume Control instance to access this config file.
Default: 0.0.0
AllowMultipleDistinctInstances
bool VolumeControl.Core.Config.AllowMultipleDistinctInstances = false get set
Gets or sets whether multiple distinct instances of Volume Control are allowed to run concurrently.
In this case, distinct means that each instance is using a different config file.
This works by creating a MD5 hash of AppConfig.ConfigurationFile.Location, and appending it to the instance's mutex ID, seperated with a colon (:).
The initialization process of acquiring a mutex lock is still performed, which will always prevent Volume Control from running alongside other instances using the same config as itself, regardless of this setting.
Default: false
AllowTransparency
bool VolumeControl.Core.Config.AllowTransparency = true get set
Gets or sets whether the main window allows transparency effects.
When true, window background transparency is allowed.
When false, window background transparency isn't allowed;
only controls within the window may use transparent background effects.
(See System.Windows.Controls.Control.Background)
Default: true
AlwaysOnTop
bool VolumeControl.Core.Config.AlwaysOnTop = false get set
Gets or sets whether volume control should always appear on top of other windows when the window isn't minimized.
Default: false
CheckForUpdates
bool VolumeControl.Core.Config.CheckForUpdates = true get set
Gets or sets whether the program should check for updates on startup.
CreateDefaultTranslationFiles
bool VolumeControl.Core.Config.CreateDefaultTranslationFiles = true get set
Gets or sets whether the program should create the default translation files if they don't already exist.
Default: true
CustomAddonDirectories
ObservableImmutableList<string> VolumeControl.Core.Config.CustomAddonDirectories = new() get set
List of directories that should be checked for addons in addition to the default one.
Default: {}
CustomLocalizationDirectories
ObservableImmutableList<string> VolumeControl.Core.Config.CustomLocalizationDirectories = new() get set
Gets or sets a list of additional directories to load localization packages from.
Default: {}
DeleteHotkeyConfirmation
bool VolumeControl.Core.Config.DeleteHotkeyConfirmation = true get set
Gets or sets whether confirmation is required to delete a hotkey.
EnabledDevices
ObservableImmutableList<string> VolumeControl.Core.Config.EnabledDevices = new() { } get set
List of enabled audio device IDs.
Referenced by VolumeControl.Audio.AudioAPI.SaveEnabledDevices().
EnableDefaultDevice
bool VolumeControl.Core.Config.EnableDefaultDevice = true get set
Whether the default audio device should be enabled or not, regardless of the device IDs in EnabledDevices.
EnableDeviceControl
bool VolumeControl.Core.Config.EnableDeviceControl = false get set
Gets or sets whether volume & mute controls are visible in the Audio Devices list.
Default: false
EnableLogging
bool VolumeControl.Core.Config.EnableLogging = true get set
Gets or sets whether the log is enabled or not.
See Log.SettingsInterface.EnableLogging
Default: true
Hotkeys
BindableHotkeyJsonWrapper [] VolumeControl.Core.Config.Hotkeys = null! get set
The current hotkey configuration, or null if the default configuration should be used instead.
Referenced by VolumeControl.Core.HotkeyManager.LoadHotkeys(), VolumeControl.Core.HotkeyManager.ResetHotkeys(), and VolumeControl.Core.HotkeyManager.SaveHotkeys().
LanguageName
string VolumeControl.Core.Config.LanguageName = "English (US/CA)" get set
Gets or sets the name of the current localization language.
Default: "English (US/CA)"
LockTargetSession
bool VolumeControl.Core.Config.LockTargetSession = false get set
Gets or sets whether the target session is locked.
LogClearOnInitialize
bool VolumeControl.Core.Config.LogClearOnInitialize = true get set
Gets or sets whether the log is cleared when the program starts.
See Log.SettingsInterface.LogClearOnInitialize
Default: true
LogEnableStackTrace
bool VolumeControl.Core.Config.LogEnableStackTrace = true get set
See Log.SettingsInterface.LogEnableStackTrace
Default: true
LogEnableStackTraceLineCount
bool VolumeControl.Core.Config.LogEnableStackTraceLineCount = true get set
See Log.SettingsInterface.LogEnableStackTraceLineCount
Default: true
LogFilter
VolumeControl.Log.Enum.EventType VolumeControl.Core.Config.LogFilter = VolumeControl.Log.Enum.EventType.ALL_EXCEPT_DEBUG get set
Gets or sets the Log.Enum.EventType filter used for messages.
See Log.SettingsInterface.LogFilter
Default: Log.Enum.EventType.ALL_EXCEPT_DEBUG
LogPath
string VolumeControl.Core.Config.LogPath = "VolumeControl.log" get set
Gets or sets the location of the log file.
See Log.SettingsInterface.LogPath
Default: "VolumeControl.log"
LogTimestampFormat
string VolumeControl.Core.Config.LogTimestampFormat = "HH:mm:ss:fff" get set
Gets or sets the format string used for timestamps in the log.
See Log.SettingsInterface.LogTimestampFormat
Default: "HH:mm:ss:fff"
NotificationDisplayTarget
string VolumeControl.Core.Config.NotificationDisplayTarget = "Audio Sessions" get set
Gets or sets the name of the currently-selected list notification display target.
NotificationDoFadeIn
bool VolumeControl.Core.Config.NotificationDoFadeIn = true get set
Gets or sets whether the notification window slowly fades in instead of appearing instantly.
NotificationDoFadeOut
bool VolumeControl.Core.Config.NotificationDoFadeOut = true get set
Gets or sets whether the notification window slowly fades out instead of disappearing instantly.
NotificationFadeInDuration
Duration VolumeControl.Core.Config.NotificationFadeInDuration = new(TimeSpan.FromMilliseconds(300)) get set
Gets or sets the duration of the notification fade-in animation.
NotificationFadeOutDuration
Duration VolumeControl.Core.Config.NotificationFadeOutDuration = new(TimeSpan.FromMilliseconds(500)) get set
Gets or sets the duration of the notification fade-in animation.
NotificationMoveRequiresAlt
bool VolumeControl.Core.Config.NotificationMoveRequiresAlt = true get set
Gets or sets whether the notification can be dragged without holding down the ALT key.
NotificationPosition
Point? VolumeControl.Core.Config.NotificationPosition get set
Gets or sets the location of the notification window
NotificationPositionOriginCorner
ScreenCorner VolumeControl.Core.Config.NotificationPositionOriginCorner = ScreenCorner.BottomLeft get set
Gets or sets whether controls from Interfaces.IListDisplayable.DisplayControls are shown or not.
Gets or sets the corner from which ListNotification size transform operations are rooted.
NotificationSavePos
bool VolumeControl.Core.Config.NotificationSavePos = true get set
Gets or sets whether NotificationPosition is used or not.
NotificationsEnabled
bool VolumeControl.Core.Config.NotificationsEnabled = true get set
Gets or sets whether notifications are enabled or not.
NotificationsOnVolumeChange
bool VolumeControl.Core.Config.NotificationsOnVolumeChange = true get set
Gets or sets whether or not the list notification window appears for volume change events.
NotificationTimeoutEnabled
bool VolumeControl.Core.Config.NotificationTimeoutEnabled = true get set
Gets or sets whether the list notification timeout is enabled, which causes the list notification to disappear after NotificationTimeoutMs milliseconds.
NotificationTimeoutMs
int VolumeControl.Core.Config.NotificationTimeoutMs = 3000 get set
The amount of time, in milliseconds, that the notification window stays visible for before disappearing.
PeakMeterUpdateIntervalMs
int VolumeControl.Core.Config.PeakMeterUpdateIntervalMs = 100 get set
Gets or sets the interval (in milliseconds) between updating the audio peak meters.
Default: 500ms
RunAtStartup
bool VolumeControl.Core.Config.RunAtStartup = false get set
Gets or sets whether the application should run when Windows starts.
Creates/deletes a registry value in HKEY_CURRENT_USER => SOFTWARE\Microsoft\Windows\CurrentVersion\Run
Default: false
ShowIcons
bool VolumeControl.Core.Config.ShowIcons = true get set
Gets or sets whether or not device/session icons are shown in the UI.
Default: true
ShowInTaskbar
bool VolumeControl.Core.Config.ShowInTaskbar = true get set
Gets or sets whether the taskbar icon is visible when the window isn't minimized.
Default: true
ShowPeakMeters
bool VolumeControl.Core.Config.ShowPeakMeters = true get set
Gets or sets whether or not peak meters are shown in the mixer.
Default: true
ShowUpdatePrompt
bool VolumeControl.Core.Config.ShowUpdatePrompt = true get set
Gets or sets whether a message box prompt is shown informing the user of an available update.
When this is disabled, updates are notified through the caption bar.
StartMinimized
bool VolumeControl.Core.Config.StartMinimized = false get set
Gets or sets whether the window should be minimized during startup.
The window can be shown again later using the tray icon.
Default: false
Target
TargetInfo VolumeControl.Core.Config.Target = new() { ProcessIdentifier = string.Empty, SessionInstanceIdentifier = string.Empty } get set
Gets or sets the last target session.
Referenced by VolumeControl.Audio.AudioAPI.AudioAPI().
VolumeStepSize
int VolumeControl.Core.Config.VolumeStepSize = 2 get set
Gets or sets the amount of volume added or subtracted from the current volume level when volume change hotkeys are pressed.
The documentation for this class was generated from the following file:
/home/runner/work/volume-control/volume-control/VolumeControl.Core/Config.cs