Volume Control: VolumeControl.Core.Input.Actions.HotkeyActionManager Class Reference
VolumeControl.Core.Input.Actions.HotkeyActionManager Class Reference
Manages a list of HotkeyActionDefinitions.
Public Member Functions
HotkeyActionManager ()
Creates a new HotkeyActionManager instance.
HotkeyActionDefinition? FindActionDefinition (string identifier, StringComparison stringComparison=StringComparison.Ordinal)
Gets the hotkey action definition with the specified identifier .
void AddActionDefinition (HotkeyActionDefinition actionDefinition)
Adds the specified actionDefinition to the manager.
void RemoveActionDefinition (HotkeyActionDefinition actionDefinition)
Removes the specified actionDefinition from the manager.
void AddActionDefinitions (params HotkeyActionDefinition[] actionDefinitions)
Adds the specified actionDefinitions to the manager.
Properties
IReadOnlyList< HotkeyActionDefinition > ActionDefinitions [get]
Gets the list of currently-loaded HotkeyActionDefinition objects.
Events
EventHandler< HotkeyActionDefinition >? AddedActionDefinition
Occurs when an action definition is added to the list for any reason.
EventHandler< HotkeyActionDefinition >? RemovedActionDefinition
Occurs when an action definition is removed from the list for any reason.
Detailed Description
Manages a list of HotkeyActionDefinitions.
Constructor & Destructor Documentation
HotkeyActionManager()
VolumeControl.Core.Input.Actions.HotkeyActionManager.HotkeyActionManager ()
Creates a new HotkeyActionManager instance.
Member Function Documentation
AddActionDefinition()
void VolumeControl.Core.Input.Actions.HotkeyActionManager.AddActionDefinition (HotkeyActionDefinition actionDefinition)
Adds the specified actionDefinition to the manager.
Parameters
actionDefinition A HotkeyActionDefinition instance to add to the list.
Exceptions
InvalidOperationException The specified actionDefinition is already in the list.
References VolumeControl.Core.Input.Actions.HotkeyActionManager.ActionDefinitions.
Referenced by VolumeControl.Core.Input.Actions.HotkeyActionManager.AddActionDefinitions().
AddActionDefinitions()
void VolumeControl.Core.Input.Actions.HotkeyActionManager.AddActionDefinitions (params HotkeyActionDefinition[] actionDefinitions)
Adds the specified actionDefinitions to the manager.
Parameters
actionDefinitions Any number of HotkeyActionDefinition instances to add to the list.
References VolumeControl.Core.Input.Actions.HotkeyActionManager.AddActionDefinition().
FindActionDefinition()
HotkeyActionDefinition? VolumeControl.Core.Input.Actions.HotkeyActionManager.FindActionDefinition (string identifier, StringComparison stringComparison = StringComparison.Ordinal)
Gets the hotkey action definition with the specified identifier .
Parameters
identifier The identifier string associated with the action definition to get.
stringComparison The comparison type to use for string comparisons.
Returns
The HotkeyActionDefinition instance with the specified identifier if found; otherwise null.
Referenced by VolumeControl.Core.Input.Json.JsonHotkey.CreateInstance< THotkey >().
RemoveActionDefinition()
void VolumeControl.Core.Input.Actions.HotkeyActionManager.RemoveActionDefinition (HotkeyActionDefinition actionDefinition)
Removes the specified actionDefinition from the manager.
Parameters
actionDefinition A HotkeyActionDefinition instance to remove from the list.
Exceptions
InvalidOperationException The specified actionDefinition is not in the list.
References VolumeControl.Core.Input.Actions.HotkeyActionManager.ActionDefinitions.
Property Documentation
ActionDefinitions
IReadOnlyList<HotkeyActionDefinition> VolumeControl.Core.Input.Actions.HotkeyActionManager.ActionDefinitions get
Gets the list of currently-loaded HotkeyActionDefinition objects.
Referenced by VolumeControl.Core.Input.Actions.HotkeyActionManager.AddActionDefinition(), and VolumeControl.Core.Input.Actions.HotkeyActionManager.RemoveActionDefinition().
Event Documentation
AddedActionDefinition
EventHandler<HotkeyActionDefinition>? VolumeControl.Core.Input.Actions.HotkeyActionManager.AddedActionDefinition
Occurs when an action definition is added to the list for any reason.
RemovedActionDefinition
EventHandler<HotkeyActionDefinition>? VolumeControl.Core.Input.Actions.HotkeyActionManager.RemovedActionDefinition
Occurs when an action definition is removed from the list for any reason.
The documentation for this class was generated from the following file:
/home/runner/work/volume-control/volume-control/VolumeControl.Core/Input/Actions/HotkeyActionManager.cs