Volume Control: VolumeControl.Audio.AudioAPI Class Reference
VolumeControl.Audio.AudioAPI Class Reference
Contains methods related to audio devices, sessions, and the underlying selection mechanics responsible for providing context to actions.
You can use this object to manipulate any audio session on the system.
Public Types
enum SessionNameFormat { SessionNameFormat.None = 0, SessionNameFormat.PID = 1, SessionNameFormat.ProcessName = 2, SessionNameFormat.ProcessIdentifier = 4 }
Bitfield flag that is used to specify which properties to include for the GetSessionNames(SessionNameFormat) method.
Public Member Functions
AudioAPI ()
void ReloadDeviceList ()
Performs a selective update on the Devices list property by removing old/disabled/unplugged entries and adding newly detected ones.
AudioDevice GetDefaultDevice ()
Gets the current default audio endpoint.
IDevice? FindDevice (Predicate< AudioDevice > predicate)
Gets a device from Devices using the given predicate function.
IDevice? FindDeviceWithID (string deviceID, StringComparison sCompareType=StringComparison.Ordinal)
Calls the FindDevice(Predicate<AudioDevice>) method with a lambda that compares the AudioDevice.DeviceID property.
void ReloadSessionList (bool reloadDevicesFirst=false)
Performs a selective update on the Sessions list property by removing old/exited entries and adding new/started entries.
ISession? FindSession (Predicate< AudioSession > predicate)
Gets a session from Sessions by applying predicate to each element and returning the first occurrence.
ISession? FindSessionWithID (int pid)
Gets a session from Sessions by searching for a session with the process id pid
ISession? FindSessionWithName (string name, StringComparison sCompareType=StringComparison.OrdinalIgnoreCase)
Gets a session from Sessions by searching for a session with the process name name
ISession? FindSessionWithIdentifier (string identifier, StringComparison sCompareType=StringComparison.OrdinalIgnoreCase)
Gets a session from Sessions by parsing identifier to determine whether to pass it to FindSessionWithID(int), FindSessionWithName(string, StringComparison), or directly comparing it to the AudioSession.ProcessIdentifier property.
List< string > GetSessionNames (SessionNameFormat format=SessionNameFormat.ProcessIdentifier|SessionNameFormat.ProcessName)
Gets a list of strings containing various properties from each element present in Sessions.
This is implemented as a faster alternative to using LINQ statements as it only loops through the list once.
int GetSessionVolume ()
Gets the current session volume of SelectedSession.
void SetSessionVolume (int volume)
Sets the current session volume of SelectedSession.
void IncrementSessionVolume (int amount)
Increments the volume of SelectedSession by amount .
Does nothing if SelectedDevice is null.
void IncrementSessionVolume ()
Increments the volume of SelectedSession by VolumeStepSize.
Does nothing if SelectedDevice is null.
void DecrementSessionVolume (int amount)
Decrements the volume of SelectedSession by amount .
Does nothing if SelectedDevice is null.
void DecrementSessionVolume ()
Decrements the volume of SelectedSession by VolumeStepSize.
Does nothing if SelectedDevice is null.
bool GetSessionMute ()
Gets whether the SelectedSession is currently muted.
void SetSessionMute (bool state)
Sets the mute state of SelectedSession.
Does nothing if SelectedDevice is null.
void ToggleSessionMute ()
Toggles the mute state of SelectedSession.
Does nothing if SelectedDevice is null.
void SelectNextSession ()
Sets SelectedSession to the session occurring after this one in Sessions.
Automatically loops back around if the selection index goes out of range.
void SelectPreviousSession ()
Sets SelectedSession to the session occurring before this one in Sessions.
Automatically loops back around if the selection index goes out of range.
bool DeselectSession ()
Sets SelectedSession to null.
Does nothing if SelectedSession is already null or if the selected session is locked.
int GetDeviceVolume ()
Gets the current endpoint volume of SelectedDevice.
void SetDeviceVolume (int volume)
Sets the current endpoint volume of SelectedDevice.
void IncrementDeviceVolume (int amount)
Increments the endpoint volume of the currently selected device.
This affects the maximum volume of all sessions using this endpoint.
void IncrementDeviceVolume ()
void DecrementDeviceVolume (int amount)
Decrements the endpoint volume of the currently selected device.
This affects the maximum volume of all sessions using this endpoint.
void DecrementDeviceVolume ()
bool GetDeviceMute ()
Gets whether the SelectedDevice is currently muted.
void SetDeviceMute (bool state)
Sets the mute state of SelectedDevice.
Does nothing if SelectedDevice is null.
void ToggleDeviceMute ()
Toggles the mute state of SelectedDevice.
Does nothing if SelectedDevice is null.
void SelectNextDevice ()
Sets SelectedDevice to the device occurring after this one in Devices.
Automatically loops back around if the selection index goes out of range.
Does nothing unless device selection is unlocked.
void SelectPreviousDevice ()
Sets SelectedDevice to the device occurring before this one in Devices.
Automatically loops back around if the selection index goes out of range.
Does nothing unless device selection is unlocked.
bool DeselectDevice ()
Sets SelectedDevice to null.
This does nothing if
Does nothing if SelectedDevice is already null, or if the selected device is locked.
bool SelectDefaultDevice ()
Sets SelectedDevice to the result of GetDefaultDevice().
Does nothing if the selected device is locked, or if the selected device is already set to the default device.
void Dispose ()
Public Attributes
AudioDevice DefaultDevice => _defaultDevice # GetDefaultDevice()
The current default audio device.
Do not store references to this object within objects whose lifetime may outlast it.
Static Public Attributes
static int ReloadIntervalMin => Settings.AutoReloadIntervalMin
The minimum allowable automatic reload interval, in milliseconds.
static int ReloadIntervalMax => Settings.AutoReloadIntervalMax
The maximum allowable automatic reload interval, in milliseconds.
Properties
bool ReloadOnInterval [get, set]
When true, automatic reloads are enabled.
int ReloadInterval [get, set]
bool ReloadOnHotkey [get, set]
When true, the 'Reload on Hotkey' feature is enabled; causing the session list to be refreshed when a relevant hotkey is pressed.
Note that this is only triggered every few seconds, as it uses an internal timer mechanism to prevent spam.
ObservableList< AudioDevice > Devices = new() [get]
An observable list of all known audio devices.
ObservableList< AudioSession > Sessions = new() [get]
An observable list of all known audio sessions.
IDevice??????? SelectedDevice [get, set]
The currently selected AudioDevice, or null if nothing is selected.
ISession????? SelectedSession [get, set]
The currently selected AudioSession, or null if nothing is selected.
bool? LockSelectedDevice [get, set]
Prevents SelectedDevice from being modified.
bool? LockSelectedSession [get, set]
Prevents SelectedSession from being modified.
string Target [get, set]
Refers to the text in the target text box on the mixer tab - that is, it is a potentially-unvalidated string representation of SelectedSession's AudioSession.ProcessIdentifier property.
bool CheckAllDevices [get, set]
When true, the session list contains sessions from all audio devices.
int VolumeStepSize [get, set]
The amount to increment or decrement volume when no direct value is provided, such as when triggering methods with hotkeys.
DeviceNotificationClient DeviceNotificationClient [get]
Events
EventHandler? DeviceListReloaded
Triggered when the device list is refreshed.
EventHandler? SessionListReloaded
Triggered when the session list is refreshed.
EventHandler? SelectedDeviceSwitched
Triggered when the selected device is changed.
EventHandler? LockSelectedDeviceChanged
Triggered when the value of the LockSelectedDevice property is changed.
EventHandler? SelectedSessionSwitched
Triggered when the selected session is changed.
EventHandler? LockSelectedSessionChanged
Triggered when the value of the LockSelectedSession property is changed.
TargetChangingEventHandler? TargetChanging
Triggered before the Target property is changed, allowing for target validation.
TargetChangedEventHandler? TargetChanged
Triggered when the Target property is changed.
VolumeEventHandler? VolumeChanged
Triggered when the volume level or mute state of SelectedDevice or SelectedSession is changed.
To differentiate between devices and sessions, see the VolumeEventArgs.Target property.
PropertyChangedEventHandler? PropertyChanged
Triggered when a member property's value is changed.
PropertyChangingEventHandler? PropertyChanging
Triggered before a member property's value is changed.
Detailed Description
Contains methods related to audio devices, sessions, and the underlying selection mechanics responsible for providing context to actions.
You can use this object to manipulate any audio session on the system.
Member Enumeration Documentation
SessionNameFormat
enum VolumeControl.Audio.AudioAPI.SessionNameFormat strong
Bitfield flag that is used to specify which properties to include for the GetSessionNames(SessionNameFormat) method.
Enumerator
None
Null
PID
Includes AudioSession.PID, as a string.
ProcessName
Includes AudioSession.ProcessName
ProcessIdentifier
Includes AudioSession.ProcessIdentifier
Member Function Documentation
DecrementDeviceVolume() [1/2]
void VolumeControl.Audio.AudioAPI.DecrementDeviceVolume ()
This calls DecrementDeviceVolume(int) using VolumeStepSize.
DecrementDeviceVolume() [2/2]
void VolumeControl.Audio.AudioAPI.DecrementDeviceVolume (int amount)
Decrements the endpoint volume of the currently selected device.
This affects the maximum volume of all sessions using this endpoint.
Parameters
amount The amount to decrease the volume by.
References VolumeControl.Audio.AudioAPI.SelectedDevice.
DecrementSessionVolume() [1/2]
void VolumeControl.Audio.AudioAPI.DecrementSessionVolume ()
Decrements the volume of SelectedSession by VolumeStepSize.
Does nothing if SelectedDevice is null.
DecrementSessionVolume() [2/2]
void VolumeControl.Audio.AudioAPI.DecrementSessionVolume (int amount)
Decrements the volume of SelectedSession by amount .
Does nothing if SelectedDevice is null.
Parameters
amount The amount to change the session's volume by.
Session volume can be any value from 0 to 100, and is automatically clamped if the final value exceeds this range.
References VolumeControl.Audio.AudioAPI.SelectedSession.
DeselectDevice()
bool VolumeControl.Audio.AudioAPI.DeselectDevice ()
Sets SelectedDevice to null.
This does nothing if
Does nothing if SelectedDevice is already null, or if the selected device is locked.
Returns
true when the selected device was set to null & the SelectedDeviceSwitched event was fired; otherwise false.
References VolumeControl.Audio.AudioAPI.LockSelectedDevice, and VolumeControl.Audio.AudioAPI.SelectedDevice.
DeselectSession()
bool VolumeControl.Audio.AudioAPI.DeselectSession ()
Sets SelectedSession to null.
Does nothing if SelectedSession is already null or if the selected session is locked.
Returns
true when SelectedSession was set to null & the SelectedSessionSwitched event was fired; otherwise false.
References VolumeControl.Audio.AudioAPI.LockSelectedSession, and VolumeControl.Audio.AudioAPI.SelectedSession.
FindDevice()
IDevice? VolumeControl.Audio.AudioAPI.FindDevice (Predicate< AudioDevice > predicate)
Gets a device from Devices using the given predicate function.
Parameters
predicate A predicate function that accepts AudioDevice types.
Returns
IDevice if successful, or null if no matching devices were found.
References VolumeControl.Audio.AudioAPI.Devices.
FindDeviceWithID()
IDevice? VolumeControl.Audio.AudioAPI.FindDeviceWithID (string deviceID, StringComparison sCompareType = StringComparison.Ordinal)
Calls the FindDevice(Predicate<AudioDevice>) method with a lambda that compares the AudioDevice.DeviceID property.
Parameters
deviceID The device id string of the target audio device.
sCompareType The string comparison type to use.
Returns
IDevice if successful, or null if no matching devices were found.
FindSession()
ISession? VolumeControl.Audio.AudioAPI.FindSession (Predicate< AudioSession > predicate)
Gets a session from Sessions by applying predicate to each element and returning the first occurrence.
Parameters
predicate A predicate function to apply to each element of Sessions that can accept AudioSession types.
Returns
ISession if a session was found, or null if predicate didn't return true for any elements.
FindSessionWithID()
ISession? VolumeControl.Audio.AudioAPI.FindSessionWithID (int pid)
Gets a session from Sessions by searching for a session with the process id pid
It is recommended to use FindSessionWithIdentifier(string, StringComparison) when searching the Sessions list.
Parameters
pid AudioSession.PID
Returns
ISession if a session was found, or null if no processes were found with pid .
FindSessionWithIdentifier()
ISession? VolumeControl.Audio.AudioAPI.FindSessionWithIdentifier (string identifier, StringComparison sCompareType = StringComparison.OrdinalIgnoreCase)
Gets a session from Sessions by parsing identifier to determine whether to pass it to FindSessionWithID(int), FindSessionWithName(string, StringComparison), or directly comparing it to the AudioSession.ProcessIdentifier property.
Parameters
identifier This can match any of the following properties:
AudioSession.PID
AudioSession.ProcessNameUses sCompareType
AudioSession.ProcessIdentifierUses sCompareType
sCompareType A StringComparison enum value to use when matching process names or full identifiers.
Returns
ISession if a session was found.
Returns null if nothing was found.
References VolumeControl.Audio.Interfaces.IProcess.PID, VolumeControl.Audio.AudioSession.PID, VolumeControl.Audio.AudioSession.ProcessIdentifier, VolumeControl.Audio.AudioSession.ProcessName, and VolumeControl.Audio.AudioAPI.Sessions.
FindSessionWithName()
ISession? VolumeControl.Audio.AudioAPI.FindSessionWithName (string name, StringComparison sCompareType = StringComparison.OrdinalIgnoreCase)
Gets a session from Sessions by searching for a session with the process name name
It is recommended to use FindSessionWithIdentifier(string, StringComparison) when searching the Sessions list.
Parameters
name AudioSession.ProcessName
sCompareType A StringComparison enum value to use when matching process names.
Returns
ISession if a session was found, or null if no processes were found named name using sCompareType string comparison.
GetDefaultDevice()
AudioDevice VolumeControl.Audio.AudioAPI.GetDefaultDevice ()
Gets the current default audio endpoint.
This method checks Devices first and only creates a new device if it wasn't found.
Returns
AudioDevice
Referenced by VolumeControl.Audio.AudioAPI.SelectDefaultDevice().
GetDeviceMute()
bool VolumeControl.Audio.AudioAPI.GetDeviceMute ()
Gets whether the SelectedDevice is currently muted.
Returns
True if SelectedDevice is not null and is muted; otherwise false.
GetDeviceVolume()
int VolumeControl.Audio.AudioAPI.GetDeviceVolume ()
Gets the current endpoint volume of SelectedDevice.
Returns
An Int32 in the range (0 - 100) if SelectedDevice is not null; otherwise (-1).
GetSessionMute()
bool VolumeControl.Audio.AudioAPI.GetSessionMute ()
Gets whether the SelectedSession is currently muted.
Returns
True if SelectedSession is not null and is muted; otherwise false.
GetSessionNames()
List<string> VolumeControl.Audio.AudioAPI.GetSessionNames (SessionNameFormat format = SessionNameFormat.ProcessIdentifier | SessionNameFormat.ProcessName)
Gets a list of strings containing various properties from each element present in Sessions.
This is implemented as a faster alternative to using LINQ statements as it only loops through the list once.
Parameters
format Bitfield flag that determines which properties to include in the list.
Returns
A list of string types containing the requested properties from each session.
References VolumeControl.Audio.AudioSession.PID, VolumeControl.Audio.AudioSession.ProcessIdentifier, VolumeControl.Audio.AudioSession.ProcessName, and VolumeControl.Audio.AudioAPI.Sessions.
GetSessionVolume()
int VolumeControl.Audio.AudioAPI.GetSessionVolume ()
Gets the current session volume of SelectedSession.
Returns
An Int32 in the range (0 - 100) if SelectedSession is not null; otherwise (-1).
IncrementDeviceVolume() [1/2]
void VolumeControl.Audio.AudioAPI.IncrementDeviceVolume ()
This calls IncrementDeviceVolume(int) using VolumeStepSize.
IncrementDeviceVolume() [2/2]
void VolumeControl.Audio.AudioAPI.IncrementDeviceVolume (int amount)
Increments the endpoint volume of the currently selected device.
This affects the maximum volume of all sessions using this endpoint.
Parameters
amount The amount to increase the volume by.
References VolumeControl.Audio.AudioAPI.SelectedDevice.
IncrementSessionVolume() [1/2]
void VolumeControl.Audio.AudioAPI.IncrementSessionVolume ()
Increments the volume of SelectedSession by VolumeStepSize.
Does nothing if SelectedDevice is null.
IncrementSessionVolume() [2/2]
void VolumeControl.Audio.AudioAPI.IncrementSessionVolume (int amount)
Increments the volume of SelectedSession by amount .
Does nothing if SelectedDevice is null.
Parameters
amount The amount to change the session's volume by.
Session volume can be any value from 0 to 100, and is automatically clamped if the final value exceeds this range.
References VolumeControl.Audio.AudioAPI.SelectedSession.
ReloadDeviceList()
void VolumeControl.Audio.AudioAPI.ReloadDeviceList ()
Performs a selective update on the Devices list property by removing old/disabled/unplugged entries and adding newly detected ones.
Referenced by VolumeControl.Audio.AudioAPI.SelectNextDevice(), and VolumeControl.Audio.AudioAPI.SelectPreviousDevice().
ReloadSessionList()
void VolumeControl.Audio.AudioAPI.ReloadSessionList (bool reloadDevicesFirst = false)
Performs a selective update on the Sessions list property by removing old/exited entries and adding new/started entries.
Parameters
reloadDevicesFirst When true, ReloadDeviceList is called before getting the updated sessions from the CoreAudio API.
Referenced by VolumeControl.Audio.AudioAPI.SelectNextSession(), and VolumeControl.Audio.AudioAPI.SelectPreviousSession().
SelectDefaultDevice()
bool VolumeControl.Audio.AudioAPI.SelectDefaultDevice ()
Sets SelectedDevice to the result of GetDefaultDevice().
Does nothing if the selected device is locked, or if the selected device is already set to the default device.
Returns
true when SelectedDevice was changed & the SelectedDeviceSwitched event was fired; otherwise false.
References VolumeControl.Audio.AudioAPI.GetDefaultDevice(), VolumeControl.Audio.AudioAPI.LockSelectedDevice, and VolumeControl.Audio.AudioAPI.SelectedDevice.
SelectNextDevice()
void VolumeControl.Audio.AudioAPI.SelectNextDevice ()
Sets SelectedDevice to the device occurring after this one in Devices.
Automatically loops back around if the selection index goes out of range.
Does nothing unless device selection is unlocked.
If SelectedDevice is set to null, the first element in Devices is selected.
References VolumeControl.Audio.AudioAPI.Devices, VolumeControl.Audio.AudioAPI.LockSelectedDevice, VolumeControl.Audio.AudioAPI.ReloadDeviceList(), VolumeControl.Audio.AudioAPI.ReloadOnHotkey, and VolumeControl.Audio.AudioAPI.SelectedDevice.
SelectNextSession()
void VolumeControl.Audio.AudioAPI.SelectNextSession ()
Sets SelectedSession to the session occurring after this one in Sessions.
Automatically loops back around if the selection index goes out of range.
If SelectedSession is set to null, the first element in Sessions is selected.
References VolumeControl.Audio.AudioAPI.LockSelectedSession, VolumeControl.Audio.AudioAPI.ReloadOnHotkey, VolumeControl.Audio.AudioAPI.ReloadSessionList(), VolumeControl.Audio.AudioAPI.SelectedSession, and VolumeControl.Audio.AudioAPI.Sessions.
SelectPreviousDevice()
void VolumeControl.Audio.AudioAPI.SelectPreviousDevice ()
Sets SelectedDevice to the device occurring before this one in Devices.
Automatically loops back around if the selection index goes out of range.
Does nothing unless device selection is unlocked.
If SelectedDevice is set to null, the last element in Devices is selected.
References VolumeControl.Audio.AudioAPI.Devices, VolumeControl.Audio.AudioAPI.LockSelectedDevice, VolumeControl.Audio.AudioAPI.ReloadDeviceList(), VolumeControl.Audio.AudioAPI.ReloadOnHotkey, and VolumeControl.Audio.AudioAPI.SelectedDevice.
SelectPreviousSession()
void VolumeControl.Audio.AudioAPI.SelectPreviousSession ()
Sets SelectedSession to the session occurring before this one in Sessions.
Automatically loops back around if the selection index goes out of range.
If SelectedSession is set to null, the last element in Sessions is selected.
References VolumeControl.Audio.AudioAPI.LockSelectedSession, VolumeControl.Audio.AudioAPI.ReloadOnHotkey, VolumeControl.Audio.AudioAPI.ReloadSessionList(), VolumeControl.Audio.AudioAPI.SelectedSession, and VolumeControl.Audio.AudioAPI.Sessions.
SetDeviceMute()
void VolumeControl.Audio.AudioAPI.SetDeviceMute (bool state)
Sets the mute state of SelectedDevice.
Does nothing if SelectedDevice is null.
Note that this affects all sessions using this device.
Parameters
state When true, the device will be muted; when false, the device will be unmuted.
References VolumeControl.Audio.AudioAPI.SelectedDevice.
SetDeviceVolume()
void VolumeControl.Audio.AudioAPI.SetDeviceVolume (int volume)
Sets the current endpoint volume of SelectedDevice.
Parameters
volume The desired endpoint volume level in the range (0 - 100)
References VolumeControl.Audio.AudioAPI.SelectedDevice.
SetSessionMute()
void VolumeControl.Audio.AudioAPI.SetSessionMute (bool state)
Sets the mute state of SelectedSession.
Does nothing if SelectedDevice is null.
Parameters
state When true, the session will be muted; when false, the session will be unmuted.
References VolumeControl.Audio.AudioAPI.SelectedSession.
SetSessionVolume()
void VolumeControl.Audio.AudioAPI.SetSessionVolume (int volume)
Sets the current session volume of SelectedSession.
Parameters
volume The desired session volume level in the range (0 - 100)
References VolumeControl.Audio.AudioAPI.SelectedSession.
ToggleDeviceMute()
void VolumeControl.Audio.AudioAPI.ToggleDeviceMute ()
Toggles the mute state of SelectedDevice.
Does nothing if SelectedDevice is null.
Note that this affects all sessions using this device.
References VolumeControl.Audio.AudioAPI.SelectedDevice.
ToggleSessionMute()
void VolumeControl.Audio.AudioAPI.ToggleSessionMute ()
Toggles the mute state of SelectedSession.
Does nothing if SelectedDevice is null.
References VolumeControl.Audio.AudioAPI.SelectedSession.
Member Data Documentation
DefaultDevice
AudioDevice VolumeControl.Audio.AudioAPI.DefaultDevice => _defaultDevice # GetDefaultDevice()
The current default audio device.
Do not store references to this object within objects whose lifetime may outlast it.
ReloadIntervalMax
int VolumeControl.Audio.AudioAPI.ReloadIntervalMax => Settings.AutoReloadIntervalMax static
The maximum allowable automatic reload interval, in milliseconds.
ReloadIntervalMin
int VolumeControl.Audio.AudioAPI.ReloadIntervalMin => Settings.AutoReloadIntervalMin static
The minimum allowable automatic reload interval, in milliseconds.
Property Documentation
CheckAllDevices
bool VolumeControl.Audio.AudioAPI.CheckAllDevices get set
When true, the session list contains sessions from all audio devices.
This changes the behaviour of ReloadSessionList so that it checks all devices instead of only the currently selected device.
DeviceNotificationClient
DeviceNotificationClient VolumeControl.Audio.AudioAPI.DeviceNotificationClient get
This forwards events directly from the core audio api.
Devices
ObservableList<AudioDevice> VolumeControl.Audio.AudioAPI.Devices = new() get
An observable list of all known audio devices.
Referenced by VolumeControl.Audio.AudioAPI.FindDevice(), VolumeControl.Audio.AudioAPI.SelectNextDevice(), and VolumeControl.Audio.AudioAPI.SelectPreviousDevice().
LockSelectedDevice
bool? VolumeControl.Audio.AudioAPI.LockSelectedDevice get set
Prevents SelectedDevice from being modified.
Referenced by VolumeControl.Audio.AudioAPI.DeselectDevice(), VolumeControl.Audio.AudioAPI.SelectDefaultDevice(), VolumeControl.Audio.AudioAPI.SelectNextDevice(), and VolumeControl.Audio.AudioAPI.SelectPreviousDevice().
LockSelectedSession
bool? VolumeControl.Audio.AudioAPI.LockSelectedSession get set
Prevents SelectedSession from being modified.
Referenced by VolumeControl.Audio.AudioAPI.DeselectSession(), VolumeControl.Audio.AudioAPI.SelectNextSession(), and VolumeControl.Audio.AudioAPI.SelectPreviousSession().
ReloadInterval
int VolumeControl.Audio.AudioAPI.ReloadInterval get set
This property automatically clamps incoming values between ReloadIntervalMin and ReloadIntervalMax
ReloadOnHotkey
bool VolumeControl.Audio.AudioAPI.ReloadOnHotkey get set
When true, the 'Reload on Hotkey' feature is enabled; causing the session list to be refreshed when a relevant hotkey is pressed.
Note that this is only triggered every few seconds, as it uses an internal timer mechanism to prevent spam.
Referenced by VolumeControl.Audio.AudioAPI.SelectNextDevice(), VolumeControl.Audio.AudioAPI.SelectNextSession(), VolumeControl.Audio.AudioAPI.SelectPreviousDevice(), and VolumeControl.Audio.AudioAPI.SelectPreviousSession().
ReloadOnInterval
bool VolumeControl.Audio.AudioAPI.ReloadOnInterval get set
When true, automatic reloads are enabled.
SelectedDevice
IDevice??????? VolumeControl.Audio.AudioAPI.SelectedDevice get set
The currently selected AudioDevice, or null if nothing is selected.
LockSelectedDevice must be false in order to change this.
Referenced by VolumeControl.Audio.AudioAPI.DecrementDeviceVolume(), VolumeControl.Audio.AudioAPI.DeselectDevice(), VolumeControl.Audio.AudioAPI.IncrementDeviceVolume(), VolumeControl.Audio.AudioAPI.SelectDefaultDevice(), VolumeControl.Audio.AudioAPI.SelectNextDevice(), VolumeControl.Audio.AudioAPI.SelectPreviousDevice(), VolumeControl.Audio.AudioAPI.SetDeviceMute(), VolumeControl.Audio.AudioAPI.SetDeviceVolume(), and VolumeControl.Audio.AudioAPI.ToggleDeviceMute().
SelectedSession
ISession????? VolumeControl.Audio.AudioAPI.SelectedSession get set
The currently selected AudioSession, or null if nothing is selected.
LockSelectedSession must be false in order to change this.
Referenced by VolumeControl.Audio.AudioAPI.DecrementSessionVolume(), VolumeControl.Audio.AudioAPI.DeselectSession(), VolumeControl.Audio.AudioAPI.IncrementSessionVolume(), VolumeControl.Audio.AudioAPI.SelectNextSession(), VolumeControl.Audio.AudioAPI.SelectPreviousSession(), VolumeControl.Audio.AudioAPI.SetSessionMute(), VolumeControl.Audio.AudioAPI.SetSessionVolume(), and VolumeControl.Audio.AudioAPI.ToggleSessionMute().
Sessions
ObservableList<AudioSession> VolumeControl.Audio.AudioAPI.Sessions = new() get
An observable list of all known audio sessions.
Referenced by VolumeControl.Audio.AudioAPI.FindSessionWithIdentifier(), VolumeControl.Audio.AudioAPI.GetSessionNames(), VolumeControl.Audio.AudioAPI.SelectNextSession(), and VolumeControl.Audio.AudioAPI.SelectPreviousSession().
Target
string VolumeControl.Audio.AudioAPI.Target get set
Refers to the text in the target text box on the mixer tab - that is, it is a potentially-unvalidated string representation of SelectedSession's AudioSession.ProcessIdentifier property.
This is automatically updated by, and automatically updates, SelectedSession.
VolumeStepSize
int VolumeControl.Audio.AudioAPI.VolumeStepSize get set
The amount to increment or decrement volume when no direct value is provided, such as when triggering methods with hotkeys.
Event Documentation
DeviceListReloaded
EventHandler? VolumeControl.Audio.AudioAPI.DeviceListReloaded
Triggered when the device list is refreshed.
LockSelectedDeviceChanged
EventHandler? VolumeControl.Audio.AudioAPI.LockSelectedDeviceChanged
Triggered when the value of the LockSelectedDevice property is changed.
LockSelectedSessionChanged
EventHandler? VolumeControl.Audio.AudioAPI.LockSelectedSessionChanged
Triggered when the value of the LockSelectedSession property is changed.
PropertyChanged
PropertyChangedEventHandler? VolumeControl.Audio.AudioAPI.PropertyChanged
Triggered when a member property's value is changed.
PropertyChanging
PropertyChangingEventHandler? VolumeControl.Audio.AudioAPI.PropertyChanging
Triggered before a member property's value is changed.
SelectedDeviceSwitched
EventHandler? VolumeControl.Audio.AudioAPI.SelectedDeviceSwitched
Triggered when the selected device is changed.
SelectedSessionSwitched
EventHandler? VolumeControl.Audio.AudioAPI.SelectedSessionSwitched
Triggered when the selected session is changed.
SessionListReloaded
EventHandler? VolumeControl.Audio.AudioAPI.SessionListReloaded
Triggered when the session list is refreshed.
TargetChanged
TargetChangedEventHandler? VolumeControl.Audio.AudioAPI.TargetChanged
Triggered when the Target property is changed.
TargetChanging
TargetChangingEventHandler? VolumeControl.Audio.AudioAPI.TargetChanging
Triggered before the Target property is changed, allowing for target validation.
Note that this is triggered before the PropertyChanging event for Target.
If this event cancels the change, the PropertyChanging event is not fired.
VolumeChanged
VolumeEventHandler? VolumeControl.Audio.AudioAPI.VolumeChanged
Triggered when the volume level or mute state of SelectedDevice or SelectedSession is changed.
To differentiate between devices and sessions, see the VolumeEventArgs.Target property.
Note that this event is only triggered by AudioAPI methods, and as a result does not trigger when the volume is changed using the UI or by any other means!
A non-exhaustive list of methods that trigger this event:
IncrementDeviceVolume(int)
DecrementDeviceVolume(int)
SetDeviceMute(bool)
ToggleDeviceMute()
IncrementSessionVolume(int)
DecrementSessionVolume(int)
SetDeviceMute(bool)
ToggleDeviceMute()
The documentation for this class was generated from the following file:
/home/runner/work/volume-control/volume-control/VolumeControl.Audio/AudioAPI.cs