Volume Control: VolumeControl.WPF.IconExtractor Class Reference
VolumeControl.WPF.IconExtractor Class Reference
A static class that provides methods for extracting icons from files, directories, or DLLs, as well as directly loading them from icon or image files.
Static Public Member Functions
static ImageSource ExtractFromHandle (IntPtr iconHandle, Int32Rect sourceRect, BitmapSizeOptions sizeOptions)
Gets an ImageSource from the specified iconHandle .
static ImageSource ExtractFromHandle (IntPtr iconHandle, Int32Rect sourceRect)
static ImageSource ExtractFromHandle (IntPtr iconHandle)
static bool TryExtractFromHandle (IntPtr iconHandle, Int32Rect sourceRect, BitmapSizeOptions sizeOptions, out ImageSource imageSource)
Attempts to get an ImageSource from the specified iconHandle .
static bool TryExtractFromHandle (IntPtr iconHandle, Int32Rect sourceRect, out ImageSource imageSource)
static bool TryExtractFromHandle (IntPtr iconHandle, out ImageSource imageSource)
static ? ImageSource ExtractFromIcoFile (string icoPath, int index=0)
Gets an ImageSource from an icon file (.ico).
static bool TryExtractFromIcoFile (string icoPath, int index, out ImageSource imageSource)
Attempts to get an ImageSource from an icon file (.ico).
static bool TryExtractFromIcoFile (string icoPath, out ImageSource imageSource)
static ? ImageSource ExtractFromImageFile (Uri imageUri)
Gets an ImageSource from the specified image file (.png, .jpg, etc.).
static ? ImageSource ExtractFromImageFile (string imagePath)
static bool TryExtractFromImageFile (Uri imageUri, out ImageSource imageSource)
Attempts to get an ImageSource from the specified image file (.png, .jpg, etc.).
static bool TryExtractFromImageFile (string imagePath, out ImageSource imageSource)
static ? ImageSource ExtractFromFile (string filePath)
Gets an ImageSource for the icon of a regular file, including executable files (.exe).
static bool TryExtractFromFile (string filePath, out ImageSource imageSource)
Attempts to get an ImageSource for the icon of a regular file, including executable files (.exe).
static ? ImageSource ExtractFromDirectory (string directoryPath)
Gets an ImageSource for the specified directory.
static bool TryExtractFromDirectory (string directoryPath, out ImageSource imageSource)
Attempts to get an ImageSource for the specified directory.
static ? ImageSource ExtractFromDll (string dllPath, int index, bool getSmallIcon)
Gets an ImageSource from an icon in the specified dynamic-link library file (.dll).
static bool TryExtractFromDll (string dllPath, int index, bool getSmallIcon, out ImageSource imageSource)
Attempts to get an ImageSource from an icon in the specified dynamic-link library file (.dll).
static ? ImageSource ExtractFromPath (string iconPath, bool getSmallIcon=true)
Gets an ImageSource from the specified iconPath .
static bool TryExtractFromPath (string iconPath, bool getSmallIcon, out ImageSource imageSource)
Attempts to get an ImageSource from the specified iconPath .
static bool TryExtractFromPath (string path, out ImageSource imageSource)
static void ParseIconPath (string iconPath, out string filePath, out int iconIndex)
Parses the specified iconPath by separating the filepath and the icon index.
Detailed Description
A static class that provides methods for extracting icons from files, directories, or DLLs, as well as directly loading them from icon or image files.
Member Function Documentation
ExtractFromDirectory()
static ? ImageSource VolumeControl.WPF.IconExtractor.ExtractFromDirectory (string directoryPath) static
Gets an ImageSource for the specified directory.
Parameters
directoryPath The location of a directory.
Returns
An ImageSource for the specified directory's icon if successful; otherwise null.
Referenced by VolumeControl.WPF.IconExtractor.ExtractFromPath(), and VolumeControl.WPF.IconExtractor.TryExtractFromDirectory().
ExtractFromDll()
static ? ImageSource VolumeControl.WPF.IconExtractor.ExtractFromDll (string dllPath, int index, bool getSmallIcon) static
Gets an ImageSource from an icon in the specified dynamic-link library file (.dll).
Parameters
dllPath The location of a DLL.
index The index of the icon to retrieve.
getSmallIcon When true, retrieves the smaller size of icon; otherwise retrieves the larger size of icon.
Returns
An ImageSource for the specified icon if successful; otherwise null.
Referenced by VolumeControl.WPF.IconExtractor.ExtractFromPath(), and VolumeControl.WPF.IconExtractor.TryExtractFromDll().
ExtractFromFile()
static ? ImageSource VolumeControl.WPF.IconExtractor.ExtractFromFile (string filePath) static
Gets an ImageSource for the icon of a regular file, including executable files (.exe).
Parameters
filePath The location of a file.
Returns
An ImageSource for the specified file's icon if successful; otherwise null.
Referenced by VolumeControl.WPF.IconExtractor.ExtractFromPath(), and VolumeControl.WPF.IconExtractor.TryExtractFromFile().
ExtractFromHandle()
static ImageSource VolumeControl.WPF.IconExtractor.ExtractFromHandle (IntPtr iconHandle, Int32Rect sourceRect, BitmapSizeOptions sizeOptions) static
Gets an ImageSource from the specified iconHandle .
Internally, this just calls Imaging.CreateBitmapSourceFromHIcon(IntPtr, Int32Rect, BitmapSizeOptions).
Parameters
iconHandle A pointer to the unmanaged icon source.
sourceRect The size of the source image.
sizeOptions The output size of the ImageSource.
Returns
An ImageSource for the specified iconHandle if successful; otherwise null.
Referenced by VolumeControl.WPF.IconExtractor.TryExtractFromHandle().
ExtractFromIcoFile()
static ? ImageSource VolumeControl.WPF.IconExtractor.ExtractFromIcoFile (string icoPath, int index = 0) static
Gets an ImageSource from an icon file (.ico).
To get an ImageSource from image filetypes other than ICO, use the ExtractFromImageFile(Uri) function instead.
Parameters
icoPath The path to the ICO file.
index The index of the icon to retrieve from the ICO file. Not all ICO files contain multiple icons
Returns
An ImageSource for the specified icon if successful; otherwise null.
Exceptions
InvalidOperationException The specified index is not valid for the specified file.
Referenced by VolumeControl.WPF.IconExtractor.ExtractFromPath(), and VolumeControl.WPF.IconExtractor.TryExtractFromIcoFile().
ExtractFromImageFile() [1/2]
static ? ImageSource VolumeControl.WPF.IconExtractor.ExtractFromImageFile (string imagePath) static
Parameters
imagePath The imageUri of an image file.
ExtractFromImageFile() [2/2]
static ? ImageSource VolumeControl.WPF.IconExtractor.ExtractFromImageFile (Uri imageUri) static
Gets an ImageSource from the specified image file (.png, .jpg, etc.).
This function is not capable of loading icon files (.ico) that contain multiple icons; use the ExtractFromIcoFile(string, int) function instead.
Parameters
imageUri The Uri of an image file.
Returns
An ImageSource for the specified image if successful; otherwise null.
Referenced by VolumeControl.WPF.IconExtractor.TryExtractFromImageFile().
ExtractFromPath()
static ? ImageSource VolumeControl.WPF.IconExtractor.ExtractFromPath (string iconPath, bool getSmallIcon = true) static
Gets an ImageSource from the specified iconPath .
Parameters
iconPath A filesystem path to a file or directory, or the path and index of an icon in a DLL.
getSmallIcon When true, retrieves the smaller size of icon; otherwise retrieves the larger size of icon.
Returns
An ImageSource for the specified icon if successful; otherwise null.
References VolumeControl.WPF.IconExtractor.ExtractFromDirectory(), VolumeControl.WPF.IconExtractor.ExtractFromDll(), VolumeControl.WPF.IconExtractor.ExtractFromFile(), VolumeControl.WPF.IconExtractor.ExtractFromIcoFile(), and VolumeControl.WPF.IconExtractor.ParseIconPath().
Referenced by VolumeControl.WPF.IconExtractor.TryExtractFromPath().
ParseIconPath()
static void VolumeControl.WPF.IconExtractor.ParseIconPath (string iconPath, out string filePath, out int iconIndex) static
Parses the specified iconPath by separating the filepath and the icon index.
This is used by ExtractFromPath(string, bool) to parse icon paths that point to a specific icon within a DLL that may contain multiple icons.
Parameters
iconPath The path to an icon within a file, or the path to an icon file.
filePath The path to the file that contains the target icon.
iconIndex The index of the target icon when the specified iconPath contains one; otherwise -1.
Referenced by VolumeControl.WPF.IconExtractor.ExtractFromPath().
TryExtractFromDirectory()
static bool VolumeControl.WPF.IconExtractor.TryExtractFromDirectory (string directoryPath, out ImageSource imageSource) static
Attempts to get an ImageSource for the specified directory.
Parameters
directoryPath The location of a directory.
imageSource An ImageSource for the specified directory icon if successful.
Returns
true when no exceptions occurred and imageSource is not null; otherwise false.
References VolumeControl.WPF.IconExtractor.ExtractFromDirectory().
TryExtractFromDll()
static bool VolumeControl.WPF.IconExtractor.TryExtractFromDll (string dllPath, int index, bool getSmallIcon, out ImageSource imageSource) static
Attempts to get an ImageSource from an icon in the specified dynamic-link library file (.dll).
Parameters
dllPath The location of a DLL.
index The index of the icon to retrieve.
getSmallIcon When true, retrieves the smaller size of icon; otherwise retrieves the larger size of icon.
imageSource An ImageSource for the specified icon if successful.
Returns
true when no exceptions occurred and imageSource is not null; otherwise false.
References VolumeControl.WPF.IconExtractor.ExtractFromDll().
TryExtractFromFile()
static bool VolumeControl.WPF.IconExtractor.TryExtractFromFile (string filePath, out ImageSource imageSource) static
Attempts to get an ImageSource for the icon of a regular file, including executable files (.exe).
Parameters
filePath The location of a file.
imageSource An ImageSource for the specified file icon if successful.
Returns
true when no exceptions occurred and imageSource is not null; otherwise false.
References VolumeControl.WPF.IconExtractor.ExtractFromFile().
TryExtractFromHandle()
static bool VolumeControl.WPF.IconExtractor.TryExtractFromHandle (IntPtr iconHandle, Int32Rect sourceRect, BitmapSizeOptions sizeOptions, out ImageSource imageSource) static
Attempts to get an ImageSource from the specified iconHandle .
Parameters
iconHandle A pointer to the unmanaged icon source.
sourceRect The size of the source image.
sizeOptions The output size of the ImageSource.
imageSource An ImageSource for the specified iconHandle if successful.
Returns
true when no exceptions occurred and imageSource is not null; otherwise false.
References VolumeControl.WPF.IconExtractor.ExtractFromHandle().
TryExtractFromIcoFile()
static bool VolumeControl.WPF.IconExtractor.TryExtractFromIcoFile (string icoPath, int index, out ImageSource imageSource) static
Attempts to get an ImageSource from an icon file (.ico).
Parameters
icoPath The path to the ICO file.
index The index of the icon to retrieve from the ICO file. Not all ICO files contain multiple icons
imageSource An ImageSource for the specified icon if successful.
Returns
true when no exceptions occurred and imageSource is not null; otherwise false.
References VolumeControl.WPF.IconExtractor.ExtractFromIcoFile().
TryExtractFromImageFile()
static bool VolumeControl.WPF.IconExtractor.TryExtractFromImageFile (Uri imageUri, out ImageSource imageSource) static
Attempts to get an ImageSource from the specified image file (.png, .jpg, etc.).
Parameters
imageUri The Uri of an image file.
imageSource An ImageSource for the specified image if successful.
Returns
true when no exceptions occurred and imageSource is not null; otherwise false.
References VolumeControl.WPF.IconExtractor.ExtractFromImageFile().
TryExtractFromPath()
static bool VolumeControl.WPF.IconExtractor.TryExtractFromPath (string iconPath, bool getSmallIcon, out ImageSource imageSource) static
Attempts to get an ImageSource from the specified iconPath .
Parameters
iconPath A filesystem path to a file or directory, or the path and index of an icon in a DLL.
getSmallIcon When true, retrieves the smaller size of icon; otherwise retrieves the larger size of icon.
imageSource An ImageSource for the specified icon if successful.
Returns
true when no exceptions occurred and imageSource is not null; otherwise false.
References VolumeControl.WPF.IconExtractor.ExtractFromPath().
The documentation for this class was generated from the following file:
/home/runner/work/volume-control/volume-control/VolumeControl.WPF/IconExtractor.cs