Volume Control: VolumeControl.WPF.WpfAddTiltScrollEventHook Class Reference
VolumeControl.WPF.WpfAddTiltScrollEventHook Class Reference
Provides a window message hook that adds support for horizontal scrolling with tiltable mouse wheels.
Static Public Member Functions
static void AddPreviewMouseWheelHorizontalHandler (DependencyObject d, MouseWheelHorizontalEventHandler handler)
Adds the specified handler to the PreviewMouseWheelHorizontalEvent.
static void RemovePreviewMouseWheelHorizontalHandler (DependencyObject d, MouseWheelHorizontalEventHandler handler)
Removes the specified handler from the PreviewMouseWheelHorizontalEvent.
static void AddMouseWheelHorizontalHandler (DependencyObject d, MouseWheelHorizontalEventHandler handler)
Adds the specified handler to the MouseWheelHorizontalEvent.
static void RemoveMouseWheelHorizontalHandler (DependencyObject d, MouseWheelHorizontalEventHandler handler)
Removes the specified handler from the MouseWheelHorizontalEvent.
static HwndSourceHook GetHook ()
Gets the WpfAddTiltScrollEventHook HwndSourceHook instance.
Static Public Attributes
static readonly RoutedEvent PreviewMouseWheelHorizontalEvent
Occurs when the user tilts the mouse wheel while the mouse pointer is over this element.
static readonly RoutedEvent MouseWheelHorizontalEvent
Occurs when the user tilts the mouse wheel while the mouse pointer is over this element.
Detailed Description
Provides a window message hook that adds support for horizontal scrolling with tiltable mouse wheels.
Adds an attached event to all UIElements that triggers when the user tilts the mouse scroll wheel.
Member Function Documentation
AddMouseWheelHorizontalHandler()
static void VolumeControl.WPF.WpfAddTiltScrollEventHook.AddMouseWheelHorizontalHandler (DependencyObject d, MouseWheelHorizontalEventHandler handler) static
Adds the specified handler to the MouseWheelHorizontalEvent.
References VolumeControl.WPF.WpfAddTiltScrollEventHook.MouseWheelHorizontalEvent.
AddPreviewMouseWheelHorizontalHandler()
static void VolumeControl.WPF.WpfAddTiltScrollEventHook.AddPreviewMouseWheelHorizontalHandler (DependencyObject d, MouseWheelHorizontalEventHandler handler) static
Adds the specified handler to the PreviewMouseWheelHorizontalEvent.
References VolumeControl.WPF.WpfAddTiltScrollEventHook.PreviewMouseWheelHorizontalEvent.
Referenced by VolumeControl.WPF.Behaviors.ScrollViewerHorizontalScrollBehavior.OnAttached(), and VolumeControl.WPF.Behaviors.TextBoxHorizontalScrollBehavior.OnAttached().
GetHook()
static HwndSourceHook VolumeControl.WPF.WpfAddTiltScrollEventHook.GetHook () static
Gets the WpfAddTiltScrollEventHook HwndSourceHook instance.
RemoveMouseWheelHorizontalHandler()
static void VolumeControl.WPF.WpfAddTiltScrollEventHook.RemoveMouseWheelHorizontalHandler (DependencyObject d, MouseWheelHorizontalEventHandler handler) static
Removes the specified handler from the MouseWheelHorizontalEvent.
RemovePreviewMouseWheelHorizontalHandler()
static void VolumeControl.WPF.WpfAddTiltScrollEventHook.RemovePreviewMouseWheelHorizontalHandler (DependencyObject d, MouseWheelHorizontalEventHandler handler) static
Removes the specified handler from the PreviewMouseWheelHorizontalEvent.
Referenced by VolumeControl.WPF.Behaviors.ScrollViewerHorizontalScrollBehavior.OnDetaching(), and VolumeControl.WPF.Behaviors.TextBoxHorizontalScrollBehavior.OnDetaching().
Member Data Documentation
MouseWheelHorizontalEvent
readonly RoutedEvent VolumeControl.WPF.WpfAddTiltScrollEventHook.MouseWheelHorizontalEvent static
Initial value:
= EventManager.RegisterRoutedEvent(
            "MouseWheelHorizontal",
            RoutingStrategy.Bubble,
            typeof(MouseWheelHorizontalEventHandler),
            typeof(WpfAddTiltScrollEventHook))
Occurs when the user tilts the mouse wheel while the mouse pointer is over this element.
Referenced by VolumeControl.WPF.WpfAddTiltScrollEventHook.AddMouseWheelHorizontalHandler().
PreviewMouseWheelHorizontalEvent
readonly RoutedEvent VolumeControl.WPF.WpfAddTiltScrollEventHook.PreviewMouseWheelHorizontalEvent static
Initial value:
= EventManager.RegisterRoutedEvent(
            "PreviewMouseWheelHorizontal",
            RoutingStrategy.Tunnel,
            typeof(MouseWheelHorizontalEventHandler),
            typeof(WpfAddTiltScrollEventHook))
Occurs when the user tilts the mouse wheel while the mouse pointer is over this element.
Referenced by VolumeControl.WPF.WpfAddTiltScrollEventHook.AddPreviewMouseWheelHorizontalHandler().
The documentation for this class was generated from the following file:
/home/runner/work/volume-control/volume-control/VolumeControl.WPF/WpfAddTiltScrollEventHook.cs