Volume Control: VolumeControl.Core.Input.HotkeyManager Class Reference
VolumeControl.Core.Input.HotkeyManager Class Reference
Manages a list of Hotkey instances.
Public Member Functions
HotkeyManager (HotkeyActionManager actionManager)
Creates a new HotkeyManager instance from the specified actionManager .
HotkeyManager ()
Creates a new HotkeyManager instance with a new Actions.HotkeyActionManager instance.
Hotkey? GetHotkey (ushort id)
Gets the Hotkey with the specified id .
void AddHotkey (Hotkey hotkey)
Adds the specified hotkey to the manager.
bool RemoveHotkey (Hotkey hotkey)
Removes the specified hotkey from the manager.
bool RemoveHotkey (ushort id)
Removes the hotkey with the specified id from the manager.
void ClearHotkeys ()
Removes all hotkeys from the manager.
virtual JsonHotkey[] GetJsonHotkeys ()
Gets a list of JsonHotkey instances for the list of managed hotkeys.
void AddJsonHotkeys< THotkey > (params JsonHotkey[] hotkeyJsonObjects)
Creates and adds a Hotkey for each element of the specified hotkeyJsonObjects .
void SetHotkeysFromJsonHotkeys< THotkey > (JsonHotkey[] hotkeyJsonObjects)
Sets the list of managed hotkeys from the specified hotkeyJsonObjects .
virtual void SetHotkeysFromJsonHotkeys (JsonHotkey[] hotkeyJsonObjects)
Properties
HotkeyActionManager HotkeyActionManager [get]
Gets the action manager instance for this HotkeyManager.
IReadOnlyList< Hotkey > Hotkeys [get]
Gets the hotkey instances that are being managed by this HotkeyManager.
IReadOnlyList< HotkeyMessageHookAbstractor > HookAbstractors [get]
Gets the list of HotkeyMessageHookAbstractor instances that are currently active.
Events
EventHandler< Hotkey >? AddedHotkey
Occurs when a hotkey is added to the list for any reason.
EventHandler< Hotkey >? RemovedHotkey
Occurs when a hotkey is removed from the list for any reason.
Detailed Description
Manages a list of Hotkey instances.
Constructor & Destructor Documentation
HotkeyManager() [1/2]
VolumeControl.Core.Input.HotkeyManager.HotkeyManager (HotkeyActionManager actionManager)
Creates a new HotkeyManager instance from the specified actionManager .
Parameters
actionManager A HotkeyActionManager instance to use for managing hotkey actions.
HotkeyManager() [2/2]
VolumeControl.Core.Input.HotkeyManager.HotkeyManager ()
Creates a new HotkeyManager instance with a new Actions.HotkeyActionManager instance.
Member Function Documentation
AddHotkey()
void VolumeControl.Core.Input.HotkeyManager.AddHotkey (Hotkey hotkey)
Adds the specified hotkey to the manager.
Parameters
hotkey A Hotkey instance to add to the list of managed hotkeys.
Exceptions
ArgumentException The hotkey is already being managed by this HotkeyManager.
References VolumeControl.Core.Input.HotkeyManager.Hotkeys, and VolumeControl.Core.Input.Hotkey.Registering.
Referenced by VolumeControl.Core.Input.HotkeyManager.AddJsonHotkeys< THotkey >().
AddJsonHotkeys< THotkey >()
void VolumeControl.Core.Input.HotkeyManager.AddJsonHotkeys< THotkey > (params JsonHotkey[] hotkeyJsonObjects)
Creates and adds a Hotkey for each element of the specified hotkeyJsonObjects .
Template Parameters
THotkey A type derived from Hotkey to create. Specifying this allows you to substitute derived types in place of the default Hotkey type.
Parameters
hotkeyJsonObjects The JSON object representation of any number of Hotkeys.
Type Constraints
THotkey : Hotkey
References VolumeControl.Core.Input.HotkeyManager.AddHotkey(), and VolumeControl.Core.Input.HotkeyManager.HotkeyActionManager.
Referenced by VolumeControl.Core.Input.HotkeyManager.SetHotkeysFromJsonHotkeys< THotkey >().
ClearHotkeys()
void VolumeControl.Core.Input.HotkeyManager.ClearHotkeys ()
Removes all hotkeys from the manager.
References VolumeControl.Core.Input.HotkeyManager.Hotkeys, and VolumeControl.Core.Input.HotkeyManager.RemoveHotkey().
Referenced by VolumeControl.Core.Input.HotkeyManager.SetHotkeysFromJsonHotkeys< THotkey >().
GetHotkey()
Hotkey? VolumeControl.Core.Input.HotkeyManager.GetHotkey (ushort id)
Gets the Hotkey with the specified id .
Parameters
id The unique ID number of the hotkey to get.
Returns
The Hotkey instance with the specified id number if found; otherwise null.
GetJsonHotkeys()
virtual JsonHotkey [] VolumeControl.Core.Input.HotkeyManager.GetJsonHotkeys () virtual
Gets a list of JsonHotkey instances for the list of managed hotkeys.
Returns
An array of JsonHotkey instances.
References VolumeControl.Core.Input.HotkeyManager.Hotkeys.
RemoveHotkey() [1/2]
bool VolumeControl.Core.Input.HotkeyManager.RemoveHotkey (Hotkey hotkey)
Removes the specified hotkey from the manager.
Parameters
hotkey A Hotkey instance to remove from the list of managed hotkeys.
Returns
true when the hotkey was successfully removed; otherwise false.
Exceptions
ArgumentException The hotkey is not being managed by this HotkeyManager.
References VolumeControl.Core.Input.Hotkey.Dispose(), VolumeControl.Core.Input.HotkeyManager.Hotkeys, and VolumeControl.Core.Input.Hotkey.Registering.
Referenced by VolumeControl.Core.Input.HotkeyManager.ClearHotkeys().
RemoveHotkey() [2/2]
bool VolumeControl.Core.Input.HotkeyManager.RemoveHotkey (ushort id)
Removes the hotkey with the specified id from the manager.
Parameters
id The unique ID number of a hotkey to remove.
Returns
true when the hotkey was successfully removed; otherwise false.
Exceptions
ArgumentException The hotkey with id is not being managed by this HotkeyManager.
SetHotkeysFromJsonHotkeys< THotkey >()
void VolumeControl.Core.Input.HotkeyManager.SetHotkeysFromJsonHotkeys< THotkey > (JsonHotkey[] hotkeyJsonObjects)
Sets the list of managed hotkeys from the specified hotkeyJsonObjects .
Template Parameters
THotkey A type derived from Hotkey to create. Specifying this allows you to substitute derived types in place of the default Hotkey type.
Parameters
hotkeyJsonObjects The JSON object representation of any number of Hotkeys.
Type Constraints
THotkey : Hotkey
References VolumeControl.Core.Input.HotkeyManager.AddJsonHotkeys< THotkey >(), and VolumeControl.Core.Input.HotkeyManager.ClearHotkeys().
Property Documentation
HookAbstractors
IReadOnlyList<HotkeyMessageHookAbstractor> VolumeControl.Core.Input.HotkeyManager.HookAbstractors get
Gets the list of HotkeyMessageHookAbstractor instances that are currently active.
HotkeyActionManager
HotkeyActionManager VolumeControl.Core.Input.HotkeyManager.HotkeyActionManager get
Gets the action manager instance for this HotkeyManager.
Referenced by VolumeControl.Core.Input.HotkeyManager.AddJsonHotkeys< THotkey >().
Hotkeys
IReadOnlyList<Hotkey> VolumeControl.Core.Input.HotkeyManager.Hotkeys get
Gets the hotkey instances that are being managed by this HotkeyManager.
Referenced by VolumeControl.Core.Input.HotkeyManager.AddHotkey(), VolumeControl.Core.Input.HotkeyManager.ClearHotkeys(), VolumeControl.Core.Input.HotkeyManager.GetJsonHotkeys(), and VolumeControl.Core.Input.HotkeyManager.RemoveHotkey().
Event Documentation
AddedHotkey
EventHandler<Hotkey>? VolumeControl.Core.Input.HotkeyManager.AddedHotkey
Occurs when a hotkey is added to the list for any reason.
RemovedHotkey
EventHandler<Hotkey>? VolumeControl.Core.Input.HotkeyManager.RemovedHotkey
Occurs when a hotkey is removed from the list for any reason.
The documentation for this class was generated from the following file:
/home/runner/work/volume-control/volume-control/VolumeControl.Core/Input/HotkeyManager.cs