Volume Control: VolumeControl.Core.Input.WindowsHotkeyAPI Class Reference
VolumeControl.Core.Input.WindowsHotkeyAPI Class Reference
API for interacting with the global hotkey functionality exposed in the Win32 API.
Static Public Member Functions
static void Register (IHotkey hotkey)
Registers the specified hotkey .
static bool TryRegister (IHotkey hotkey)
Attempts to register the specified hotkey .
static void Unregister (IHotkey hotkey)
Unregisters the specified hotkey .
static bool TryUnregister (IHotkey hotkey)
Attempts to unregister the specified hotkey .
Static Public Attributes
const ushort MinID = 0x0000
The minimum valid hotkey ID number.
const ushort MaxID = 0xBFFF
The maximum valid hotkey ID number.
const int WM_HOTKEY = 0x312
Windows message type for hotkey messages.
Detailed Description
API for interacting with the global hotkey functionality exposed in the Win32 API.
Member Function Documentation
Register()
static void VolumeControl.Core.Input.WindowsHotkeyAPI.Register (IHotkey hotkey) static
Registers the specified hotkey .
Parameters
hotkey An IHotkey instance to register.
Exceptions
HotkeyRegistrationException Hotkey registration failed.
References VolumeControl.Core.Input.IHotkey.ID, VolumeControl.Core.Input.IHotkey.Key, VolumeControl.Core.Input.IHotkey.MessageHook, and VolumeControl.Core.Input.IHotkey.Modifiers.
Referenced by VolumeControl.Core.Input.HotkeyWithError.Register(), VolumeControl.Core.Input.HotkeyWithError.Reregister(), and VolumeControl.Core.Input.WindowsHotkeyAPI.TryRegister().
TryRegister()
static bool VolumeControl.Core.Input.WindowsHotkeyAPI.TryRegister (IHotkey hotkey) static
Attempts to register the specified hotkey .
Parameters
hotkey An IHotkey instance to register.
Returns
true when the hotkey was registered successfully; otherwise false.
References VolumeControl.Core.Input.WindowsHotkeyAPI.Register().
Referenced by VolumeControl.Core.Input.Hotkey.Register().
TryUnregister()
static bool VolumeControl.Core.Input.WindowsHotkeyAPI.TryUnregister (IHotkey hotkey) static
Attempts to unregister the specified hotkey .
Parameters
hotkey An IHotkey instance to unregister.
Returns
true when the hotkey was unregistered successfully; otherwise false.
References VolumeControl.Core.Input.WindowsHotkeyAPI.Unregister().
Referenced by VolumeControl.Core.Input.Hotkey.Unregister().
Unregister()
static void VolumeControl.Core.Input.WindowsHotkeyAPI.Unregister (IHotkey hotkey) static
Unregisters the specified hotkey .
Parameters
hotkey An IHotkey instance to unregister.
Exceptions
HotkeyRegistrationException Hotkey unregistration failed.
References VolumeControl.Core.Input.IHotkey.ID, and VolumeControl.Core.Input.IHotkey.MessageHook.
Referenced by VolumeControl.Core.Input.HotkeyWithError.Reregister(), VolumeControl.Core.Input.WindowsHotkeyAPI.TryUnregister(), and VolumeControl.Core.Input.HotkeyWithError.Unregister().
Member Data Documentation
MaxID
const ushort VolumeControl.Core.Input.WindowsHotkeyAPI.MaxID = 0xBFFF static
The maximum valid hotkey ID number.
This is defined by the Win32 API, and cannot be changed or circumvented. There are a total of 45,151 possible hotkey IDs.
MinID
const ushort VolumeControl.Core.Input.WindowsHotkeyAPI.MinID = 0x0000 static
The minimum valid hotkey ID number.
This is defined by the Win32 API, and cannot be changed or circumvented. There are a total of 45,151 possible hotkey IDs.
WM_HOTKEY
const int VolumeControl.Core.Input.WindowsHotkeyAPI.WM_HOTKEY = 0x312 static
Windows message type for hotkey messages.
The documentation for this class was generated from the following file:
/home/runner/work/volume-control/volume-control/VolumeControl.Core/Input/WindowsHotkeyAPI.cs