Volume Control: VolumeControl.CoreAudio.AudioSessionMultiSelector Class Reference
VolumeControl.CoreAudio.AudioSessionMultiSelector Class Reference
Manages multiple "selected" audio sessions for a given CoreAudio.AudioSessionManager instance.
Public Member Functions
AudioSessionMultiSelector (AudioSessionManager audioSessionManager)
Creates a new AudioSessionMultiSelector instance for the specified audioSessionManager .
void NotifyActiveSessionChanged (AudioSession? audioSession)
Occurs when the ActiveSession is changed for any reason.
bool GetSessionIsSelected (AudioSession audioSession)
Gets whether the specified audioSession is selected or not.
void SetSessionIsSelected (AudioSession audioSession, bool isSelected)
Sets whether the specified audioSession is selected or not.
void SetSessionIsSelected (int index, bool isSelected)
Sets whether the AudioSession at the specified index is selected or not.
void SetAllSessionSelectionStates (bool isSelected)
Sets whether all AudioSession instances in the Sessions list are selected or not.
void SetSelectedSessions (params AudioSession[] sessions)
Sets only the specified sessions as selected.
void SetSelectedSessions (IEnumerable< AudioSession > sessions)
void SetSelectedSessionsOrCurrentSession (params AudioSession[] sessions)
Sets only the specified sessions as selected, unless sessions contains exactly 1 session in which case the CurrentSession is set and all sessions are deselected.
void SetSelectedSessionsOrCurrentSession (IEnumerable< AudioSession > sessions)
void ClearSelectedSessions ()
Unselects all SelectedSessions.
void SelectCurrentItem ()
Selects the CurrentItem.
void DeselectCurrentItem ()
Deselects the CurrentItem.
void ToggleSelectCurrentItem ()
Toggles whether the CurrentItem is selected.
void IncrementCurrentIndex ()
Increments the CurrentIndex by 1, looping back around to 0 when it exceeds the length of the Sessions list.
void DecrementCurrentIndex ()
Decrements the CurrentIndex by 1, looping back around to the length of the Sessions list when it goes past 0.
void UnsetCurrentIndex ()
Sets the CurrentIndex to 0.
bool NotificationIsEmpty ()
Gets whether the session notification would be empty after applying all filters.
Properties
IReadOnlyList< bool > SelectionStates [get, set]
IReadOnlyList< AudioSession > SelectedSessions [get, set]
Gets or sets the list of selected AudioSession instances.
bool HasSelectedSessions [get]
Gets whether there are any selected sessions or not.
int? CurrentIndex [get, set]
bool LockCurrentIndex [get, set]
AudioSession?? CurrentSession [get, set]
Gets or sets the session that the selector is currently pointing at.
bool LockSelection [get, set]
bool LockCurrentIndexOnLockSelection [get, set]
Gets or sets whether the LockCurrentIndex property is also set when LockSelection is changed.
Properties inherited from VolumeControl.CoreAudio.Interfaces.IAudioMultiSelector
IReadOnlyList< bool > SelectionStates [get, set]
Gets or sets the selection state of each AudioSession instance in the Sessions list.
int CurrentIndex [get, set]
Gets or sets the current index of the selector in the Sessions list.
bool LockCurrentIndex [get, set]
Gets or sets whether the CurrentIndex can be changed.
bool LockSelection [get, set]
Gets or sets whether the selected items can be changed.
Events
PropertyChangedEventHandler? PropertyChanged
EventHandler< AudioSession >? SessionSelected
Occurs when a session is selected for any reason.
EventHandler< AudioSession >? SessionDeselected
Occurs when a session is deselected for any reason.
EventHandler< AudioSession?>? CurrentSessionChanged
Occurs when the CurrentItem is changed for any reason.
EventHandler< AudioSession?>? ActiveSessionChanged
Occurs when the ActiveSession is changed for any reason.
PreviewSessionIsSelectedEventHandler? PreviewSessionIsSelected
Occurs prior to a new session being added, allowing handlers to determine if it should be selected by default.
Detailed Description
Manages multiple "selected" audio sessions for a given CoreAudio.AudioSessionManager instance.
Constructor & Destructor Documentation
AudioSessionMultiSelector()
VolumeControl.CoreAudio.AudioSessionMultiSelector.AudioSessionMultiSelector (AudioSessionManager audioSessionManager)
Creates a new AudioSessionMultiSelector instance for the specified audioSessionManager .
Parameters
audioSessionManager An CoreAudio.AudioSessionManager instance to select from.
References VolumeControl.CoreAudio.AudioSessionManager.AddedSessionToList, VolumeControl.CoreAudio.AudioSessionMultiSelector.CurrentIndex, and VolumeControl.CoreAudio.AudioSessionManager.RemovingSessionFromList.
Member Function Documentation
ClearSelectedSessions()
void VolumeControl.CoreAudio.AudioSessionMultiSelector.ClearSelectedSessions ()
Unselects all SelectedSessions.
DecrementCurrentIndex()
void VolumeControl.CoreAudio.AudioSessionMultiSelector.DecrementCurrentIndex ()
Decrements the CurrentIndex by 1, looping back around to the length of the Sessions list when it goes past 0.
Does nothing when LockCurrentIndex is true.
References VolumeControl.CoreAudio.AudioSessionMultiSelector.CurrentIndex, VolumeControl.Core.Config.HideInactiveSessions, and VolumeControl.CoreAudio.AudioSessionMultiSelector.LockCurrentIndex.
DeselectCurrentItem()
void VolumeControl.CoreAudio.AudioSessionMultiSelector.DeselectCurrentItem ()
Deselects the CurrentItem.
Does nothing when LockSelection is true or CurrentIndex is -1.
References VolumeControl.CoreAudio.AudioSessionMultiSelector.CurrentIndex, VolumeControl.CoreAudio.AudioSessionMultiSelector.CurrentSession, and VolumeControl.CoreAudio.AudioSessionMultiSelector.LockSelection.
GetSessionIsSelected()
bool VolumeControl.CoreAudio.AudioSessionMultiSelector.GetSessionIsSelected (AudioSession audioSession)
Gets whether the specified audioSession is selected or not.
Parameters
audioSession An AudioSession instance.
Returns
true when the audioSession is selected; otherwise false.
Exceptions
ArgumentException The specified audioSession does not exist in the AudioSessionManager.
References VolumeControl.CoreAudio.AudioSessionMultiSelector.SelectionStates.
IncrementCurrentIndex()
void VolumeControl.CoreAudio.AudioSessionMultiSelector.IncrementCurrentIndex ()
Increments the CurrentIndex by 1, looping back around to 0 when it exceeds the length of the Sessions list.
Does nothing when LockCurrentIndex is true.
References VolumeControl.CoreAudio.AudioSessionMultiSelector.CurrentIndex, VolumeControl.Core.Config.HideInactiveSessions, and VolumeControl.CoreAudio.AudioSessionMultiSelector.LockCurrentIndex.
NotificationIsEmpty()
bool VolumeControl.CoreAudio.AudioSessionMultiSelector.NotificationIsEmpty ()
Gets whether the session notification would be empty after applying all filters.
Returns
true when the session notification would be empty; otherwise false.
References VolumeControl.CoreAudio.AudioSessionMultiSelector.CurrentSession, and VolumeControl.Core.Config.HideInactiveSessions.
Referenced by VolumeControl.SDK.VCAPI.ShowSessionListNotification().
NotifyActiveSessionChanged()
void VolumeControl.CoreAudio.AudioSessionMultiSelector.NotifyActiveSessionChanged (AudioSession? audioSession)
Occurs when the ActiveSession is changed for any reason.
Referenced by VolumeControl.SDK.VCAPI.ShowSessionListNotification().
SelectCurrentItem()
void VolumeControl.CoreAudio.AudioSessionMultiSelector.SelectCurrentItem ()
Selects the CurrentItem.
Does nothing when LockSelection is true or CurrentIndex is -1.
References VolumeControl.CoreAudio.AudioSessionMultiSelector.CurrentIndex, VolumeControl.CoreAudio.AudioSessionMultiSelector.CurrentSession, and VolumeControl.CoreAudio.AudioSessionMultiSelector.LockSelection.
SetAllSessionSelectionStates()
void VolumeControl.CoreAudio.AudioSessionMultiSelector.SetAllSessionSelectionStates (bool isSelected)
Sets whether all AudioSession instances in the Sessions list are selected or not.
Parameters
isSelected true selects the sessions; false deselects the sessions.
References VolumeControl.CoreAudio.AudioSessionMultiSelector.SelectionStates, and VolumeControl.CoreAudio.AudioSessionMultiSelector.SetSessionIsSelected().
Referenced by VolumeControl.CoreAudio.AudioSessionMultiSelector.SetSelectedSessionsOrCurrentSession().
SetSelectedSessions()
void VolumeControl.CoreAudio.AudioSessionMultiSelector.SetSelectedSessions (params AudioSession[] sessions)
Sets only the specified sessions as selected.
Parameters
sessions Any number of audio sessions.
References VolumeControl.CoreAudio.AudioSessionMultiSelector.SelectionStates, and VolumeControl.CoreAudio.AudioSessionMultiSelector.SetSessionIsSelected().
Referenced by VolumeControl.CoreAudio.AudioSessionMultiSelector.SetSelectedSessionsOrCurrentSession().
SetSelectedSessionsOrCurrentSession()
void VolumeControl.CoreAudio.AudioSessionMultiSelector.SetSelectedSessionsOrCurrentSession (params AudioSession[] sessions)
Sets only the specified sessions as selected, unless sessions contains exactly 1 session in which case the CurrentSession is set and all sessions are deselected.
Parameters
sessions Any number of audio sessions.
References VolumeControl.CoreAudio.AudioSessionMultiSelector.CurrentSession, VolumeControl.CoreAudio.AudioSessionMultiSelector.SetAllSessionSelectionStates(), and VolumeControl.CoreAudio.AudioSessionMultiSelector.SetSelectedSessions().
SetSessionIsSelected() [1/2]
void VolumeControl.CoreAudio.AudioSessionMultiSelector.SetSessionIsSelected (AudioSession audioSession, bool isSelected)
Sets whether the specified audioSession is selected or not.
Parameters
audioSession An AudioSession instance.
isSelected true selects the audioSession ; false deselects the audioSession .
Exceptions
ArgumentException The specified audioSession does not exist in the AudioSessionManager.
References VolumeControl.CoreAudio.AudioSession.IsSelected.
Referenced by VolumeControl.CoreAudio.AudioSessionMultiSelector.SetAllSessionSelectionStates(), and VolumeControl.CoreAudio.AudioSessionMultiSelector.SetSelectedSessions().
SetSessionIsSelected() [2/2]
void VolumeControl.CoreAudio.AudioSessionMultiSelector.SetSessionIsSelected (int index, bool isSelected)
Sets whether the AudioSession at the specified index is selected or not.
Parameters
index The zero-based index of the AudioSession instance to (de)select.
isSelected true selects the session; false deselects the session.
Exceptions
ArgumentOutOfRangeException The specified index is out-of-range of the Sessions list.
ToggleSelectCurrentItem()
void VolumeControl.CoreAudio.AudioSessionMultiSelector.ToggleSelectCurrentItem ()
Toggles whether the CurrentItem is selected.
Does nothing when LockSelection is true or CurrentIndex is -1.
References VolumeControl.CoreAudio.AudioSessionMultiSelector.CurrentIndex, VolumeControl.CoreAudio.AudioSessionMultiSelector.CurrentSession, VolumeControl.CoreAudio.AudioSessionMultiSelector.LockSelection, and VolumeControl.CoreAudio.AudioSessionMultiSelector.SelectionStates.
UnsetCurrentIndex()
void VolumeControl.CoreAudio.AudioSessionMultiSelector.UnsetCurrentIndex ()
Sets the CurrentIndex to 0.
Does nothing when LockCurrentIndex is true.
References VolumeControl.CoreAudio.AudioSessionMultiSelector.CurrentIndex, and VolumeControl.CoreAudio.AudioSessionMultiSelector.LockCurrentIndex.
Property Documentation
CurrentSession
AudioSession?? VolumeControl.CoreAudio.AudioSessionMultiSelector.CurrentSession get set
Gets or sets the session that the selector is currently pointing at.
Referenced by VolumeControl.CoreAudio.AudioSessionMultiSelector.DeselectCurrentItem(), VolumeControl.CoreAudio.AudioSessionMultiSelector.NotificationIsEmpty(), VolumeControl.CoreAudio.AudioSessionMultiSelector.SelectCurrentItem(), VolumeControl.CoreAudio.AudioSessionMultiSelector.SetSelectedSessionsOrCurrentSession(), and VolumeControl.CoreAudio.AudioSessionMultiSelector.ToggleSelectCurrentItem().
HasSelectedSessions
bool VolumeControl.CoreAudio.AudioSessionMultiSelector.HasSelectedSessions get
Gets whether there are any selected sessions or not.
Returns
true when there is at least one selected session; otherwise false.
LockCurrentIndexOnLockSelection
bool VolumeControl.CoreAudio.AudioSessionMultiSelector.LockCurrentIndexOnLockSelection get set
Gets or sets whether the LockCurrentIndex property is also set when LockSelection is changed.
SelectedSessions
IReadOnlyList<AudioSession> VolumeControl.CoreAudio.AudioSessionMultiSelector.SelectedSessions get set
Gets or sets the list of selected AudioSession instances.
Returns
An array of all selected AudioSessions in the order that they appear in the Sessions list.
Event Documentation
ActiveSessionChanged
EventHandler<AudioSession?>? VolumeControl.CoreAudio.AudioSessionMultiSelector.ActiveSessionChanged
Occurs when the ActiveSession is changed for any reason.
CurrentSessionChanged
EventHandler<AudioSession?>? VolumeControl.CoreAudio.AudioSessionMultiSelector.CurrentSessionChanged
Occurs when the CurrentItem is changed for any reason.
PreviewSessionIsSelected
PreviewSessionIsSelectedEventHandler? VolumeControl.CoreAudio.AudioSessionMultiSelector.PreviewSessionIsSelected
Occurs prior to a new session being added, allowing handlers to determine if it should be selected by default.
SessionDeselected
EventHandler<AudioSession>? VolumeControl.CoreAudio.AudioSessionMultiSelector.SessionDeselected
Occurs when a session is deselected for any reason.
SessionSelected
EventHandler<AudioSession>? VolumeControl.CoreAudio.AudioSessionMultiSelector.SessionSelected
Occurs when a session is selected for any reason.
The documentation for this class was generated from the following file:
/home/runner/work/volume-control/volume-control/VolumeControl.CoreAudio/AudioSessionMultiSelector.cs