Volume Control: VolumeControl.CoreAudio.AudioSessionManager Class Reference
VolumeControl.CoreAudio.AudioSessionManager Class Reference
Manages a list of AudioSession instances and their related events for any number of AudioDeviceSessionManager instances.
Public Member Functions
AudioSessionManager ()
Creates a new AudioSessionManager instance without any SessionManagers.
AudioSessionManager (IEnumerable< AudioDeviceSessionManager > sessionManagers)
Creates a new AudioSessionManager instance with the given sessionManagers .
AudioSession? FindSession (Predicate< AudioSession > predicate)
AudioSession? FindSessionWithID (uint pid)
AudioSession? FindSessionWithProcessName (string processName, StringComparison sCompareType=StringComparison.OrdinalIgnoreCase)
AudioSession? FindSessionWithProcessIdentifier (string identifier, bool prioritizePID=true, StringComparison sCompareType=StringComparison.OrdinalIgnoreCase)
Gets a session from Sessions by parsing identifier to determine whether to pass it to FindSessionWithID(uint), FindSessionWithProcessName(string, StringComparison), or directly comparing it to the AudioSession.ProcessIdentifier property.
AudioSession? FindSessionWithSessionInstanceIdentifier (string sessionInstanceIdentifier)
bool AddSessionManager (AudioDeviceSessionManager sessionManager)
Adds the given sessionManager to the SessionManagers list.
int AddSessionManagers (IEnumerable< AudioDeviceSessionManager > sessionManagers)
Adds the given sessionManagers to the SessionManagers list using AddSessionManager(AudioDeviceSessionManager).
bool RemoveSessionManager (AudioDeviceSessionManager sessionManager)
Removes the given sessionManager from the SessionManagers list.
Properties
IReadOnlyList< AudioDeviceSessionManager > SessionManagers [get]
Gets the list of AudioDeviceSessionManager instances currently being managed by this AudioSessionManager instance.
IReadOnlyList< AudioSession > Sessions [get]
Gets the list of AudioSession instances currently being managed by this AudioSessionManager instance.
Events
EventHandler< AudioSession >? SessionAddedToList
Occurs when an AudioSession is added to the Sessions list for any reason.
EventHandler< AudioSession >? SessionRemovedFromList
Occurs when an AudioSession is removed from the Sessions list for any reason.
EventHandler< AudioDeviceSessionManager >? SessionManagerAddedToList
Occurs when an AudioDeviceSessionManager is added to the SessionManagers list for any reason.
EventHandler< AudioDeviceSessionManager >? SessionManagerRemovedFromList
Occurs when an AudioDeviceSessionManager is removed from the SessionManagers list for any reason.
Detailed Description
Manages a list of AudioSession instances and their related events for any number of AudioDeviceSessionManager instances.
AudioDeviceSessionManager instances can be retrieved from AudioDevice.SessionManager
Constructor & Destructor Documentation
AudioSessionManager() [1/2]
VolumeControl.CoreAudio.AudioSessionManager.AudioSessionManager ()
Creates a new AudioSessionManager instance without any SessionManagers.
AudioSessionManager() [2/2]
VolumeControl.CoreAudio.AudioSessionManager.AudioSessionManager (IEnumerable< AudioDeviceSessionManager > sessionManagers)
Creates a new AudioSessionManager instance with the given sessionManagers .
Parameters
sessionManagers Any number of AudioDeviceSessionManager instances to add to the SessionManagers list.
References VolumeControl.CoreAudio.AudioSessionManager.AddSessionManager().
Member Function Documentation
AddSessionManager()
bool VolumeControl.CoreAudio.AudioSessionManager.AddSessionManager (AudioDeviceSessionManager sessionManager)
Adds the given sessionManager to the SessionManagers list.
Parameters
sessionManager A AudioDeviceSessionManager instance to add.
Returns
true when successful; otherwise false if the sessionManager is already in the list.
References VolumeControl.CoreAudio.AudioDeviceSessionManager.SessionAddedToList, VolumeControl.CoreAudio.AudioSessionManager.SessionManagers, and VolumeControl.CoreAudio.AudioDeviceSessionManager.SessionRemovedFromList.
Referenced by VolumeControl.CoreAudio.AudioSessionManager.AddSessionManagers(), and VolumeControl.CoreAudio.AudioSessionManager.AudioSessionManager().
AddSessionManagers()
int VolumeControl.CoreAudio.AudioSessionManager.AddSessionManagers (IEnumerable< AudioDeviceSessionManager > sessionManagers)
Adds the given sessionManagers to the SessionManagers list using AddSessionManager(AudioDeviceSessionManager).
Parameters
sessionManagers Any number of AudioDeviceSessionManager instances to add.
Returns
The number of sessionManagers that were successfully added to the list.
References VolumeControl.CoreAudio.AudioSessionManager.AddSessionManager().
FindSessionWithProcessIdentifier()
AudioSession? VolumeControl.CoreAudio.AudioSessionManager.FindSessionWithProcessIdentifier (string identifier, bool prioritizePID = true, StringComparison sCompareType = StringComparison.OrdinalIgnoreCase)
Gets a session from Sessions by parsing identifier to determine whether to pass it to FindSessionWithID(uint), FindSessionWithProcessName(string, StringComparison), or directly comparing it to the AudioSession.ProcessIdentifier property.
Parameters
identifier This can match any of the following properties:
AudioSession.PID
AudioSession.ProcessNameUses sCompareType
AudioSession.ProcessIdentifierUses sCompareType
prioritizePID When true (default), process IDs are prioritized over process names, which returns more accurate results when multiple sessions have identical names but may take longer.
When false, the first process with a matching ID or name is returned.
sCompareType A StringComparison enum value to use when matching process names or full identifiers.
Returns
ISession if a session was found.
Returns null if nothing was found.
References VolumeControl.CoreAudio.AudioSession.PID, VolumeControl.CoreAudio.AudioSession.ProcessName, and VolumeControl.CoreAudio.AudioSessionManager.Sessions.
RemoveSessionManager()
bool VolumeControl.CoreAudio.AudioSessionManager.RemoveSessionManager (AudioDeviceSessionManager sessionManager)
Removes the given sessionManager from the SessionManagers list.
Parameters
sessionManager A AudioDeviceSessionManager instance to remove.
Returns
true when successful; otherwise false when the sessionManager wasn't in the list.
References VolumeControl.CoreAudio.AudioDeviceSessionManager.SessionAddedToList, VolumeControl.CoreAudio.AudioSessionManager.SessionManagers, and VolumeControl.CoreAudio.AudioDeviceSessionManager.SessionRemovedFromList.
Property Documentation
SessionManagers
IReadOnlyList<AudioDeviceSessionManager> VolumeControl.CoreAudio.AudioSessionManager.SessionManagers get
Gets the list of AudioDeviceSessionManager instances currently being managed by this AudioSessionManager instance.
Referenced by VolumeControl.CoreAudio.AudioSessionManager.AddSessionManager(), and VolumeControl.CoreAudio.AudioSessionManager.RemoveSessionManager().
Sessions
IReadOnlyList<AudioSession> VolumeControl.CoreAudio.AudioSessionManager.Sessions get
Gets the list of AudioSession instances currently being managed by this AudioSessionManager instance.
Referenced by VolumeControl.CoreAudio.AudioSessionManager.FindSessionWithProcessIdentifier(), VolumeControl.CoreAudio.AudioSessionSelector.SelectNextSession(), and VolumeControl.CoreAudio.AudioSessionSelector.SelectPreviousSession().
Event Documentation
SessionAddedToList
EventHandler<AudioSession>? VolumeControl.CoreAudio.AudioSessionManager.SessionAddedToList
Occurs when an AudioSession is added to the Sessions list for any reason.
SessionManagerAddedToList
EventHandler<AudioDeviceSessionManager>? VolumeControl.CoreAudio.AudioSessionManager.SessionManagerAddedToList
Occurs when an AudioDeviceSessionManager is added to the SessionManagers list for any reason.
SessionManagerRemovedFromList
EventHandler<AudioDeviceSessionManager>? VolumeControl.CoreAudio.AudioSessionManager.SessionManagerRemovedFromList
Occurs when an AudioDeviceSessionManager is removed from the SessionManagers list for any reason.
SessionRemovedFromList
EventHandler<AudioSession>? VolumeControl.CoreAudio.AudioSessionManager.SessionRemovedFromList
Occurs when an AudioSession is removed from the Sessions list for any reason.
Referenced by VolumeControl.CoreAudio.AudioSessionSelector.AudioSessionSelector().
The documentation for this class was generated from the following file:
/home/runner/work/volume-control/volume-control/VolumeControl.CoreAudio/AudioSessionManager.cs