Volume Control: VolumeControl.WPF.HorizontalScroll Class Reference
VolumeControl.WPF.HorizontalScroll Class Reference
WPF attached event for receiving horizontal scroll events sent by tiltable mouse wheels.
Static Public Member Functions
static void AddPreviewMouseWheelHorizontalHandler (DependencyObject d, MouseWheelHorizontalEventHandler handler)
Adds the specified handler to the PreviewMouseWheelHorizontalEvent.
static void RemovePreviewMouseWheelHorizontalHandler (DependencyObject d, MouseWheelHorizontalEventHandler handler)
Removes the specified handler from the PreviewMouseWheelHorizontalEvent.
static void AddMouseWheelHorizontalHandler (DependencyObject d, MouseWheelHorizontalEventHandler handler)
Adds the specified handler to the MouseWheelHorizontalEvent.
static void RemoveMouseWheelHorizontalHandler (DependencyObject d, MouseWheelHorizontalEventHandler handler)
Removes the specified handler from the MouseWheelHorizontalEvent.
Static Public Attributes
static readonly RoutedEvent PreviewMouseWheelHorizontalEvent
Occurs when the user tilts the mouse wheel while the mouse pointer is over this element.
static readonly RoutedEvent MouseWheelHorizontalEvent
Occurs when the user tilts the mouse wheel while the mouse pointer is over this element.
Detailed Description
WPF attached event for receiving horizontal scroll events sent by tiltable mouse wheels.
Member Function Documentation
AddMouseWheelHorizontalHandler()
static void VolumeControl.WPF.HorizontalScroll.AddMouseWheelHorizontalHandler (DependencyObject d, MouseWheelHorizontalEventHandler handler) static
Adds the specified handler to the MouseWheelHorizontalEvent.
References VolumeControl.WPF.HorizontalScroll.MouseWheelHorizontalEvent.
AddPreviewMouseWheelHorizontalHandler()
static void VolumeControl.WPF.HorizontalScroll.AddPreviewMouseWheelHorizontalHandler (DependencyObject d, MouseWheelHorizontalEventHandler handler) static
Adds the specified handler to the PreviewMouseWheelHorizontalEvent.
References VolumeControl.WPF.HorizontalScroll.PreviewMouseWheelHorizontalEvent.
Referenced by VolumeControl.WPF.Behaviors.ScrollViewerHorizontalScrollBehavior.OnAttached(), and VolumeControl.WPF.Behaviors.TextBoxHorizontalScrollBehavior.OnAttached().
RemoveMouseWheelHorizontalHandler()
static void VolumeControl.WPF.HorizontalScroll.RemoveMouseWheelHorizontalHandler (DependencyObject d, MouseWheelHorizontalEventHandler handler) static
Removes the specified handler from the MouseWheelHorizontalEvent.
RemovePreviewMouseWheelHorizontalHandler()
static void VolumeControl.WPF.HorizontalScroll.RemovePreviewMouseWheelHorizontalHandler (DependencyObject d, MouseWheelHorizontalEventHandler handler) static
Removes the specified handler from the PreviewMouseWheelHorizontalEvent.
Referenced by VolumeControl.WPF.Behaviors.ScrollViewerHorizontalScrollBehavior.OnDetaching(), and VolumeControl.WPF.Behaviors.TextBoxHorizontalScrollBehavior.OnDetaching().
Member Data Documentation
MouseWheelHorizontalEvent
readonly RoutedEvent VolumeControl.WPF.HorizontalScroll.MouseWheelHorizontalEvent static
Initial value:
= EventManager.RegisterRoutedEvent(
            "MouseWheelHorizontal",
            RoutingStrategy.Bubble,
            typeof(MouseWheelHorizontalEventHandler),
            typeof(WpfTiltScrollHook))
Occurs when the user tilts the mouse wheel while the mouse pointer is over this element.
Referenced by VolumeControl.WPF.HorizontalScroll.AddMouseWheelHorizontalHandler().
PreviewMouseWheelHorizontalEvent
readonly RoutedEvent VolumeControl.WPF.HorizontalScroll.PreviewMouseWheelHorizontalEvent static
Initial value:
= EventManager.RegisterRoutedEvent(
            "PreviewMouseWheelHorizontal",
            RoutingStrategy.Tunnel,
            typeof(MouseWheelHorizontalEventHandler),
            typeof(WpfTiltScrollHook))
Occurs when the user tilts the mouse wheel while the mouse pointer is over this element.
Referenced by VolumeControl.WPF.HorizontalScroll.AddPreviewMouseWheelHorizontalHandler().
The documentation for this class was generated from the following file:
/home/runner/work/volume-control/volume-control/VolumeControl.WPF/HorizontalScroll.cs