Volume Control: VolumeControl.WPF.HWndHook Class Reference
VolumeControl.WPF.HWndHook Class Reference
Handles receiving windows event messages.
Public Member Functions
HWndHook (HwndSource hWndSource)
HWndHook ()
void SetSource (HwndSource src, [CallerMemberName] string caller="")
Sets the HwndSource used to add and remove hooks.
void AddHook (HwndSourceHook hook, [CallerMemberName] string caller="")
Adds a message handler.
void RemoveHook (HwndSourceHook hook, [CallerMemberName] string caller="")
Removes a message handler.
void Dispose ()
Properties
IntPtr Handle [get]
Gets the current target handle from the hook source.
Detailed Description
Handles receiving windows event messages.
Constructor & Destructor Documentation
HWndHook()
VolumeControl.WPF.HWndHook.HWndHook (HwndSource hWndSource)
Parameters
hWndSource The main window's HwndSource object.
Member Function Documentation
AddHook()
void VolumeControl.WPF.HWndHook.AddHook (HwndSourceHook hook, [CallerMemberName] string caller = "")
Adds a message handler.
Parameters
hook The handler delegate to use.
caller Used for logging purposes.
References VolumeControl.Log.FLog.Debug().
RemoveHook()
void VolumeControl.WPF.HWndHook.RemoveHook (HwndSourceHook hook, [CallerMemberName] string caller = "")
Removes a message handler.
Parameters
hook The hook to remove.
caller Used for logging purposes.
References VolumeControl.Log.FLog.Debug(), and VolumeControl.Log.FLog.Warning().
SetSource()
void VolumeControl.WPF.HWndHook.SetSource (HwndSource src, [CallerMemberName] string caller = "")
Sets the HwndSource used to add and remove hooks.
Parameters
src A new source object.
caller Used for logging purposes.
References VolumeControl.Log.FLog.Debug().
Property Documentation
Handle
IntPtr VolumeControl.WPF.HWndHook.Handle get
Gets the current target handle from the hook source.
The documentation for this class was generated from the following file:
/home/runner/work/volume-control/volume-control/VolumeControl.WPF/HWndHook.cs