Volume Control: VolumeControl.Core.Input.HotkeyActionAddonLoader Class Reference
VolumeControl.Core.Input.HotkeyActionAddonLoader Class Reference
Provides methods to load HotkeyActionDefinition instances from types or assemblies using reflection.
Public Types
enum class MethodNamePart {
None = 0 , FullTypeNames = 1 , FullDeclaringTypeName = 2 , GenericParameters = 4 ,
ParameterTypes = 8 , ParameterNames = 16 , Parameters = ParameterTypes | ParameterNames , NonVoidReturnType = 32 ,
VoidReturnType = 64 , ReturnType = NonVoidReturnType | VoidReturnType
}
Static Public Member Functions
static string GetFullName (this MethodInfo method, MethodNamePart includedNameComponents)
static string GetFullName (this MethodInfo method)
static HotkeyActionDefinition[] Load (params Type[] types)
Loads hotkey actions from the specified types .
Detailed Description
Provides methods to load HotkeyActionDefinition instances from types or assemblies using reflection.
Member Enumeration Documentation
MethodNamePart
enum VolumeControl.Core.Input.HotkeyActionAddonLoader.MethodNamePart strong
Enumerator
None
Shows only the declaring type name and the method name, with empty brackets.
FullTypeNames
Shows namespace qualifiers for all types.
FullDeclaringTypeName
Shows namespace qualifiers for the declaring type.
GenericParameters
Shows generic type parameters.
ParameterTypes
Shows parameter types.
ParameterNames
Shows parameter names.
Parameters
Shows parameter types and names.
NonVoidReturnType
Shows the return type, but only if it isn't void.
VoidReturnType
Shows the return type, even if it is void.
ReturnType
Shows the return type.
Member Function Documentation
Load()
static HotkeyActionDefinition [] VolumeControl.Core.Input.HotkeyActionAddonLoader.Load (params Type[] types) static
Loads hotkey actions from the specified types .
Parameters
types Any number of Type instances that represent hotkey action group types.
Returns
List of HotkeyActionDefinition objects for all publicly-accessible action methods.
References VolumeControl.Core.Input.Actions.HotkeyActionDefinition.CreateInstance(), VolumeControl.Log.AsyncLogWriter.Debug(), VolumeControl.Log.AsyncLogWriter.Error(), VolumeControl.Log.AsyncLogWriter.FilterEventType(), VolumeControl.Log.FLog.Log, and VolumeControl.Log.AsyncLogWriter.Trace().
The documentation for this class was generated from the following file:
/home/runner/work/volume-control/volume-control/VolumeControl.Core/Input/HotkeyActionAddonLoader.cs