Volume Control: VolumeControl.Core.Input.HotkeyPressedEventArgs Class Reference
VolumeControl.Core.Input.HotkeyPressedEventArgs Class Reference
Event arguments for hotkey action events.
Public Member Functions
HotkeyPressedEventArgs ()
Creates a new HotkeyPressedEventArgs instance without any action settings.
HotkeyPressedEventArgs (bool defaultHandledValue)
Creates a new HotkeyPressedEventArgs instance without any action settings.
HotkeyPressedEventArgs (IActionSettingInstance[] actionSettings)
Creates a new HotkeyPressedEventArgs instance with the specified actionSettings .
HotkeyPressedEventArgs (IActionSettingInstance[] actionSettings, bool defaultHandledValue)
Creates a new HotkeyPressedEventArgs instance with the specified actionSettings .
IActionSettingInstance GetSetting (string name, StringComparison stringComparison=StringComparison.Ordinal)
Gets the action setting with the specified name .
IActionSettingInstance GetSetting (string name, Type valueType, StringComparison stringComparison=StringComparison.Ordinal)
Gets the action setting with the specified name and valueType .
IActionSettingInstance< T > GetSetting< T > (string name, StringComparison stringComparison=StringComparison.Ordinal)
Gets the action setting with the specified name and value type.
bool TryGetSetting (string name, StringComparison stringComparison, out IActionSettingInstance setting)
Attempts to get the action setting with the specified name .
bool TryGetSetting (string name, out IActionSettingInstance setting)
bool TryGetSetting (string name, Type valueType, StringComparison stringComparison, out IActionSettingInstance setting)
Attempts to get the action setting with the specified name and valueType .
bool TryGetSetting (string name, Type valueType, out IActionSettingInstance setting)
bool TryGetSetting< T > (string name, StringComparison stringComparison, out IActionSettingInstance< T > setting)
Gets the action setting with the specified name and value type.
bool TryGetSetting< T > (string name, out IActionSettingInstance< T > setting)
object GetValue (string name, StringComparison stringComparison=StringComparison.Ordinal)
Gets the value of the action setting with the specified name if it is enabled; otherwise gets the setting's default value.
object GetValue (string name, Type valueType, StringComparison stringComparison=StringComparison.Ordinal)
Gets the value of the action setting with the specified name and valueType if it is enabled; otherwise gets the setting's default value.
T GetValue< T > (string name, StringComparison stringComparison=StringComparison.Ordinal)
Gets the value of the action setting with the specified name and value type if it is enabled; otherwise gets the setting's default value.
bool TryGetValue (string name, StringComparison stringComparison, out object value)
Attempts to get the value of the action setting with the specified name if it is enabled; otherwise gets the setting's default value.
bool TryGetValue (string name, out object value)
bool TryGetValue (string name, Type valueType, StringComparison stringComparison, out object value)
Attempts to get the value of the action setting with the specified name and valueType if it is enabled; otherwise gets the setting's default value.
bool TryGetValue (string name, Type valueType, out object value)
bool TryGetValue< T > (string name, StringComparison stringComparison, out T value)
Attempts to get the value of the action setting with the specified name and value type if it is enabled; otherwise gets the setting's default value.
object GetValueOrDefault (string name, StringComparison stringComparison, object defaultValue=default!)
Gets the value of the action setting with the specified name if it isn't null or disabled.
object GetValueOrDefault (string name, object defaultValue=default!)
object GetValueOrDefault (string name, Type valueType, StringComparison stringComparison, object defaultValue=default!)
Gets the value of the action setting with the specified name and valueType if it isn't null or disabled.
object GetValueOrDefault (string name, Type valueType, object defaultValue=default!)
T GetValueOrDefault< T > (string name, StringComparison stringComparison, T defaultValue=default!)
Gets the value of the action setting with the specified name and value type if it isn't null or disabled.
T GetValueOrDefault< T > (string name, T defaultValue=default!)
Properties
IActionSettingInstance[] Settings [get]
Gets the array of ActionSettings configured for the hotkey that triggered the event.
Detailed Description
Event arguments for hotkey action events.
Constructor & Destructor Documentation
HotkeyPressedEventArgs() [1/4]
VolumeControl.Core.Input.HotkeyPressedEventArgs.HotkeyPressedEventArgs ()
Creates a new HotkeyPressedEventArgs instance without any action settings.
References VolumeControl.Core.Input.HotkeyPressedEventArgs.Settings.
HotkeyPressedEventArgs() [2/4]
VolumeControl.Core.Input.HotkeyPressedEventArgs.HotkeyPressedEventArgs (bool defaultHandledValue)
Creates a new HotkeyPressedEventArgs instance without any action settings.
Parameters
defaultHandledValue The default value for the HandledEventArgs.Handled property.
References VolumeControl.Core.Input.HotkeyPressedEventArgs.Settings.
HotkeyPressedEventArgs() [3/4]
VolumeControl.Core.Input.HotkeyPressedEventArgs.HotkeyPressedEventArgs (IActionSettingInstance[] actionSettings)
Creates a new HotkeyPressedEventArgs instance with the specified actionSettings .
Parameters
actionSettings The array of settings to send to the action method.
References VolumeControl.Core.Input.HotkeyPressedEventArgs.Settings.
HotkeyPressedEventArgs() [4/4]
VolumeControl.Core.Input.HotkeyPressedEventArgs.HotkeyPressedEventArgs (IActionSettingInstance[] actionSettings, bool defaultHandledValue)
Creates a new HotkeyPressedEventArgs instance with the specified actionSettings .
Parameters
actionSettings The array of settings to send to the action method.
defaultHandledValue The default value for the HandledEventArgs.Handled property.
References VolumeControl.Core.Input.HotkeyPressedEventArgs.Settings.
Member Function Documentation
GetSetting() [1/2]
IActionSettingInstance VolumeControl.Core.Input.HotkeyPressedEventArgs.GetSetting (string name, StringComparison stringComparison = StringComparison.Ordinal)
Gets the action setting with the specified name .
Parameters
name The name of the setting to get.
stringComparison The comparison type to use when performing string comparisons.
Returns
IActionSettingInstance with the specified name .
Exceptions
ActionSettingNotFoundException There is no action setting with the specified name .
References VolumeControl.Core.Input.HotkeyPressedEventArgs.Settings.
Referenced by VolumeControl.Core.Input.HotkeyPressedEventArgs.GetValue(), and VolumeControl.Core.Input.HotkeyPressedEventArgs.TryGetSetting().
GetSetting() [2/2]
IActionSettingInstance VolumeControl.Core.Input.HotkeyPressedEventArgs.GetSetting (string name, Type valueType, StringComparison stringComparison = StringComparison.Ordinal)
Gets the action setting with the specified name and valueType .
Parameters
name The name of the setting to get.
valueType The value type of the setting to get.
stringComparison The comparison type to use when performing string comparisons.
Returns
IActionSettingInstance with the specified name & valueType .
Exceptions
ActionSettingNotFoundException There is no action setting with the specified name & valueType .
References VolumeControl.Core.Input.HotkeyPressedEventArgs.Settings.
GetSetting< T >()
IActionSettingInstance<T> VolumeControl.Core.Input.HotkeyPressedEventArgs.GetSetting< T > (string name, StringComparison stringComparison = StringComparison.Ordinal)
Gets the action setting with the specified name and value type.
Template Parameters
T The value type of the setting to get.
Parameters
name The name of the setting to get.
stringComparison The comparison type to use when performing string comparisons.
Returns
IActionSettingInstance with the specified name and value type.
Exceptions
ActionSettingNotFoundException There is no action setting with the specified name and value type.
References VolumeControl.Core.Input.HotkeyPressedEventArgs.Settings.
Referenced by VolumeControl.Core.Input.HotkeyPressedEventArgs.GetValue< T >(), and VolumeControl.Core.Input.HotkeyPressedEventArgs.TryGetSetting< T >().
GetValue() [1/2]
object VolumeControl.Core.Input.HotkeyPressedEventArgs.GetValue (string name, StringComparison stringComparison = StringComparison.Ordinal)
Gets the value of the action setting with the specified name if it is enabled; otherwise gets the setting's default value.
Parameters
name The name of the action setting to get the value of.
stringComparison The type of StringComparison to use when comparing strings.
Returns
Value of the setting with the specified name when enabled; otherwise the default value.
Exceptions
ActionSettingNotFoundException There is no action setting with the specified name .
References VolumeControl.Core.Input.HotkeyPressedEventArgs.GetSetting().
Referenced by VolumeControl.Core.Input.HotkeyPressedEventArgs.TryGetValue().
GetValue() [2/2]
object VolumeControl.Core.Input.HotkeyPressedEventArgs.GetValue (string name, Type valueType, StringComparison stringComparison = StringComparison.Ordinal)
Gets the value of the action setting with the specified name and valueType if it is enabled; otherwise gets the setting's default value.
Parameters
name The name of the setting to get.
valueType The value type of the setting to get.
stringComparison The comparison type to use when performing string comparisons.
Returns
Value of the setting with the specified name & valueType when enabled; otherwise the default value.
Exceptions
ActionSettingNotFoundException There is no action setting with the specified name & valueType .
References VolumeControl.Core.Input.HotkeyPressedEventArgs.GetSetting().
GetValue< T >()
T VolumeControl.Core.Input.HotkeyPressedEventArgs.GetValue< T > (string name, StringComparison stringComparison = StringComparison.Ordinal)
Gets the value of the action setting with the specified name and value type if it is enabled; otherwise gets the setting's default value.
Template Parameters
T The value type of the action setting to get.
Parameters
name The name of the action setting to get the value of.
stringComparison The type of StringComparison to use when comparing strings.
Returns
Value of the setting with the specified name and value type when enabled; otherwise the default value.
Exceptions
ActionSettingNotFoundException There is no action setting with the specified name and value type.
References VolumeControl.Core.Input.HotkeyPressedEventArgs.GetSetting< T >().
Referenced by VolumeControl.Core.Input.HotkeyPressedEventArgs.TryGetValue< T >().
GetValueOrDefault() [1/2]
object VolumeControl.Core.Input.HotkeyPressedEventArgs.GetValueOrDefault (string name, StringComparison stringComparison, object defaultValue = default!)
Gets the value of the action setting with the specified name if it isn't null or disabled.
Parameters
name The name of the action setting to get the value of.
stringComparison The type of StringComparison to use when comparing strings.
defaultValue The value to return if the setting wasn't found, or if its value is null.
Returns
The value of the setting with the specified name if it exists and isn't null; otherwise defaultValue .
References VolumeControl.Core.Input.HotkeyPressedEventArgs.TryGetSetting().
GetValueOrDefault() [2/2]
object VolumeControl.Core.Input.HotkeyPressedEventArgs.GetValueOrDefault (string name, Type valueType, StringComparison stringComparison, object defaultValue = default!)
Gets the value of the action setting with the specified name and valueType if it isn't null or disabled.
Parameters
name The name of the action setting to get the value of.
valueType The value type of the setting to get.
stringComparison The type of StringComparison to use when comparing strings.
defaultValue The value to return if the setting wasn't found, or if its value is null.
Returns
The value of the setting with the specified name and valueType if it exists and isn't null; otherwise defaultValue .
References VolumeControl.Core.Input.HotkeyPressedEventArgs.TryGetSetting().
GetValueOrDefault< T >()
T VolumeControl.Core.Input.HotkeyPressedEventArgs.GetValueOrDefault< T > (string name, StringComparison stringComparison, T defaultValue = default!)
Gets the value of the action setting with the specified name and value type if it isn't null or disabled.
Template Parameters
T The value type of the action setting to get.
Parameters
name The name of the action setting to get the value of.
stringComparison The type of StringComparison to use when comparing strings.
defaultValue The value to return if the setting wasn't found, or if its value is null.
Returns
The value of the setting with the specified name and value type if it exists and isn't null; otherwise defaultValue .
References VolumeControl.Core.Input.HotkeyPressedEventArgs.TryGetSetting< T >().
TryGetSetting() [1/2]
bool VolumeControl.Core.Input.HotkeyPressedEventArgs.TryGetSetting (string name, StringComparison stringComparison, out IActionSettingInstance setting)
Attempts to get the action setting with the specified name .
Parameters
name The name of the setting to get.
stringComparison The comparison type to use when performing string comparisons.
setting IActionSettingInstance with the specified name .
Returns
true when the setting was found and isn't null; otherwise false.
References VolumeControl.Core.Input.HotkeyPressedEventArgs.GetSetting().
Referenced by VolumeControl.Core.Input.HotkeyPressedEventArgs.GetValueOrDefault().
TryGetSetting() [2/2]
bool VolumeControl.Core.Input.HotkeyPressedEventArgs.TryGetSetting (string name, Type valueType, StringComparison stringComparison, out IActionSettingInstance setting)
Attempts to get the action setting with the specified name and valueType .
Parameters
name The name of the setting to get.
valueType The value type of the setting to get.
stringComparison The comparison type to use when performing string comparisons.
setting IActionSettingInstance with the specified name & valueType .
Returns
true when the setting was found and isn't null; otherwise false.
References VolumeControl.Core.Input.HotkeyPressedEventArgs.GetSetting().
TryGetSetting< T >()
bool VolumeControl.Core.Input.HotkeyPressedEventArgs.TryGetSetting< T > (string name, StringComparison stringComparison, out IActionSettingInstance< T > setting)
Gets the action setting with the specified name and value type.
Template Parameters
T The value type of the setting to get.
Parameters
name The name of the setting to get.
stringComparison The comparison type to use when performing string comparisons.
setting IActionSettingInstance with the specified name and value type.
Returns
true when the setting was found and isn't null; otherwise false.
References VolumeControl.Core.Input.HotkeyPressedEventArgs.GetSetting< T >().
Referenced by VolumeControl.Core.Input.HotkeyPressedEventArgs.GetValueOrDefault< T >().
TryGetValue() [1/2]
bool VolumeControl.Core.Input.HotkeyPressedEventArgs.TryGetValue (string name, StringComparison stringComparison, out object value)
Attempts to get the value of the action setting with the specified name if it is enabled; otherwise gets the setting's default value.
Parameters
name The name of the action setting to get the value of.
stringComparison The type of StringComparison to use when comparing strings.
value Value of the setting with the specified name .
Returns
true when the setting was found and the value isn't null; otherwise false.
References VolumeControl.Core.Input.HotkeyPressedEventArgs.GetValue().
TryGetValue() [2/2]
bool VolumeControl.Core.Input.HotkeyPressedEventArgs.TryGetValue (string name, Type valueType, StringComparison stringComparison, out object value)
Attempts to get the value of the action setting with the specified name and valueType if it is enabled; otherwise gets the setting's default value.
Parameters
name The name of the setting to get.
valueType The value type of the setting to get.
stringComparison The comparison type to use when performing string comparisons.
value Value of the setting with the specified name & valueType .
Returns
true when the setting was found and the value isn't null; otherwise false.
References VolumeControl.Core.Input.HotkeyPressedEventArgs.GetValue().
TryGetValue< T >()
bool VolumeControl.Core.Input.HotkeyPressedEventArgs.TryGetValue< T > (string name, StringComparison stringComparison, out T value)
Attempts to get the value of the action setting with the specified name and value type if it is enabled; otherwise gets the setting's default value.
Template Parameters
T The value type of the action setting to get.
Parameters
name The name of the action setting to get the value of.
stringComparison The type of StringComparison to use when comparing strings.
value Value of the setting with the specified name and value type.
Returns
true when the setting was found and the value isn't null; otherwise false.
References VolumeControl.Core.Input.HotkeyPressedEventArgs.GetValue< T >().
Property Documentation
Settings
IActionSettingInstance [] VolumeControl.Core.Input.HotkeyPressedEventArgs.Settings get
Gets the array of ActionSettings configured for the hotkey that triggered the event.
Referenced by VolumeControl.Core.Input.HotkeyPressedEventArgs.GetSetting(), VolumeControl.Core.Input.HotkeyPressedEventArgs.GetSetting< T >(), and VolumeControl.Core.Input.HotkeyPressedEventArgs.HotkeyPressedEventArgs().
The documentation for this class was generated from the following file:
/home/runner/work/volume-control/volume-control/VolumeControl.Core/Input/HotkeyPressedEventArgs.cs