Volume Control: VolumeControl.Hotkeys.BindableWindowsHotkey Class Reference
VolumeControl.Hotkeys.BindableWindowsHotkey Class Reference
This is a wrapper object around HotkeyLib.WindowsHotkey that is designed for data binding.
Public Member Functions
BindableWindowsHotkey (HotkeyManager manager, string name, IKeyCombo keys, string action, bool registerNow=false)
void Dispose ()
void NotifyPressed (HandledEventArgs e)
Triggers a Pressed event.
void NotifyPressed ()
Triggers a Pressed event with the default arguments.
override string ToString ()
string Serialize ()
Serializes this hotkey into a string format.
This is used when saving the hotkey to the configuration file.
string GetFullIdentifier ()
Gets all properties in a pseudo-json format for dumping them to the log.
Static Public Member Functions
static BindableWindowsHotkey Parse (string hkString, HotkeyManager manager)
Parse a serialized hotkey string (hkString) into a usable BindableWindowsHotkey.
This is used when loading hotkeys from the configuration file.
Public Attributes
bool Valid => Hotkey.Valid
int ID => Hotkey.ID
Properties
WindowsHotkey Hotkey [get]
The underlying WindowsHotkey instance.
This shouldn't be used when data binding.
string Name [get, set]
Gets or sets this hotkey's name.
bool Registered [get, set]
string?? ActionName [get, set]
Gets or sets the name of the action associated with this hotkey.
IActionBinding? Action [get, set]
Gets or sets the action associated with this hotkey.
System.Windows.Forms.Keys Key [get, set]
Modifier Mod [get, set]
bool Alt [get, set]
bool Ctrl [get, set]
bool Shift [get, set]
bool Win [get, set]
KeyEventHandler Pressed
EventHandler KeysChanged
Properties inherited from HotkeyLib.IKeyCombo
Keys Key [get, set]
The primary key on the Keyboard.
Modifier Mod [get, set]
The modifier key bitfield.
bool Alt [get, set]
Get or set whether the Alt modifier key is enabled. This corresponds to the first bit in the modifier key bitfield. Both the left and right modifier keys apply here, there is no method available to limit the key combination to only the left or right modifier key.
bool Ctrl [get, set]
Get or set whether the Ctrl modifier key is enabled. This corresponds to the second bit in the modifier key bitfield. Both the left and right modifier keys apply here, there is no method available to limit the key combination to only the left or right modifier key.
bool Shift [get, set]
Get or set whether the Shift modifier key is enabled. This corresponds to the third bit in the modifier key bitfield. Both the left and right modifier keys apply here, there is no method available to limit the key combination to only the left or right modifier key.
bool Win [get, set]
Get or set whether the "Windows Key" (super) modifier key is enabled. This corresponds to the fourth bit in the modifier key bitfield. Both the left and right modifier keys apply here, there is no method available to limit the key combination to only the left or right modifier key.
bool Valid [get]
Checks if this KeyCombo instance contains a valid keyboard key combination.
Events
PropertyChangedEventHandler? PropertyChanged
Triggered after a property has been set.
PropertyChangingEventHandler? PropertyChanging
Triggered before a property is about to be set.
Detailed Description
This is a wrapper object around HotkeyLib.WindowsHotkey that is designed for data binding.
Constructor & Destructor Documentation
BindableWindowsHotkey()
VolumeControl.Hotkeys.BindableWindowsHotkey.BindableWindowsHotkey (HotkeyManager manager, string name, IKeyCombo keys, string action, bool registerNow = false)
Parameters
manager The hotkey manager to bind to.
name The name of this hotkey.
keys The key & modifiers of this hotkey.
action The action that this hotkey is bound to.
registerNow When true, the hotkey is registered in the constructor; otherwise, the hotkey starts as unregistered.
References VolumeControl.Hotkeys.BindableWindowsHotkey.ActionName, VolumeControl.Hotkeys.BindableWindowsHotkey.Hotkey, VolumeControl.Hotkeys.HotkeyManager.OwnerHandle, and VolumeControl.Hotkeys.BindableWindowsHotkey.Registered.
Member Function Documentation
GetFullIdentifier()
string VolumeControl.Hotkeys.BindableWindowsHotkey.GetFullIdentifier ()
Gets all properties in a pseudo-json format for dumping them to the log.
Returns
A human-readable, single-line string that includes all of this hotkey's current values.
Referenced by VolumeControl.Hotkeys.HotkeyManager.SaveHotkeys().
NotifyPressed() [1/2]
void VolumeControl.Hotkeys.BindableWindowsHotkey.NotifyPressed ()
Triggers a Pressed event with the default arguments.
NotifyPressed() [2/2]
void VolumeControl.Hotkeys.BindableWindowsHotkey.NotifyPressed (HandledEventArgs e)
Triggers a Pressed event.
Parameters
e HandledEventArgs to pass to the event.
Parse()
static BindableWindowsHotkey VolumeControl.Hotkeys.BindableWindowsHotkey.Parse (string hkString, HotkeyManager manager) static
Parse a serialized hotkey string (hkString) into a usable BindableWindowsHotkey.
This is used when loading hotkeys from the configuration file.
Parameters
hkString A serialized hotkey string.
manager The HotkeyManager instance to use when looking up action definitions.
Returns
A BindableWindowsHotkey class.
References HotkeyLib.KeyCombo.Parse().
Serialize()
string VolumeControl.Hotkeys.BindableWindowsHotkey.Serialize ()
Serializes this hotkey into a string format.
This is used when saving the hotkey to the configuration file.
Returns
A string containing this hotkey in serialized form.
Implements HotkeyLib.IKeyCombo.
Referenced by VolumeControl.Hotkeys.HotkeyManager.SaveHotkeys().
Property Documentation
Action
IActionBinding? VolumeControl.Hotkeys.BindableWindowsHotkey.Action get set
Gets or sets the action associated with this hotkey.
This property automatically handles changing the Pressed event.
ActionName
string?? VolumeControl.Hotkeys.BindableWindowsHotkey.ActionName get set
Gets or sets the name of the action associated with this hotkey.
This property automatically handles changing the Pressed event.
Referenced by VolumeControl.Hotkeys.BindableWindowsHotkey.BindableWindowsHotkey().
Hotkey
WindowsHotkey VolumeControl.Hotkeys.BindableWindowsHotkey.Hotkey get
The underlying WindowsHotkey instance.
This shouldn't be used when data binding.
Referenced by VolumeControl.Hotkeys.BindableWindowsHotkey.BindableWindowsHotkey(), and VolumeControl.Hotkeys.BindableWindowsHotkey.Dispose().
Name
string VolumeControl.Hotkeys.BindableWindowsHotkey.Name get set
Gets or sets this hotkey's name.
Event Documentation
PropertyChanged
PropertyChangedEventHandler? VolumeControl.Hotkeys.BindableWindowsHotkey.PropertyChanged
Triggered after a property has been set.
PropertyChanging
PropertyChangingEventHandler? VolumeControl.Hotkeys.BindableWindowsHotkey.PropertyChanging
Triggered before a property is about to be set.
The documentation for this class was generated from the following file:
/home/runner/work/volume-control/volume-control/VolumeControl.Hotkeys/BindableWindowsHotkey.cs