Volume Control: VolumeControl.CoreAudio.AudioDeviceManager Class Reference
VolumeControl.CoreAudio.AudioDeviceManager Class Reference
Manages a list of AudioDevice instances and related events.
Public Member Functions
AudioDeviceManager (DataFlow deviceDataFlow, MMDeviceEnumerator deviceEnumerator)
Creates a new AudioDeviceManager instance.
AudioDeviceManager (DataFlow deviceDataFlow)
Creates a new AudioDeviceManager instance.
AudioDevice? FindDeviceByID (string deviceID, StringComparison comparisonType=StringComparison.Ordinal)
Gets the AudioDevice instance associated with the given deviceID string. (MMDevice.ID)
AudioDevice? FindDeviceByMMDevice (MMDevice mmDevice)
Gets the AudioDevice instance associated with the given mmDevice .
AudioDevice? GetDefaultDevice (DataFlow dataFlow, Role deviceRole)
Gets the default device for the specified dataFlow & deviceRole .
void Dispose ()
Properties
IReadOnlyList< AudioDevice > Devices [get]
Gets the list of AudioDevice instances.
DataFlow DeviceDataFlow [get, set]
Gets the DataFlow type of the audio devices managed by this AudioDeviceManager instance.
Events
EventHandler< AudioDevice >? DeviceAddedToList
Occurs when an AudioDevice was added to the Devices list for any reason.
EventHandler< AudioDevice >? DeviceRemovedFromList
Occurs when an AudioDevice was removed from the Devices list for any reason.
EventHandler< AudioDevice >? DeviceStateChanged
Occurs when an AudioDevice instance's state was changed.
Detailed Description
Manages a list of AudioDevice instances and related events.
The AudioDeviceManager class is responsible for managing the list of active audio devices and handling all events related directly to AudioDevice instances.
Constructor & Destructor Documentation
AudioDeviceManager() [1/2]
VolumeControl.CoreAudio.AudioDeviceManager.AudioDeviceManager (DataFlow deviceDataFlow, MMDeviceEnumerator deviceEnumerator)
Creates a new AudioDeviceManager instance.
Parameters
deviceDataFlow The DataFlow type of the devices that this AudioDeviceManager instance will manage. This cannot be changed later.
deviceEnumerator The MMDeviceEnumerator instance to use.
References VolumeControl.Log.FLog.Critical(), and VolumeControl.CoreAudio.AudioDeviceManager.DeviceDataFlow.
AudioDeviceManager() [2/2]
VolumeControl.CoreAudio.AudioDeviceManager.AudioDeviceManager (DataFlow deviceDataFlow)
Creates a new AudioDeviceManager instance.
Parameters
deviceDataFlow The DataFlow type of the devices that this AudioDeviceManager instance will manage. This cannot be changed later.
Member Function Documentation
FindDeviceByID()
AudioDevice? VolumeControl.CoreAudio.AudioDeviceManager.FindDeviceByID (string deviceID, StringComparison comparisonType = StringComparison.Ordinal)
Gets the AudioDevice instance associated with the given deviceID string. (MMDevice.ID)
Parameters
deviceID The ID of the target device.
comparisonType The StringComparison type to use when comparing ID strings.
Returns
The AudioDevice associated with the given deviceID if found; otherwise null.
Referenced by VolumeControl.CoreAudio.AudioDeviceManager.GetDefaultDevice().
FindDeviceByMMDevice()
AudioDevice? VolumeControl.CoreAudio.AudioDeviceManager.FindDeviceByMMDevice (MMDevice mmDevice)
Gets the AudioDevice instance associated with the given mmDevice .
Parameters
mmDevice The MMDevice instance associated with the target device.
Returns
The AudioDevice associated with the given mmDevice if found; otherwise null.
GetDefaultDevice()
AudioDevice? VolumeControl.CoreAudio.AudioDeviceManager.GetDefaultDevice (DataFlow dataFlow, Role deviceRole)
Gets the default device for the specified dataFlow & deviceRole .
Parameters
dataFlow The DataFlow of the target device.
deviceRole The Role of the target device.
Returns
The default AudioDevice instance if one was found; otherwise, null.
References VolumeControl.Log.FLog.Error(), and VolumeControl.CoreAudio.AudioDeviceManager.FindDeviceByID().
Referenced by VolumeControl.CoreAudio.AudioDeviceSelector.SelectDefaultDevice().
Property Documentation
DeviceDataFlow
DataFlow VolumeControl.CoreAudio.AudioDeviceManager.DeviceDataFlow get set
Gets the DataFlow type of the audio devices managed by this AudioDeviceManager instance.
Referenced by VolumeControl.CoreAudio.AudioDeviceManager.AudioDeviceManager().
Devices
IReadOnlyList<AudioDevice> VolumeControl.CoreAudio.AudioDeviceManager.Devices get
Gets the list of AudioDevice instances.
Referenced by VolumeControl.CoreAudio.AudioDeviceManager.Dispose(), VolumeControl.CoreAudio.AudioDeviceSelector.SelectNextDevice(), and VolumeControl.CoreAudio.AudioDeviceSelector.SelectPreviousDevice().
Event Documentation
DeviceAddedToList
EventHandler<AudioDevice>? VolumeControl.CoreAudio.AudioDeviceManager.DeviceAddedToList
Occurs when an AudioDevice was added to the Devices list for any reason.
DeviceRemovedFromList
EventHandler<AudioDevice>? VolumeControl.CoreAudio.AudioDeviceManager.DeviceRemovedFromList
Occurs when an AudioDevice was removed from the Devices list for any reason.
Referenced by VolumeControl.CoreAudio.AudioDeviceSelector.AudioDeviceSelector().
DeviceStateChanged
EventHandler<AudioDevice>? VolumeControl.CoreAudio.AudioDeviceManager.DeviceStateChanged
Occurs when an AudioDevice instance's state was changed.
The documentation for this class was generated from the following file:
/home/runner/work/volume-control/volume-control/VolumeControl.CoreAudio/AudioDeviceManager.cs