var namespace_volume_control_1_1_unit_tests_1_1_w_p_f_1_1_converters =
[
    [ "BooleanInverter_Tests", "class_volume_control_1_1_unit_tests_1_1_w_p_f_1_1_converters_1_1_boolean_inverter___tests.html", "class_volume_control_1_1_unit_tests_1_1_w_p_f_1_1_converters_1_1_boolean_inverter___tests" ],
    [ "WindowHandleGetter_Tests", "class_volume_control_1_1_unit_tests_1_1_w_p_f_1_1_converters_1_1_window_handle_getter___tests.html", "class_volume_control_1_1_unit_tests_1_1_w_p_f_1_1_converters_1_1_window_handle_getter___tests" ]
];