Volume Control: VolumeControl.Core.Input.Json.JsonHotkey Struct Reference
VolumeControl.Core.Input.Json.JsonHotkey Struct Reference
Contains the JSON object representation of a Hotkey instance.
Public Member Functions
JsonHotkey (IHotkey hotkey)
Creates a new JsonHotkey instance using the specified hotkey .
JsonHotkey ()
Creates a new JsonHotkey instance with default values.
THotkey CreateInstance< THotkey > (HotkeyActionManager actionManager, bool deferRegistration=false)
Creates a new THotkey instance from this JsonHotkey struct, using the specified actionManager to resolve the ActionIdentifier.
Properties
string Name = string.Empty [get, set]
EFriendlyKey Key = EFriendlyKey.None [get, set]
EModifierKey Modifiers = EModifierKey.None [get, set]
bool IsRegistered = false [get, set]
string? ActionIdentifier = null [get, set]
Gets or sets the Identifier string of this hotkey's action.
Dictionary< string, JsonActionSettingValue >? ActionSettings = null [get, set]
Gets or sets the action settings dictionary containing the action settings for this hotkey's action.
Detailed Description
Contains the JSON object representation of a Hotkey instance.
Constructor & Destructor Documentation
JsonHotkey() [1/2]
VolumeControl.Core.Input.Json.JsonHotkey.JsonHotkey (IHotkey hotkey)
Creates a new JsonHotkey instance using the specified hotkey .
Parameters
hotkey An IHotkey instance to copy the values of.
References VolumeControl.Core.Input.IHotkey.Action, VolumeControl.Core.Input.Json.JsonHotkey.ActionIdentifier, VolumeControl.Core.Input.Actions.HotkeyActionInstance.ActionSettings, VolumeControl.Core.Input.Json.JsonHotkey.ActionSettings, VolumeControl.Core.Input.Actions.HotkeyActionInstance.Identifier, VolumeControl.Core.Input.IHotkey.IsRegistered, VolumeControl.Core.Input.Json.JsonHotkey.IsRegistered, VolumeControl.Core.Input.IHotkey.Key, VolumeControl.Core.Input.Json.JsonHotkey.Key, VolumeControl.Core.Input.IHotkey.Modifiers, VolumeControl.Core.Input.Json.JsonHotkey.Modifiers, VolumeControl.Core.Input.IHotkey.Name, and VolumeControl.Core.Input.Json.JsonHotkey.Name.
JsonHotkey() [2/2]
VolumeControl.Core.Input.Json.JsonHotkey.JsonHotkey ()
Creates a new JsonHotkey instance with default values.
Member Function Documentation
CreateInstance< THotkey >()
THotkey VolumeControl.Core.Input.Json.JsonHotkey.CreateInstance< THotkey > (HotkeyActionManager actionManager, bool deferRegistration = false)
Creates a new THotkey instance from this JsonHotkey struct, using the specified actionManager to resolve the ActionIdentifier.
Template Parameters
THotkey A hotkey type that derives from Hotkey.
Parameters
actionManager A HotkeyActionManager instance to use to resolve the ActionIdentifier.
deferRegistration When true, the created hotkey is not registered even if it should be.
Returns
A new THotkey instance.
Exceptions
InvalidOperationException Creating an instance of type THotkey failed.
Type Constraints
THotkey : Hotkey
References VolumeControl.Core.Input.Hotkey.Action, VolumeControl.Core.Input.Json.JsonHotkey.ActionIdentifier, VolumeControl.Core.Input.Json.JsonHotkey.ActionSettings, VolumeControl.Log.FLog.Error(), VolumeControl.Log.FLog.FilterEventType(), VolumeControl.Core.Input.Actions.HotkeyActionManager.FindActionDefinition(), VolumeControl.Core.Input.Json.JsonHotkey.IsRegistered, VolumeControl.Core.Input.Json.JsonHotkey.Key, VolumeControl.Core.Input.Json.JsonHotkey.Modifiers, and VolumeControl.Core.Input.Json.JsonHotkey.Name.
Property Documentation
ActionIdentifier
string? VolumeControl.Core.Input.Json.JsonHotkey.ActionIdentifier = null get set
Gets or sets the Identifier string of this hotkey's action.
Referenced by VolumeControl.Core.Input.Json.JsonHotkey.CreateInstance< THotkey >(), and VolumeControl.Core.Input.Json.JsonHotkey.JsonHotkey().
ActionSettings
Dictionary<string, JsonActionSettingValue>? VolumeControl.Core.Input.Json.JsonHotkey.ActionSettings = null get set
Gets or sets the action settings dictionary containing the action settings for this hotkey's action.
Referenced by VolumeControl.Core.Input.Json.JsonHotkey.CreateInstance< THotkey >(), and VolumeControl.Core.Input.Json.JsonHotkey.JsonHotkey().
The documentation for this struct was generated from the following file:
/home/runner/work/volume-control/volume-control/VolumeControl.Core/Input/Json/HotkeyJsonObject.cs