//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toastify.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Toastify.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toastify was unable to load the settings file.
        ///The application will be started with default values..
        /// </summary>
        internal static string ERROR_SETTINGS_UNABLE_TO_LOAD {
            get {
                return ResourceManager.GetString("ERROR_SETTINGS_UNABLE_TO_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find Spotify process!
        ///If Spotify is running, please open an issue at github.com/aleab/toastify..
        /// </summary>
        internal static string ERROR_STARTUP_PROCESS {
            get {
                return ResourceManager.GetString("ERROR_STARTUP_PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when trying to start Spotify.
        ///Please restart the application..
        /// </summary>
        internal static string ERROR_STARTUP_RESTART {
            get {
                return ResourceManager.GetString("ERROR_STARTUP_RESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when trying to start Spotify..
        /// </summary>
        internal static string ERROR_STARTUP_SPOTIFY {
            get {
                return ResourceManager.GetString("ERROR_STARTUP_SPOTIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toastify was not able to connect with Spotify..
        /// </summary>
        internal static string ERROR_STARTUP_SPOTIFY_API_CONNECT {
            get {
                return ResourceManager.GetString("ERROR_STARTUP_SPOTIFY_API_CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when trying to connect with Spotify.
        ///The firewall might have blocked the connection to &quot;open.spotify.com&quot;..
        /// </summary>
        internal static string ERROR_STARTUP_SPOTIFY_API_CONNECTION_BLOCKED {
            get {
                return ResourceManager.GetString("ERROR_STARTUP_SPOTIFY_API_CONNECTION_BLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when trying to connect with Spotify.
        ///The host address &quot;open.spotify.com&quot; might have been redirected by the client. Check your &quot;hosts&quot; file (%WinDir%\System32\drivers\etc\hosts) and delete any entry containing &quot;open.spotify.com&quot;..
        /// </summary>
        internal static string ERROR_STARTUP_SPOTIFY_API_CONNECTION_BLOCKED_HOSTS {
            get {
                return ResourceManager.GetString("ERROR_STARTUP_SPOTIFY_API_CONNECTION_BLOCKED_HOSTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when trying to connect with Spotify: SpotifyAPI returned a null status.
        ///Please open an issue at github.com/aleab/toastify..
        /// </summary>
        internal static string ERROR_STARTUP_SPOTIFY_API_STATUS_NULL {
            get {
                return ResourceManager.GetString("ERROR_STARTUP_SPOTIFY_API_STATUS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find Spotify executable.
        ///Try to start Spotify manually before launching Toastify..
        /// </summary>
        internal static string ERROR_STARTUP_SPOTIFY_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_STARTUP_SPOTIFY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toastify timed out while trying to start, find or connect to Spotify..
        /// </summary>
        internal static string ERROR_STARTUP_SPOTIFY_TIMEOUT {
            get {
                return ResourceManager.GetString("ERROR_STARTUP_SPOTIFY_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find Spotify main window.
        ///Try to start Spotify manually before launching Toastify..
        /// </summary>
        internal static string ERROR_STARTUP_SPOTIFY_WINDOW_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_STARTUP_SPOTIFY_WINDOW_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred when trying to start Spotify..
        /// </summary>
        internal static string ERROR_UNKNOWN {
            get {
                return ResourceManager.GetString("ERROR_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toastify is already running!
        ///Look for the blue icon in your system tray..
        /// </summary>
        internal static string INFO_TOASTIFY_ALREADY_RUNNING {
            get {
                return ResourceManager.GetString("INFO_TOASTIFY_ALREADY_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon toastify_loading_spotify_0 {
            get {
                object obj = ResourceManager.GetObject("toastify_loading_spotify_0", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon toastify_loading_spotify_1 {
            get {
                object obj = ResourceManager.GetObject("toastify_loading_spotify_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon toastify_loading_spotify_10 {
            get {
                object obj = ResourceManager.GetObject("toastify_loading_spotify_10", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon toastify_loading_spotify_11 {
            get {
                object obj = ResourceManager.GetObject("toastify_loading_spotify_11", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon toastify_loading_spotify_12 {
            get {
                object obj = ResourceManager.GetObject("toastify_loading_spotify_12", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon toastify_loading_spotify_13 {
            get {
                object obj = ResourceManager.GetObject("toastify_loading_spotify_13", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon toastify_loading_spotify_14 {
            get {
                object obj = ResourceManager.GetObject("toastify_loading_spotify_14", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon toastify_loading_spotify_15 {
            get {
                object obj = ResourceManager.GetObject("toastify_loading_spotify_15", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon toastify_loading_spotify_16 {
            get {
                object obj = ResourceManager.GetObject("toastify_loading_spotify_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon toastify_loading_spotify_17 {
            get {
                object obj = ResourceManager.GetObject("toastify_loading_spotify_17", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon toastify_loading_spotify_18 {
            get {
                object obj = ResourceManager.GetObject("toastify_loading_spotify_18", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon toastify_loading_spotify_19 {
            get {
                object obj = ResourceManager.GetObject("toastify_loading_spotify_19", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon toastify_loading_spotify_2 {
            get {
                object obj = ResourceManager.GetObject("toastify_loading_spotify_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon toastify_loading_spotify_20 {
            get {
                object obj = ResourceManager.GetObject("toastify_loading_spotify_20", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon toastify_loading_spotify_21 {
            get {
                object obj = ResourceManager.GetObject("toastify_loading_spotify_21", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon toastify_loading_spotify_22 {
            get {
                object obj = ResourceManager.GetObject("toastify_loading_spotify_22", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon toastify_loading_spotify_23 {
            get {
                object obj = ResourceManager.GetObject("toastify_loading_spotify_23", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon toastify_loading_spotify_3 {
            get {
                object obj = ResourceManager.GetObject("toastify_loading_spotify_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon toastify_loading_spotify_4 {
            get {
                object obj = ResourceManager.GetObject("toastify_loading_spotify_4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon toastify_loading_spotify_5 {
            get {
                object obj = ResourceManager.GetObject("toastify_loading_spotify_5", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon toastify_loading_spotify_6 {
            get {
                object obj = ResourceManager.GetObject("toastify_loading_spotify_6", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon toastify_loading_spotify_7 {
            get {
                object obj = ResourceManager.GetObject("toastify_loading_spotify_7", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon toastify_loading_spotify_8 {
            get {
                object obj = ResourceManager.GetObject("toastify_loading_spotify_8", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon toastify_loading_spotify_9 {
            get {
                object obj = ResourceManager.GetObject("toastify_loading_spotify_9", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ToastifyIcon {
            get {
                object obj = ResourceManager.GetObject("ToastifyIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
